Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (set args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"5.15.0-1003-realtime"},"dpdk_dir":"/root/dpdk-stable-20.11.3/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.239.183.130","run_time":"600","pf1":"ens4f0","os":"rehat","pf1_bandwidth":"100"},"pkg_generator":{"host":"10.239.182.88","pf1":"ens785f0"},"run_type":"ipv4"}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4Dqouna/UALz1cds/DYDIib12lRO4R4U9QQgmUx/wyv5AAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgEJMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAnLfKUwgAAAA==[0m[Pipeline] script
[8mha:////4JUhH4fIWh5icAEY6zBr3HRHHu0lnMalVyM2fPsu3/3sAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgIhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD0QKVszCAAAA[0m[Pipeline] {
[8mha:////4PJRxj8hD/CuSHgtWDRwAQ67XTdBRcldvWih24U4ysBWAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCoEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AHN/bm5vgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics -s -m nicIperfTcpGuestStress --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nicIperfTcpGuestStress_ipv4_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 16 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-28 05:57:42 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-03-28/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]_05_57_42/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img].log, case_logdir: /root/testconfig/testlogs/2022-03-28/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]_05_57_42
2022-03-28 05:57:42 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
2022-03-28 05:57:42 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-28 05:57:42 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-28 05:57:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 05:57:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-28 05:57:43 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-28 05:57:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-28 05:57:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 05:57:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-28 05:57:43 - test_network_sriov_stress.py - [line:54] - root - INFO - start to rmmod irdma....
2022-03-28 05:57:46 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-03-28 05:57:46 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:57:51 - test_network_sriov_stress.py - [line:57] - root - INFO - finished rmmod irdma....
2022-03-28 05:57:51 - test_network_sriov_stress.py - [line:58] - root - INFO - start to rmmod ice....
2022-03-28 05:57:54 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-03-28 05:58:00 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:58:05 - test_network_sriov_stress.py - [line:61] - root - INFO - finished rmmod ice....
2022-03-28 05:58:05 - test_network_sriov_stress.py - [line:63] - root - INFO - start to modprobe ice....
2022-03-28 05:58:08 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-03-28 05:58:43 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:58:48 - test_network_sriov_stress.py - [line:65] - root - INFO - finished modprobe ice....
2022-03-28 05:58:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 up
2022-03-28 05:58:51 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:58:59 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens4f0
2022-03-28 05:58:59 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-28 05:59:04 - test_network_sriov_stress.py - [line:75] - root - INFO - trying to get ipv6 addr for pf1
2022-03-28 05:59:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0
2022-03-28 05:59:07 - sshInstance.py - [line:54] - root - INFO - ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 2032 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 05:59:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-03-28 05:59:15 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 11044502613  bytes 16714338814660 (15.2 TiB)
        RX errors 0  dropped 11391  overruns 0  frame 0
        TX packets 124556578  bytes 8221871737 (7.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 05:59:23 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep ens4f0 | awk '{print $1;}'
2022-03-28 05:59:23 - sshInstance.py - [line:54] - root - INFO - 0000:6f:00.0

2022-03-28 05:59:28 - test_network_sriov_stress.py - [line:122] - root - INFO - pf_id was found: 0000:6f:00.0

2022-03-28 05:59:28 - test_network_sriov_stress.py - [line:839] - root - INFO - format_pf_id is 0000\:6f\:00.0

2022-03-28 05:59:28 - test_network_sriov_stress.py - [line:842] - root - INFO - pf_id_key: 6f
2022-03-28 05:59:34 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 05:59:34 - sshInstance.py - [line:100] - root - INFO - Last login: Sun Mar 27 20:42:52 2022 from 10.112.97.60
RTNETLINK answers: File exists
[?2004hroot@npx-SPR-automation:~# ifconfig ens4f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 05:59:37 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: ens4f0
2022-03-28 05:59:43 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 05:59:43 - sshInstance.py - [line:100] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 28 04:44:33 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-03-28 05:59:46 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-03-28 05:59:49 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 05:59:53 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:59:58 - test_network_sriov_stress.py - [line:136] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-28 06:00:01 - sshInstance.py - [line:50] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-28 06:00:01 - sshInstance.py - [line:54] - root - INFO - 6f:01.0
6f:01.1
6f:01.2
6f:01.3

2022-03-28 06:00:06 - test_network_sriov_stress.py - [line:150] - root - INFO - Succssfully Gotten vf_id list:

2022-03-28 06:00:09 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-03-28 06:00:09 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:00:17 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
2022-03-28 06:00:18 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:00:23 - test_network_sriov_stress.py - [line:183] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-28 06:00:26 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
2022-03-28 06:00:27 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:00:32 - test_network_sriov_stress.py - [line:183] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-28 06:00:32 - test_network_sriov_stress.py - [line:863] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-28 06:00:35 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-28 06:00:35 - sshInstance.py - [line:54] - root - INFO - 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-28 06:00:40 - test_network_sriov_stress.py - [line:875] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-28 06:00:40 - test_network_sriov_stress.py - [line:206] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-28 06:00:43 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-28 06:00:43 - sshInstance.py - [line:54] - root - INFO - yes

2022-03-28 06:00:48 - test_network_sriov_stress.py - [line:209] - root - INFO - Default network is active? yes

2022-03-28 06:00:52 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-28 06:00:54 - sshInstance.py - [line:75] - root - INFO - 
Starting install...
2022-03-28 06:00:57 - sshInstance.py - [line:75] - root - INFO - Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:01:25 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:01:28 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully created a VM: VMtest1
2022-03-28 06:01:32 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole
[?2004l
2022-03-28 06:01:34 - sshInstance.py - [line:75] - root - INFO - 
Starting install...
2022-03-28 06:01:37 - sshInstance.py - [line:75] - root - INFO - Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:02:05 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:02:08 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully created a VM: VMtest2
2022-03-28 06:02:11 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-28 06:02:11 - sshInstance.py - [line:54] - root - INFO - 192.168.122.233/24

2022-03-28 06:02:16 - test_network_sriov_stress.py - [line:259] - root - INFO - Successfully got VMtest1 IP: 192.168.122.233/24

2022-03-28 06:02:19 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-28 06:02:19 - sshInstance.py - [line:54] - root - INFO - 192.168.122.205/24

2022-03-28 06:02:24 - test_network_sriov_stress.py - [line:259] - root - INFO - Successfully got VMtest2 IP: 192.168.122.205/24

2022-03-28 06:02:28 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.233
[?2004lPING 192.168.122.233 (192.168.122.233) 56(84) bytes of data.
64 bytes from 192.168.122.233: icmp_seq=1 ttl=64 time=0.220 ms
2022-03-28 06:02:29 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=2 ttl=64 time=0.171 ms
2022-03-28 06:02:30 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=3 ttl=64 time=0.188 ms
2022-03-28 06:02:31 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=4 ttl=64 time=0.182 ms
2022-03-28 06:02:32 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=5 ttl=64 time=0.206 ms

--- 192.168.122.233 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.171/0.193/0.220/0.017 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:03:03 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:12 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:12 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.233
[?2004lThe authenticity of host '192.168.122.233 (192.168.122.233)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (18 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-28 06:03:21 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:21 - sshInstance.py - [line:100] - root - INFO - yes
Warning: Permanently added '192.168.122.233' (ED25519) to the list of known hosts.
root@192.168.122.233's password: 
2022-03-28 06:03:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:31 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:13:35 PM EDT
  System load:  0.47               Processes:               175
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.233
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:18:51 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.cVxBPXz4jz which is empty
root@localhost:~# 
2022-03-28 06:03:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:40 - sshInstance.py - [line:100] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
2022-03-28 06:03:46 - test_network_sriov_stress.py - [line:355] - root - INFO - successfully got vf pci id of vm1: 0000:05:00.0
2022-03-28 06:03:52 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:52 - sshInstance.py - [line:100] - root - INFO - ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
2022-03-28 06:03:57 - test_network_sriov_stress.py - [line:369] - root - INFO - Successfully got vf device name of vm1: enp5s0
2022-03-28 06:04:03 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:03 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 192.168.10.12
root@localhost:~# 
2022-03-28 06:04:06 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: enp5s0
2022-03-28 06:04:12 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:12 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 down
root@localhost:~# 
2022-03-28 06:04:22 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:22 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 hw ether 1234567890ac
root@localhost:~# 
2022-03-28 06:04:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:31 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 up
root@localhost:~# 
2022-03-28 06:04:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:40 - sshInstance.py - [line:100] - root - INFO - nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
2022-03-28 06:04:49 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:49 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1032 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 21  bytes 2790 (2.7 KB)
        TX errors 2  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-28 06:04:58 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:58 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.233 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:05:05 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.205
[?2004lPING 192.168.122.205 (192.168.122.205) 56(84) bytes of data.
64 bytes from 192.168.122.205: icmp_seq=1 ttl=64 time=0.384 ms
2022-03-28 06:05:06 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=2 ttl=64 time=0.166 ms
2022-03-28 06:05:07 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=3 ttl=64 time=0.181 ms
2022-03-28 06:05:08 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=4 ttl=64 time=0.143 ms
2022-03-28 06:05:09 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=5 ttl=64 time=0.193 ms

--- 192.168.122.205 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.143/0.213/0.384/0.086 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:05:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:05:50 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:05:50 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.205
[?2004lThe authenticity of host '192.168.122.205 (192.168.122.205)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (19 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-28 06:05:59 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:05:59 - sshInstance.py - [line:100] - root - INFO - yes
Warning: Permanently added '192.168.122.205' (ED25519) to the list of known hosts.
root@192.168.122.205's password: 
2022-03-28 06:06:09 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:09 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:16:12 PM EDT
  System load:  0.12               Processes:               182
  Usage of /:   39.3% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.205
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:14:59 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.D4FQ7jhCFt which is empty
root@localhost:~# 
2022-03-28 06:06:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:18 - sshInstance.py - [line:100] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
2022-03-28 06:06:24 - test_network_sriov_stress.py - [line:355] - root - INFO - successfully got vf pci id of vm1: 0000:05:00.0
2022-03-28 06:06:30 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:30 - sshInstance.py - [line:100] - root - INFO - ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
2022-03-28 06:06:35 - test_network_sriov_stress.py - [line:369] - root - INFO - Successfully got vf device name of vm1: enp5s0
2022-03-28 06:06:41 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:41 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 192.168.10.13
root@localhost:~# 
2022-03-28 06:06:44 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: enp5s0
2022-03-28 06:06:50 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:50 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 down
root@localhost:~# 
2022-03-28 06:07:00 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:00 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 hw ether 1234567890ab
root@localhost:~# 
2022-03-28 06:07:09 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:09 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 up
root@localhost:~# 
2022-03-28 06:07:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:18 - sshInstance.py - [line:100] - root - INFO - nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
2022-03-28 06:07:27 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:27 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 7  bytes 2418 (2.4 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 14  bytes 1932 (1.9 KB)
        TX errors 2  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-28 06:07:36 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:36 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.205 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:07:43 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.205
[?2004lPING 192.168.122.205 (192.168.122.205) 56(84) bytes of data.
64 bytes from 192.168.122.205: icmp_seq=1 ttl=64 time=0.331 ms
2022-03-28 06:07:44 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=2 ttl=64 time=0.200 ms
2022-03-28 06:07:45 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=3 ttl=64 time=0.199 ms
2022-03-28 06:07:46 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=4 ttl=64 time=0.213 ms
2022-03-28 06:07:47 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=5 ttl=64 time=0.195 ms

--- 192.168.122.205 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.195/0.227/0.331/0.052 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:08:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:27 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:27 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.205
[?2004lroot@192.168.122.205's password: 
2022-03-28 06:08:37 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:37 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:18:40 PM EDT
  System load:  0.02               Processes:               151
  Usage of /:   39.3% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.205
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.13

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 18:16:13 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
2022-03-28 06:08:46 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:46 - sshInstance.py - [line:100] - root - INFO - nohup iperf -s -V&
[1] 1152
root@localhost:~# 
root@localhost:~# nohup: ignoring input and appending output to 'nohup.out'

2022-03-28 06:08:55 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:55 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.205 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:09:04 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:09:04 - sshInstance.py - [line:100] - root - INFO - nohup iperf -s -V&
[1] 227356
[root@CYP10RT ~]# 
[root@CYP10RT ~]# nohup: ignoring input and appending output to 'nohup.out'

2022-03-28 06:09:11 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.233
[?2004lPING 192.168.122.233 (192.168.122.233) 56(84) bytes of data.
64 bytes from 192.168.122.233: icmp_seq=1 ttl=64 time=0.248 ms
2022-03-28 06:09:12 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=2 ttl=64 time=0.194 ms
2022-03-28 06:09:13 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=3 ttl=64 time=0.180 ms
2022-03-28 06:09:14 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=4 ttl=64 time=0.197 ms
2022-03-28 06:09:15 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=5 ttl=64 time=0.225 ms

--- 192.168.122.233 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.180/0.208/0.248/0.024 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:09:46 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:09:55 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:09:55 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.233
[?2004lroot@192.168.122.233's password: 
2022-03-28 06:10:05 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:10:05 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:20:08 PM EDT
  System load:  0.0                Processes:               154
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.233
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.12

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 18:13:35 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
2022-03-28 06:10:14 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:10:14 - sshInstance.py - [line:100] - root - INFO - rm -rf /tmp/*.txt
root@localhost:~# 
2022-03-28 06:20:33 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:20:33 - sshInstance.py - [line:100] - root - INFO - iperf -c 192.168.10.13 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_vm2.txt
root@localhost:~# 
2022-03-28 06:30:53 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:30:53 - sshInstance.py - [line:100] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_sut2.txt
root@localhost:~# 
2022-03-28 06:31:02 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:31:02 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.233 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:31:11 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:31:11 - sshInstance.py - [line:100] - root - INFO - rm -rf /tmp/*.txt
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:41:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:41:31 - sshInstance.py - [line:100] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_sut1_sut2.txt
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:41:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:41:40 - sshInstance.py - [line:100] - root - INFO - scp root@192.168.122.233:/tmp/*.txt /tmp
[?2004lroot@192.168.122.233's password: 
2022-03-28 06:41:49 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:41:49 - sshInstance.py - [line:100] - root - INFO - 
iperf_ipv4_vm1_sut2.txt                         0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_sut2.txt                       100%  298KB  70.5MB/s   00:00    
iperf_ipv4_vm1_vm2.txt                          0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_vm2.txt                        100%  298KB  91.9MB/s   00:00    
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:41:52 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: rm -rf /tmp/*.txt....
2022-03-28 06:41:52 - commonFunc.py - [line:30] - root - INFO - 
2022-03-28 06:41:52 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: rm -rf /tmp/*.txt
F2022-03-28 06:41:52 - test_network_sriov_stress.py - [line:84] - root - INFO - removing VMs: VMtest1, VMtest2
2022-03-28 06:41:55 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest2
2022-03-28 06:41:57 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest2' destroyed


2022-03-28 06:42:02 - test_network_sriov_stress.py - [line:291] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-28 06:42:05 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest2
2022-03-28 06:42:05 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest2' has been undefined


2022-03-28 06:42:10 - test_network_sriov_stress.py - [line:301] - root - INFO - Successfully removed the VM: VMtest2
2022-03-28 06:42:13 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest1
2022-03-28 06:42:15 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest1' destroyed


2022-03-28 06:42:20 - test_network_sriov_stress.py - [line:291] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-28 06:42:23 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest1
2022-03-28 06:42:23 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest1' has been undefined


2022-03-28 06:42:28 - test_network_sriov_stress.py - [line:301] - root - INFO - Successfully removed the VM: VMtest1
2022-03-28 06:42:31 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 06:42:35 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:42:43 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 0
2022-03-28 06:42:43 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:42:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 0
2022-03-28 06:42:51 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:42:59 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-28 06:42:59 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:43:04 - test_network_sriov_stress.py - [line:93] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-28 06:43:04 - test_network_sriov_stress.py - [line:95] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-28/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]_05_57_42
2022-03-28 06:43:07 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-03-28 06:43:07 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:43:12 - test_network_sriov_stress.py - [line:97] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-28 06:43:12 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-03-28 06:43:12 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
                  [100%]

=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f8ee04fe940>
vm1_image = 'uvm1.img', vm2_image = 'uvm2.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicStress
    @pytest.mark.nicIperfTcpGuestStress
    @pytest.mark.SriovVfIperf
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Virtualization_SRIOV_VF_Stress_L(self, vm1_image, vm2_image):
        run_type = settings.__getattribute__("run_type")
        pf_id, status = self.get_pf_id(self.client, self.pf_name)
        # transfer pf_id to 0000\:00\:00.0 format
        if not pf_id:
            assert 200 == status
        else:
            pf_id_format = pf_id.replace(":", "\\:", 2)
            logging.info("format_pf_id is {}".format(pf_id_format))
            # get the number key of pf_id
            pf_id_key = pf_id.split(":")[1]
            logging.info("pf_id_key: {}".format(pf_id_key))
            # assign IP to PF in SUT and sut2
            sut1_pf_ip = "192.168.10.10"
            sut2_pf_ip = "192.168.10.11"
            assert 200 == self.assign_ip_ehternet(self.session, sut1_pf_ip, self.pf_name)
            assert 200 == self.assign_ip_ehternet(self.session2, sut2_pf_ip, self.pf2_name)
            # virtulize the pf to vfs
            assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
            # get vf ids
            vf_id_list, status = self.get_vf_ids(self.client, pf_id_key)
            vf_id_list = [i.strip() for i in vf_id_list]
            if status == 200:
                # modprobe vfio-pci
                assert 200 == self.modprobe("vfio-pci")
                # bind vf with vfio-pci
                host_dev_id_list, status = self.bind_vf_to_vfio_pci(self.client, vf_id_list)
                assert 200 == status
            else:
                assert 200 == status
            # get vF device id
            cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
            logging.info(cmd)
            vf_device_id = ""
            vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
            vf_device_id_rs = vf_device_id_rs.strip()
            if vf_device_id_rs:
                st = False
                vf_device_id = None
                for one in vf_device_id_rs.split(" "):
                    one = " " + one + " "
                    if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                        vf_device_id = one.replace("[", "").replace("]", "").strip()
                if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                logging.info("Successfully get vf device id: {}".format(vf_device_id))
                assert 200 == 200
            else:
                logging.error("Fail to get vf device id.")
                assert 200 == 400
            # set network
            status = self.default_network_isActive(self.client, self.defult_network)
            if status == "no":
                assert 200 == self.start_default_network(self.defult_network)
    
            # start VMs
            if self.sut_info["os"] == "UBUNTU":
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0],  self.vm1_name, "ubuntu20.04", "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "ubuntu20.04", "5901")
            else:
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "rhel8.2", "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "rhel8.2", "5901")
            # get VM ssh IP
            vm1_ip, status1 = self.get_vm_ip(self.vm1_name)
            vm2_ip, status2 = self.get_vm_ip(self.vm2_name)
    
            # ssh VM1 to set VF
            # ssh VM1 to set VF
            vm1_vf_ip = "192.168.10.12"
            vm2_vf_ip = "192.168.10.13"
            assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                              vm1_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
            vm1_vf_name, vm1_ipv6, status = self.ssh_vm_set_VF(vm1_ip, vf_device_id, vm1_vf_ip, "1234567890ac")
            self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
    
            assert 200 == status, "vm1 vf related settings failed"
            assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                              vm2_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
            vm2_vf_name, vm2_ipv6, status = self.ssh_vm_set_VF(vm2_ip, vf_device_id, vm2_vf_ip, "1234567890ab")
            self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
            assert 200 == status, "vm2 vf related settings failed"
    
            ping_time = self.sut_info["run_time"]
            assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                              vm2_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
            # vm2 and sut2 run iperf -s
            self.ssh_sut.run_ssh_cmd(self.session, "nohup iperf -s -V&\n\n")
            self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
            self.ssh_sut.run_ssh_cmd(self.session2, "nohup iperf -s -V&\n\n")
            #ssh to vm1
            assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                              vm1_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
            #vm1 iperf cmd other
            self.vm1_iperf_other(ping_time, vm2_vf_ip, vm2_ipv6, vm1_vf_name, sut2_pf_ip,run_type)
            self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
            # rm sut1 txt file
            cmd_rm_file = "rm -rf /tmp/*.txt\n"
            self.ssh_sut.run_ssh_cmd(self.session, cmd_rm_file)
            self.sut1_iperf_sut2(ping_time, sut2_pf_ip,run_type)
            #scp txt file form vm1
            self.ssh_sut.run_ssh_cmd(self.session, "scp root@{}:/tmp/*.txt /tmp\n".format(vm1_ip))
            self.ssh_sut.run_ssh_cmd(self.session, "password\n")
            #rm control txt file in /tmp
            localcmd = CommonFunc()
            localcmd.run_cmd("rm -rf /tmp/*.txt")
            #check result
>           self.check_iperf_log(ping_time,run_type)

npxtester/Tests/testNics/test_network_sriov_stress.py:936: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f8ee04fe940>
ping_time = '600', run_type = 'ipv4'

    def check_iperf_log(self, ping_time,run_type):
        timeout = int(ping_time) + 60
    
        if run_type == "ipv4":
            filelist = [
                {"filename": "iperf_ipv4_vm1_vm2.txt", "err_message": "iperf vm1 vm2 ipv4 is error", "rs": 400,"st": False},
                {"filename": "iperf_ipv4_vm1_sut2.txt", "err_message": "iperf vm2 sut2 ipv4 is error", "rs": 400,"st": False},
                {"filename": "iperf_ipv4_sut1_sut2.txt", "err_message": "iperf sut1 sut2 ipv4 is error", "rs": 400,"st": False},
            ]
        if run_type == "ipv6":
            filelist = [
                {"filename": "iperf_ipv6_vm1_vm2.txt", "err_message": "iperf vm1 vm2 ipv6 is error", "rs": 400,"st": False},
                {"filename": "iperf_ipv6_vm1_sut2.txt", "err_message": "iperf vm2 sut2 ipv6 is error", "rs": 400,"st": False},
                {"filename": "iperf_ipv6_sut1_sut2.txt", "err_message": "iperf sut1 sut2 ipv6 is error", "rs": 400,"st": False},
            ]
        tm = 0
        while True:
            for dt in filelist:
                st, code = self.check_content_rs(dt["filename"])
                if st:
                    dt["st"] = st
                    dt["rs"] = code
            all_st = True
            for dt in filelist:
                if not dt["st"]:
                    all_st = False
            if all_st:
                break
    
            time.sleep(10)
            tm = tm + 10
            if tm > timeout:
                break
        for dt in filelist:
>           assert 200 == dt["rs"], dt["err_message"]
E           AssertionError: iperf vm1 vm2 ipv4 is error
E           assert 200 == 400

npxtester/Tests/testNics/test_network_sriov_stress.py:821: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-28 05:57:42 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-03-28/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]_05_57_42/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img].log, case_logdir: /root/testconfig/testlogs/2022-03-28/test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]_05_57_42
2022-03-28 05:57:42 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img] case ============================
2022-03-28 05:57:42 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-28 05:57:42 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-28 05:57:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 05:57:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-28 05:57:43 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-28 05:57:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-28 05:57:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 05:57:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-28 05:57:43 - test_network_sriov_stress.py - [line:54] - root - INFO - start to rmmod irdma....
2022-03-28 05:57:46 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-03-28 05:57:46 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:57:51 - test_network_sriov_stress.py - [line:57] - root - INFO - finished rmmod irdma....
2022-03-28 05:57:51 - test_network_sriov_stress.py - [line:58] - root - INFO - start to rmmod ice....
2022-03-28 05:57:54 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-03-28 05:58:00 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:58:05 - test_network_sriov_stress.py - [line:61] - root - INFO - finished rmmod ice....
2022-03-28 05:58:05 - test_network_sriov_stress.py - [line:63] - root - INFO - start to modprobe ice....
2022-03-28 05:58:08 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-03-28 05:58:43 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:58:48 - test_network_sriov_stress.py - [line:65] - root - INFO - finished modprobe ice....
2022-03-28 05:58:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 up
2022-03-28 05:58:51 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:58:59 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens4f0
2022-03-28 05:58:59 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-28 05:59:04 - test_network_sriov_stress.py - [line:75] - root - INFO - trying to get ipv6 addr for pf1
2022-03-28 05:59:07 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0
2022-03-28 05:59:07 - sshInstance.py - [line:54] - root - INFO - ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 2032 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 05:59:15 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-03-28 05:59:15 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 11044502613  bytes 16714338814660 (15.2 TiB)
        RX errors 0  dropped 11391  overruns 0  frame 0
        TX packets 124556578  bytes 8221871737 (7.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-03-28 05:59:23 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep ens4f0 | awk '{print $1;}'
2022-03-28 05:59:23 - sshInstance.py - [line:54] - root - INFO - 0000:6f:00.0

2022-03-28 05:59:28 - test_network_sriov_stress.py - [line:122] - root - INFO - pf_id was found: 0000:6f:00.0

2022-03-28 05:59:28 - test_network_sriov_stress.py - [line:839] - root - INFO - format_pf_id is 0000\:6f\:00.0

2022-03-28 05:59:28 - test_network_sriov_stress.py - [line:842] - root - INFO - pf_id_key: 6f
2022-03-28 05:59:34 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 05:59:34 - sshInstance.py - [line:100] - root - INFO - Last login: Sun Mar 27 20:42:52 2022 from 10.112.97.60
RTNETLINK answers: File exists
[?2004hroot@npx-SPR-automation:~# ifconfig ens4f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 05:59:37 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: ens4f0
2022-03-28 05:59:43 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 05:59:43 - sshInstance.py - [line:100] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 28 04:44:33 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-03-28 05:59:46 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-03-28 05:59:49 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 05:59:53 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 05:59:58 - test_network_sriov_stress.py - [line:136] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-28 06:00:01 - sshInstance.py - [line:50] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-28 06:00:01 - sshInstance.py - [line:54] - root - INFO - 6f:01.0
6f:01.1
6f:01.2
6f:01.3

2022-03-28 06:00:06 - test_network_sriov_stress.py - [line:150] - root - INFO - Succssfully Gotten vf_id list:

2022-03-28 06:00:09 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-03-28 06:00:09 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:00:17 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
2022-03-28 06:00:18 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:00:23 - test_network_sriov_stress.py - [line:183] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-28 06:00:26 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
2022-03-28 06:00:27 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 06:00:32 - test_network_sriov_stress.py - [line:183] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-28 06:00:32 - test_network_sriov_stress.py - [line:863] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-28 06:00:35 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-28 06:00:35 - sshInstance.py - [line:54] - root - INFO - 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-28 06:00:40 - test_network_sriov_stress.py - [line:875] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-28 06:00:40 - test_network_sriov_stress.py - [line:206] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-28 06:00:43 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-28 06:00:43 - sshInstance.py - [line:54] - root - INFO - yes

2022-03-28 06:00:48 - test_network_sriov_stress.py - [line:209] - root - INFO - Default network is active? yes

2022-03-28 06:00:52 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-28 06:00:54 - sshInstance.py - [line:75] - root - INFO - 
Starting install...
2022-03-28 06:00:57 - sshInstance.py - [line:75] - root - INFO - Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:01:25 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:01:28 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully created a VM: VMtest1
2022-03-28 06:01:32 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole
[?2004l
2022-03-28 06:01:34 - sshInstance.py - [line:75] - root - INFO - 
Starting install...
2022-03-28 06:01:37 - sshInstance.py - [line:75] - root - INFO - Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:02:05 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:02:08 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully created a VM: VMtest2
2022-03-28 06:02:11 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-28 06:02:11 - sshInstance.py - [line:54] - root - INFO - 192.168.122.233/24

2022-03-28 06:02:16 - test_network_sriov_stress.py - [line:259] - root - INFO - Successfully got VMtest1 IP: 192.168.122.233/24

2022-03-28 06:02:19 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-28 06:02:19 - sshInstance.py - [line:54] - root - INFO - 192.168.122.205/24

2022-03-28 06:02:24 - test_network_sriov_stress.py - [line:259] - root - INFO - Successfully got VMtest2 IP: 192.168.122.205/24

2022-03-28 06:02:28 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.233
[?2004lPING 192.168.122.233 (192.168.122.233) 56(84) bytes of data.
64 bytes from 192.168.122.233: icmp_seq=1 ttl=64 time=0.220 ms
2022-03-28 06:02:29 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=2 ttl=64 time=0.171 ms
2022-03-28 06:02:30 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=3 ttl=64 time=0.188 ms
2022-03-28 06:02:31 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=4 ttl=64 time=0.182 ms
2022-03-28 06:02:32 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=5 ttl=64 time=0.206 ms

--- 192.168.122.233 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.171/0.193/0.220/0.017 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:03:03 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:12 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:12 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.233
[?2004lThe authenticity of host '192.168.122.233 (192.168.122.233)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (18 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-28 06:03:21 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:21 - sshInstance.py - [line:100] - root - INFO - yes
Warning: Permanently added '192.168.122.233' (ED25519) to the list of known hosts.
root@192.168.122.233's password: 
2022-03-28 06:03:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:31 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:13:35 PM EDT
  System load:  0.47               Processes:               175
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.233
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:18:51 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.cVxBPXz4jz which is empty
root@localhost:~# 
2022-03-28 06:03:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:40 - sshInstance.py - [line:100] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
2022-03-28 06:03:46 - test_network_sriov_stress.py - [line:355] - root - INFO - successfully got vf pci id of vm1: 0000:05:00.0
2022-03-28 06:03:52 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:03:52 - sshInstance.py - [line:100] - root - INFO - ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
2022-03-28 06:03:57 - test_network_sriov_stress.py - [line:369] - root - INFO - Successfully got vf device name of vm1: enp5s0
2022-03-28 06:04:03 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:03 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 192.168.10.12
root@localhost:~# 
2022-03-28 06:04:06 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: enp5s0
2022-03-28 06:04:12 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:12 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 down
root@localhost:~# 
2022-03-28 06:04:22 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:22 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 hw ether 1234567890ac
root@localhost:~# 
2022-03-28 06:04:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:31 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 up
root@localhost:~# 
2022-03-28 06:04:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:40 - sshInstance.py - [line:100] - root - INFO - nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
2022-03-28 06:04:49 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:49 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1032 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 21  bytes 2790 (2.7 KB)
        TX errors 2  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-28 06:04:58 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:04:58 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.233 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:05:05 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.205
[?2004lPING 192.168.122.205 (192.168.122.205) 56(84) bytes of data.
64 bytes from 192.168.122.205: icmp_seq=1 ttl=64 time=0.384 ms
2022-03-28 06:05:06 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=2 ttl=64 time=0.166 ms
2022-03-28 06:05:07 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=3 ttl=64 time=0.181 ms
2022-03-28 06:05:08 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=4 ttl=64 time=0.143 ms
2022-03-28 06:05:09 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=5 ttl=64 time=0.193 ms

--- 192.168.122.205 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.143/0.213/0.384/0.086 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:05:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:05:50 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:05:50 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.205
[?2004lThe authenticity of host '192.168.122.205 (192.168.122.205)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (19 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-28 06:05:59 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:05:59 - sshInstance.py - [line:100] - root - INFO - yes
Warning: Permanently added '192.168.122.205' (ED25519) to the list of known hosts.
root@192.168.122.205's password: 
2022-03-28 06:06:09 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:09 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:16:12 PM EDT
  System load:  0.12               Processes:               182
  Usage of /:   39.3% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.205
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:14:59 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.D4FQ7jhCFt which is empty
root@localhost:~# 
2022-03-28 06:06:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:18 - sshInstance.py - [line:100] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
2022-03-28 06:06:24 - test_network_sriov_stress.py - [line:355] - root - INFO - successfully got vf pci id of vm1: 0000:05:00.0
2022-03-28 06:06:30 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:30 - sshInstance.py - [line:100] - root - INFO - ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
2022-03-28 06:06:35 - test_network_sriov_stress.py - [line:369] - root - INFO - Successfully got vf device name of vm1: enp5s0
2022-03-28 06:06:41 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:41 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 192.168.10.13
root@localhost:~# 
2022-03-28 06:06:44 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: enp5s0
2022-03-28 06:06:50 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:06:50 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 down
root@localhost:~# 
2022-03-28 06:07:00 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:00 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 hw ether 1234567890ab
root@localhost:~# 
2022-03-28 06:07:09 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:09 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 up
root@localhost:~# 
2022-03-28 06:07:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:18 - sshInstance.py - [line:100] - root - INFO - nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
2022-03-28 06:07:27 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:27 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 7  bytes 2418 (2.4 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 14  bytes 1932 (1.9 KB)
        TX errors 2  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-28 06:07:36 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:07:36 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.205 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:07:43 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.205
[?2004lPING 192.168.122.205 (192.168.122.205) 56(84) bytes of data.
64 bytes from 192.168.122.205: icmp_seq=1 ttl=64 time=0.331 ms
2022-03-28 06:07:44 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=2 ttl=64 time=0.200 ms
2022-03-28 06:07:45 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=3 ttl=64 time=0.199 ms
2022-03-28 06:07:46 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=4 ttl=64 time=0.213 ms
2022-03-28 06:07:47 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.205: icmp_seq=5 ttl=64 time=0.195 ms

--- 192.168.122.205 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.195/0.227/0.331/0.052 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:08:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:27 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:27 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.205
[?2004lroot@192.168.122.205's password: 
2022-03-28 06:08:37 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:37 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:18:40 PM EDT
  System load:  0.02               Processes:               151
  Usage of /:   39.3% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.205
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.13

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 18:16:13 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
2022-03-28 06:08:46 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:46 - sshInstance.py - [line:100] - root - INFO - nohup iperf -s -V&
[1] 1152
root@localhost:~# 
root@localhost:~# nohup: ignoring input and appending output to 'nohup.out'

2022-03-28 06:08:55 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:08:55 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.205 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:09:04 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:09:04 - sshInstance.py - [line:100] - root - INFO - nohup iperf -s -V&
[1] 227356
[root@CYP10RT ~]# 
[root@CYP10RT ~]# nohup: ignoring input and appending output to 'nohup.out'

2022-03-28 06:09:11 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.233
[?2004lPING 192.168.122.233 (192.168.122.233) 56(84) bytes of data.
64 bytes from 192.168.122.233: icmp_seq=1 ttl=64 time=0.248 ms
2022-03-28 06:09:12 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=2 ttl=64 time=0.194 ms
2022-03-28 06:09:13 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=3 ttl=64 time=0.180 ms
2022-03-28 06:09:14 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=4 ttl=64 time=0.197 ms
2022-03-28 06:09:15 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.233: icmp_seq=5 ttl=64 time=0.225 ms

--- 192.168.122.233 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.180/0.208/0.248/0.024 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:09:46 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:09:55 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:09:55 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.233
[?2004lroot@192.168.122.233's password: 
2022-03-28 06:10:05 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:10:05 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:20:08 PM EDT
  System load:  0.0                Processes:               154
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.233
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.12

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 18:13:35 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
2022-03-28 06:10:14 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:10:14 - sshInstance.py - [line:100] - root - INFO - rm -rf /tmp/*.txt
root@localhost:~# 
2022-03-28 06:20:33 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:20:33 - sshInstance.py - [line:100] - root - INFO - iperf -c 192.168.10.13 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_vm2.txt
root@localhost:~# 
2022-03-28 06:30:53 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:30:53 - sshInstance.py - [line:100] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_sut2.txt
root@localhost:~# 
2022-03-28 06:31:02 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:31:02 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.233 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:31:11 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:31:11 - sshInstance.py - [line:100] - root - INFO - rm -rf /tmp/*.txt
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:41:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:41:31 - sshInstance.py - [line:100] - root - INFO - iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_sut1_sut2.txt
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:41:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:41:40 - sshInstance.py - [line:100] - root - INFO - scp root@192.168.122.233:/tmp/*.txt /tmp
[?2004lroot@192.168.122.233's password: 
2022-03-28 06:41:49 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 06:41:49 - sshInstance.py - [line:100] - root - INFO - 
iperf_ipv4_vm1_sut2.txt                         0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_sut2.txt                       100%  298KB  70.5MB/s   00:00    
iperf_ipv4_vm1_vm2.txt                          0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_vm2.txt                        100%  298KB  91.9MB/s   00:00    
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 06:41:52 - commonFunc.py - [line:16] - root - INFO - starting to execute the cmd: rm -rf /tmp/*.txt....
2022-03-28 06:41:52 - commonFunc.py - [line:30] - root - INFO - 
2022-03-28 06:41:52 - commonFunc.py - [line:31] - root - INFO - finished exeucting the cmd: rm -rf /tmp/*.txt
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:50 /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep ens4f0 | awk '{print $1;}'
INFO     root:sshInstance.py:54 0000:6f:00.0

INFO     root:test_network_sriov_stress.py:122 pf_id was found: 0000:6f:00.0

INFO     root:test_network_sriov_stress.py:839 format_pf_id is 0000\:6f\:00.0

INFO     root:test_network_sriov_stress.py:842 pf_id_key: 6f
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 Last login: Sun Mar 27 20:42:52 2022 from 10.112.97.60
RTNETLINK answers: File exists
[?2004hroot@npx-SPR-automation:~# ifconfig ens4f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
INFO     root:test_network_sriov_stress.py:316 Successfully assigned ip to ethernet: ens4f0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 28 04:44:33 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
INFO     root:test_network_sriov_stress.py:316 Successfully assigned ip to ethernet: ens785f0
INFO     root:sshInstance.py:50 echo 4 > /sys/class/net/ens4f0/device/sriov_numvfs
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:136 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:50  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:54 6f:01.0
6f:01.1
6f:01.2
6f:01.3

INFO     root:test_network_sriov_stress.py:150 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:50 modprobe vfio-pci

INFO     root:sshInstance.py:54 
INFO     root:sshInstance.py:50 /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:183 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:50 /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:183 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:863 lspci -Dnn | grep 6f:01.1
INFO     root:sshInstance.py:50 lspci -Dnn | grep 6f:01.1
INFO     root:sshInstance.py:54 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:875 Successfully get vf device id: 8086:1889
INFO     root:test_network_sriov_stress.py:206 get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:54 yes

INFO     root:test_network_sriov_stress.py:209 Default network is active? yes

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
INFO     root:sshInstance.py:75 
Starting install...
INFO     root:sshInstance.py:75 Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:test_network_sriov_stress.py:247 Successfully created a VM: VMtest1
INFO     root:sshInstance.py:75 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole
[?2004l
INFO     root:sshInstance.py:75 
Starting install...
INFO     root:sshInstance.py:75 Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:test_network_sriov_stress.py:247 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:50 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:54 192.168.122.233/24

INFO     root:test_network_sriov_stress.py:259 Successfully got VMtest1 IP: 192.168.122.233/24

INFO     root:sshInstance.py:50 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:54 192.168.122.205/24

INFO     root:test_network_sriov_stress.py:259 Successfully got VMtest2 IP: 192.168.122.205/24

INFO     root:sshInstance.py:75 ping -c 5 192.168.122.233
[?2004lPING 192.168.122.233 (192.168.122.233) 56(84) bytes of data.
64 bytes from 192.168.122.233: icmp_seq=1 ttl=64 time=0.220 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=2 ttl=64 time=0.171 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=3 ttl=64 time=0.188 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=4 ttl=64 time=0.182 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=5 ttl=64 time=0.206 ms

--- 192.168.122.233 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.171/0.193/0.220/0.017 ms
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ssh root@192.168.122.233
[?2004lThe authenticity of host '192.168.122.233 (192.168.122.233)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (18 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 yes
Warning: Permanently added '192.168.122.233' (ED25519) to the list of known hosts.
root@192.168.122.233's password: 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:13:35 PM EDT
  System load:  0.47               Processes:               175
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.233
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:18:51 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.cVxBPXz4jz which is empty
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 successfully got vf pci id of vm1: 0000:05:00.0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:369 Successfully got vf device name of vm1: enp5s0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 192.168.10.12
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:316 Successfully assigned ip to ethernet: enp5s0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 down
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 hw ether 1234567890ac
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 up
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1032 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 21  bytes 2790 (2.7 KB)
        TX errors 2  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 exit
logout
Connection to 192.168.122.233 closed.
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:75 ping -c 5 192.168.122.205
[?2004lPING 192.168.122.205 (192.168.122.205) 56(84) bytes of data.
64 bytes from 192.168.122.205: icmp_seq=1 ttl=64 time=0.384 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=2 ttl=64 time=0.166 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=3 ttl=64 time=0.181 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=4 ttl=64 time=0.143 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=5 ttl=64 time=0.193 ms

--- 192.168.122.205 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.143/0.213/0.384/0.086 ms
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ssh root@192.168.122.205
[?2004lThe authenticity of host '192.168.122.205 (192.168.122.205)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (19 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 yes
Warning: Permanently added '192.168.122.205' (ED25519) to the list of known hosts.
root@192.168.122.205's password: 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:16:12 PM EDT
  System load:  0.12               Processes:               182
  Usage of /:   39.3% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.205
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:14:59 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.D4FQ7jhCFt which is empty
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 successfully got vf pci id of vm1: 0000:05:00.0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:369 Successfully got vf device name of vm1: enp5s0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 192.168.10.13
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:316 Successfully assigned ip to ethernet: enp5s0
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 down
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 hw ether 1234567890ab
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0 up
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 7  bytes 2418 (2.4 KB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 14  bytes 1932 (1.9 KB)
        TX errors 2  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 exit
logout
Connection to 192.168.122.205 closed.
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:75 ping -c 5 192.168.122.205
[?2004lPING 192.168.122.205 (192.168.122.205) 56(84) bytes of data.
64 bytes from 192.168.122.205: icmp_seq=1 ttl=64 time=0.331 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=2 ttl=64 time=0.200 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=3 ttl=64 time=0.199 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=4 ttl=64 time=0.213 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.205: icmp_seq=5 ttl=64 time=0.195 ms

--- 192.168.122.205 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.195/0.227/0.331/0.052 ms
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ssh root@192.168.122.205
[?2004lroot@192.168.122.205's password: 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:18:40 PM EDT
  System load:  0.02               Processes:               151
  Usage of /:   39.3% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.205
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.13

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 18:16:13 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 nohup iperf -s -V&
[1] 1152
root@localhost:~# 
root@localhost:~# nohup: ignoring input and appending output to 'nohup.out'

INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 exit
logout
Connection to 192.168.122.205 closed.
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 nohup iperf -s -V&
[1] 227356
[root@CYP10RT ~]# 
[root@CYP10RT ~]# nohup: ignoring input and appending output to 'nohup.out'

INFO     root:sshInstance.py:75 ping -c 5 192.168.122.233
[?2004lPING 192.168.122.233 (192.168.122.233) 56(84) bytes of data.
64 bytes from 192.168.122.233: icmp_seq=1 ttl=64 time=0.248 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=2 ttl=64 time=0.194 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=3 ttl=64 time=0.180 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=4 ttl=64 time=0.197 ms
INFO     root:sshInstance.py:75 64 bytes from 192.168.122.233: icmp_seq=5 ttl=64 time=0.225 ms

--- 192.168.122.233 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.180/0.208/0.248/0.024 ms
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 ssh root@192.168.122.233
[?2004lroot@192.168.122.233's password: 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 06:20:08 PM EDT
  System load:  0.0                Processes:               154
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.233
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.12

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 18:13:35 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 rm -rf /tmp/*.txt
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 iperf -c 192.168.10.13 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_vm2.txt
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_vm1_sut2.txt
root@localhost:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 exit
logout
Connection to 192.168.122.233 closed.
[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 rm -rf /tmp/*.txt
[?2004l[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 iperf -c 192.168.10.11 -i 1 -f g -P 9 -t 600 > /tmp/iperf_ipv4_sut1_sut2.txt
[?2004l[?2004hroot@npx-SPR-automation:~# 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 scp root@192.168.122.233:/tmp/*.txt /tmp
[?2004lroot@192.168.122.233's password: 
INFO     root:sshInstance.py:98 --cmd is end--
INFO     root:sshInstance.py:100 
iperf_ipv4_vm1_sut2.txt                         0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_sut2.txt                       100%  298KB  70.5MB/s   00:00    
iperf_ipv4_vm1_vm2.txt                          0%    0     0.0KB/s   --:-- ETAiperf_ipv4_vm1_vm2.txt                        100%  298KB  91.9MB/s   00:00    
[?2004hroot@npx-SPR-automation:~# 
INFO     root:commonFunc.py:16 starting to execute the cmd: rm -rf /tmp/*.txt....
INFO     root:commonFunc.py:30 
INFO     root:commonFunc.py:31 finished exeucting the cmd: rm -rf /tmp/*.txt
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:74
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_iperf_client_4hour.py:74: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:121
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_iperf_client_4hour.py:121: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:396
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_network_sriov_stress.py:396: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:521
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_network_sriov_stress.py:521: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:829
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_network_sriov_stress.py:829: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:84
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_nics.py:84: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:111
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_nics.py:111: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:141
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_nics.py:141: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:212
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_nics.py:212: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:238
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_nics.py:238: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:281
  /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/Tests/testNics/test_nics.py:281: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nicIperfTcpGuestStress_ipv4_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Virtualization_SRIOV_VF_Stress_L[uvm1.img-uvm2.img]
========== 1 failed, 16 deselected, 15 warnings in 2729.78s (0:45:29) ==========
[8mha:////4DDaF6xD1n97fCJC17HEPtC4MvFSxjBMoUPdpyGs71EZAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AGMzKKgvgAAAA==[0m[Pipeline] echo
1
[8mha:////4JdwCG2vyNU1vR63Cq0h1I9fweuZdBzoUYFbNZMa07ZpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAcw+QVkfcu1r/wFPn4+LvgAAAA==[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4J0lAWMm8HuBR5s3oE3lokuIt9KB2+AHQUkjEiJ+aQGpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPMKRSIUQVVorDS8w8WGcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThyM6JEGS7GzwrvR5CUmDsPV8SR6voiOKbJD0eLUssZmwZYTwpKihJWEDVLnOFoyCbayVw9VOUWmOqeQv6OE0uo7PKGQ2ZxUSF+YA+xuo45MP89fAcw+Qbk/5Kpr/wEOrpSSvgAAAA==[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4Mt0DSsxkJzZfVcF7hGhEOllvDy/ttdaA/Rf0YiZvcahAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAQ1CqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKYhQrk95Nrthw/JONXdvgAAAA==[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/spr-test-nicIperfTcpGuestStress_ipv4/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4BJ3niM699yfMaO4XlYckMNVxHBxF/A/6tXrT01aXGOTAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigSgQSkVrueEFJjHGiXUXbAen4kV8jT9gEYmKLVY728zrDcvgoWZvsNPUWwqNxcGNJi9M7Pur44QdX7BhCuw0Sp0kt/o0o+SoYU5RwkLASlPjOFgyEdaiUw9VOUWmOkefv6OA0rZ3eEIhsjkqH78wedjcxjYw/Tx/BTANQ4Ryt8+1PXwARMxJg74AAAA=[0m[Pipeline] }
[8mha:////4KLOGR+83vgrLFidGueNeEu4h+87+yS5qW1q0kigPKEkAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu32u7eEDfI7acr4AAAA=[0m[Pipeline] // script
[8mha:////4B/bjeg5xruNbbx3kITLupXWvVAJcKllvbrOrw34K5MTAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiQZECUaW10vACExvjxLoztkNS8SK+xh+wiETFFqudbeb1hnUMcOJgsNc0WIqdRe9GkxdOHIar4wl7vmDHFNlpbPXUstLNgi0nDUuKElYCNpo6x9GSSbAVvXzIykky1TmF/B0FlFbd4QmFyOYkQ/rCHGB3G1Vk+nn+CmD2PkF5qHPt6w9IQDkpvgAAAA==[0m[Pipeline] }
[8mha:////4Pysn2p6Cuaw38A5WKCzX3hZbaQrVsudvseeZZRTcVjBAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu0Ou7f4DC8Jor74AAAA=[0m[Pipeline] // stage
[8mha:////4AtNwyaW/AZqBd3OKxZrkWfAC6zB3HxngMFQ9sJmqFs1AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEGIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsP/+idkr0AAAA=[0m[Pipeline] }
[8mha:////4I5dJP3UyABwbWbQZBRGWAtgfXC/GfHsQ3SW1rlV0+rIAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBlS/sHL0AAAA=[0m[Pipeline] // node
[8mha:////4OCxxHdXTRYePL6pNSOSjI/nVmiKF6Ardumg4UkWHzykAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBszaLVr0AAAA=[0m[Pipeline] End of Pipeline
Finished: FAILURE
