Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (set args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-21.02/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.239.182.209","run_time":"600","connect_switch_sut_pf":"ens785f2","pf1":"ens785f2","os":"RHEL"},"pkg_generator":{"host":"10.239.182.79","pf1":"ens787f2"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics -s -m nicSriov2hours --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov2hours_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 20 items / 19 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-05-02 04:41:33 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-05-02/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img]_04_41_33/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img].log, case_logdir: /root/testconfig/testlogs/2022-05-02/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img]_04_41_33
2022-05-02 04:41:33 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-05-02 04:41:33 - test_network_sriov_stress.py - [line:32] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-05-02 04:41:33 - test_network_sriov_stress.py - [line:50] - root - INFO - ssh to the sut1
2022-05-02 04:41:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-05-02 04:41:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-05-02 04:41:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-05-02 04:41:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-05-02 04:41:34 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-05-02 04:41:34 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-05-02 04:41:34 - test_network_sriov_stress.py - [line:64] - root - INFO - clean up iperf and taskset process...
2022-05-02 04:41:37 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-05-02 04:41:37 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:41:45 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-05-02 04:41:45 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:41:53 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-05-02 04:41:53 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:01 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-05-02 04:42:01 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:06 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 3] Opened sftp connection (server version 3)
2022-05-02 04:42:06 - sshInstance.py - [line:201] - root - INFO - start to rmmod irdma....
2022-05-02 04:42:09 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-05-02 04:42:09 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-05-02 04:42:14 - sshInstance.py - [line:204] - root - INFO - finished rmmod irdma....
2022-05-02 04:42:14 - sshInstance.py - [line:205] - root - INFO - start to rmmod ice....
2022-05-02 04:42:17 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-05-02 04:42:26 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:31 - sshInstance.py - [line:208] - root - INFO - finished rmmod ice....
2022-05-02 04:42:31 - sshInstance.py - [line:210] - root - INFO - start to modprobe ice....
2022-05-02 04:42:34 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-05-02 04:42:38 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:43 - sshInstance.py - [line:212] - root - INFO - finished modprobe ice....
2022-05-02 04:42:46 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-05-02 04:42:46 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-05-02 04:42:51 - test_network_sriov_stress.py - [line:71] - root - INFO - try to get ipv6 for ens785f2
2022-05-02 04:42:51 - test_network_sriov_stress.py - [line:73] - root - INFO - try to get ipv6 of pf for redhat...
2022-05-02 04:42:51 - sshInstance.py - [line:188] - root - INFO - starting to delete network of ens785f2:
2022-05-02 04:42:57 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon May  2 04:52:38 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (03aaab02-a667-40d0-8493-e3f2f4b8cc7f) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:00 - sshInstance.py - [line:190] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:43:06 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:09 - sshInstance.py - [line:194] - root - INFO - starting to add network of ens785f2:
2022-05-02 04:43:15 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (24644a1c-ef2f-44cb-8cc7-7acd8834a506) successfully added.
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:18 - sshInstance.py - [line:197] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:43:24 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:27 - test_network_sriov_stress.py - [line:80] - root - INFO - try to get ipv6 for ens787f2
2022-05-02 04:43:27 - test_network_sriov_stress.py - [line:82] - root - INFO - getting ipv6 in redhat.
2022-05-02 04:43:27 - sshInstance.py - [line:188] - root - INFO - starting to delete network of ens787f2:
2022-05-02 04:43:33 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon May  2 04:50:47 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# nmcli connection delete ens787f2
Connection 'ens787f2' (e48c4b8e-5bb4-4c17-a60d-6865e19ee0f4) successfully deleted.
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:43:36 - sshInstance.py - [line:190] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:43:42 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:43:45 - sshInstance.py - [line:194] - root - INFO - starting to add network of ens787f2:
2022-05-02 04:43:51 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens7877f2 ifname ens787f2
Connection 'ens787f2' (ab43fe6d-f762-4de7-9573-9162418af3d0) successfully added.
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:43:54 - sshInstance.py - [line:197] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:44:00 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:44:03 - test_network_sriov_stress.py - [line:90] - root - INFO - trying to get ipv6 addr for pf1
2022-05-02 04:44:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-05-02 04:44:06 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::31bf:227f:3884:2119  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 12  bytes 3519 (3.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 44  bytes 7542 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-05-02 04:44:14 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-05-02 04:44:14 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c9f2:229d:c7cd:d67  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 11271842887  bytes 17065482959175 (15.5 TiB)
        RX errors 1  dropped 17  overruns 0  frame 1
        TX packets 358577745  bytes 23675955241 (22.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-05-02 04:44:22 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-05-02 04:44:23 - sshInstance.py - [line:54] - root - INFO - 0000:4b:00.2

2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:156] - root - INFO - pf_id was found: 0000:4b:00.2

2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:754] - root - INFO - format_pf_id is 0000\:4b\:00.2

2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:757] - root - INFO - pf_id_key: 4b
2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:761] - root - INFO - Start assgin sut1 192.168.10.10 ip
2022-05-02 04:44:34 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 192.168.10.10
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:44:37 - test_network_sriov_stress.py - [line:365] - root - INFO - Successfully assigned ip to ethernet: ens785f2
2022-05-02 04:44:37 - test_network_sriov_stress.py - [line:763] - root - INFO - Start assgin sut2 192.168.10.11 ip
2022-05-02 04:44:43 - sshInstance.py - [line:99] - root - INFO - ifconfig ens787f2 192.168.10.11
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:44:46 - test_network_sriov_stress.py - [line:365] - root - INFO - Successfully assigned ip to ethernet: ens787f2
2022-05-02 04:44:46 - test_network_sriov_stress.py - [line:162] - root - INFO - virtulize sut1 pf to 4 vfs
2022-05-02 04:44:49 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-05-02 04:44:49 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:44:54 - test_network_sriov_stress.py - [line:171] - root - INFO - Successfully Virtualized PF to VFs.
2022-05-02 04:44:57 - sshInstance.py - [line:50] - root - INFO - lspci | grep "Virtual" |grep 4b | awk '{print $1;}'list
2022-05-02 04:44:57 - sshInstance.py - [line:54] - root - INFO - 4b:11.0
4b:11.1
4b:11.2
4b:11.3

2022-05-02 04:45:02 - test_network_sriov_stress.py - [line:185] - root - INFO - Succssfully Gotten vf_id list:

2022-05-02 04:45:05 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-05-02 04:45:05 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:45:10 - test_network_sriov_stress.py - [line:205] - root - INFO - start to bind drive in sut1
2022-05-02 04:45:13 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.0
2022-05-02 04:45:14 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:45:19 - test_network_sriov_stress.py - [line:219] - root - INFO - Successfuly bound VF to vfio-pci
2022-05-02 04:45:22 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.1
2022-05-02 04:45:23 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:45:28 - test_network_sriov_stress.py - [line:219] - root - INFO - Successfuly bound VF to vfio-pci
2022-05-02 04:45:28 - test_network_sriov_stress.py - [line:782] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-05-02 04:45:31 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-05-02 04:45:31 - sshInstance.py - [line:54] - root - INFO - 0000:4b:11.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-05-02 04:45:36 - test_network_sriov_stress.py - [line:794] - root - INFO - Successfully get vf device id: 8086:1889
2022-05-02 04:45:36 - test_network_sriov_stress.py - [line:242] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-05-02 04:45:39 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-05-02 04:45:40 - sshInstance.py - [line:54] - root - INFO - yes

2022-05-02 04:45:45 - test_network_sriov_stress.py - [line:245] - root - INFO - Default network is active? yes

2022-05-02 04:45:45 - test_network_sriov_stress.py - [line:804] - root - INFO - start to create VMs....
2022-05-02 04:45:45 - test_network_sriov_stress.py - [line:275] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-05-02 04:45:49 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:45:52 - test_network_sriov_stress.py - [line:278] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-05-02 04:45:56 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-05-02 04:45:59 - sshInstance.py - [line:75] - root - INFO - Domain creation completed.
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:46:02 - test_network_sriov_stress.py - [line:292] - root - INFO - Successfully created a VM: VMtest1
2022-05-02 04:46:02 - test_network_sriov_stress.py - [line:275] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole

2022-05-02 04:46:06 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5901 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:46:09 - test_network_sriov_stress.py - [line:278] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole

2022-05-02 04:46:13 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-05-02 04:46:16 - sshInstance.py - [line:75] - root - INFO - Domain creation completed.
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:46:19 - test_network_sriov_stress.py - [line:292] - root - INFO - Successfully created a VM: VMtest2
2022-05-02 04:46:22 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-05-02 04:46:22 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:46:27 - test_network_sriov_stress.py - [line:313] - root - ERROR - not found IP of VMtest1
2022-05-02 04:47:30 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-05-02 04:47:30 - sshInstance.py - [line:54] - root - INFO - 192.168.122.208/24

2022-05-02 04:47:35 - test_network_sriov_stress.py - [line:308] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-05-02 04:47:38 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-05-02 04:47:38 - sshInstance.py - [line:54] - root - INFO - 192.168.122.168/24

2022-05-02 04:47:43 - test_network_sriov_stress.py - [line:308] - root - INFO - Successfully got VMtest2 IP: 192.168.122.168/24

2022-05-02 04:47:43 - test_network_sriov_stress.py - [line:823] - root - INFO - Start ssh vm1 and conf VM
2022-05-02 04:47:49 - sshInstance.py - [line:99] - root - INFO - ssh-key -R 192.168.122.208
bash: ssh-key: command not found...

2022-05-02 04:47:56 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.208
F2022-05-02 04:48:30 - test_network_sriov_stress.py - [line:102] - root - INFO - removing VMs: VMtest1, VMtest2
2022-05-02 04:48:33 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest2
2022-05-02 04:48:34 - sshInstance.py - [line:54] - root - INFO - Domain VMtest2 destroyed


2022-05-02 04:48:39 - test_network_sriov_stress.py - [line:340] - root - INFO - Successfully shut down the VM: VMtest2
2022-05-02 04:48:42 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest2
2022-05-02 04:48:42 - sshInstance.py - [line:54] - root - INFO - Domain VMtest2 has been undefined


2022-05-02 04:48:47 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully removed the VM: VMtest2
2022-05-02 04:48:50 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest1
2022-05-02 04:48:52 - sshInstance.py - [line:54] - root - INFO - Domain VMtest1 destroyed


2022-05-02 04:48:57 - test_network_sriov_stress.py - [line:340] - root - INFO - Successfully shut down the VM: VMtest1
2022-05-02 04:49:00 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest1
2022-05-02 04:49:00 - sshInstance.py - [line:54] - root - INFO - Domain VMtest1 has been undefined


2022-05-02 04:49:05 - test_network_sriov_stress.py - [line:350] - root - INFO - Successfully removed the VM: VMtest1
2022-05-02 04:49:08 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-05-02 04:49:10 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:49:15 - test_network_sriov_stress.py - [line:107] - root - INFO - try to reset network for ens785f2
2022-05-02 04:49:15 - test_network_sriov_stress.py - [line:109] - root - INFO - try to reset network for redhat...
2022-05-02 04:49:15 - sshInstance.py - [line:188] - root - INFO - starting to delete network of ens785f2:
2022-05-02 04:49:21 - sshInstance.py - [line:99] - root - INFO - nmcli connection delete ens785f2

2022-05-02 04:49:24 - sshInstance.py - [line:190] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:49:30 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager

2022-05-02 04:49:33 - sshInstance.py - [line:194] - root - INFO - starting to add network of ens785f2:
2022-05-02 04:49:39 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifname ens785f2

2022-05-02 04:49:42 - sshInstance.py - [line:197] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:49:48 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager

2022-05-02 04:49:51 - test_network_sriov_stress.py - [line:116] - root - INFO - try to reset network for ens787f2
2022-05-02 04:49:51 - test_network_sriov_stress.py - [line:118] - root - INFO - try to reset network for redhat
2022-05-02 04:49:51 - sshInstance.py - [line:188] - root - INFO - starting to delete network of ens787f2:
2022-05-02 04:49:57 - sshInstance.py - [line:99] - root - INFO - nmcli connection delete ens787f2
Connection 'ens787f2' (ab43fe6d-f762-4de7-9573-9162418af3d0) successfully deleted.
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:50:00 - sshInstance.py - [line:190] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:50:06 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:50:09 - sshInstance.py - [line:194] - root - INFO - starting to add network of ens787f2:
2022-05-02 04:50:15 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens7877f2 ifname ens787f2
Connection 'ens787f2' (e88d17d2-e209-4934-9af4-6223066c2c82) successfully added.
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:50:18 - sshInstance.py - [line:197] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:50:24 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:50:30 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-05-02 04:50:30 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:50:35 - test_network_sriov_stress.py - [line:126] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-05-02 04:50:35 - test_network_sriov_stress.py - [line:128] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-05-02/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img]_04_41_33
2022-05-02 04:50:38 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-05-02 04:50:38 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:50:43 - test_network_sriov_stress.py - [line:130] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-05-02 04:50:46 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/*.txt
2022-05-02 04:50:46 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:50:51 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-05-02 04:50:51 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img] case ============================
                  [100%]

=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f55daf5ee48>
vm1_image = 'uvm1.img', vm2_image = 'uvm2.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicStress
    @pytest.mark.nicSriovStress
    @pytest.mark.nicSriov2hours
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest(self, vm1_image, vm2_image):
        pf_id, status = self.get_pf_id(self.client, self.pf_name)
        # transfer pf_id to 0000\:00\:00.0 format
    
        if not pf_id:
            assert 200 == status
        else:
            pf_id_format = pf_id.replace(":", "\\:", 2)
            logging.info("format_pf_id is {}".format(pf_id_format))
            # get the number key of pf_id
            pf_id_key = pf_id.split(":")[1]
            logging.info("pf_id_key: {}".format(pf_id_key))
            # assign IP to PF in SUT and sut2
            pf_ip = "192.168.10.10"
            sut2_ip = "192.168.10.11"
            logging.info("Start assgin sut1 {} ip".format(pf_ip))
            assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
            logging.info("Start assgin sut2 {} ip".format(sut2_ip))
            assert 200 == self.assign_ip_ehternet(self.session2, sut2_ip, self.sut2_info["pf1"])
            # virtulize the pf to vfs
            assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
            # get vf ids
            vf_id_list, status = self.get_vf_ids(self.client, pf_id_key)
            vf_id_list = [i.strip() for i in vf_id_list]
    
            if status == 200:
                # modprobe vfio-pci
                assert 200 == self.modprobe("vfio-pci")
                # bind vf with vfio-pci
                host_dev_id_list, status = self.bind_vf_to_vfio_pci(self.client, vf_id_list)
                assert 200 == status
            else:
                assert 200 == status
    
            # get vF device id
            cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
            logging.info(cmd)
            vf_device_id = ""
            vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
            vf_device_id_rs = vf_device_id_rs.strip()
            if vf_device_id_rs:
                st = False
                vf_device_id = None
                for one in vf_device_id_rs.split(" "):
                    one = " " + one + " "
                    if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                        vf_device_id = one.replace("[", "").replace("]", "").strip()
                if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                logging.info("Successfully get vf device id: {}".format(vf_device_id))
                assert 200 == 200
            else:
                logging.error("Fail to get vf device id.")
                assert 200 == 400
            # set network
            status = self.default_network_isActive(self.client, self.defult_network)
            if status == "no":
                assert 200 == self.start_default_network(self.defult_network)
    
            logging.info("start to create VMs....")
            if self.sut_info["os"] == "UBUNTU":
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "ubuntu20.04", "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "ubuntu20.04", "5901")
            else:
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "rhel8.2", "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "rhel8.2", "5901")
    
            # start VMs
            # assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "5900")
            # assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "5901")
            # get VM ssh IP
            vm1_ip, status1 = self.get_vm_ip(self.vm1_name)
            vm2_ip, status2 = self.get_vm_ip(self.vm2_name)
    
            # ssh VM1 to set VF
            # ssh VM1 to set VF
            vm1_vf_ip = "192.168.10.12"
            vm2_vf_ip = "192.168.10.13"
            logging.info("Start ssh vm1 and conf VM")
>           assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                              vm1_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
E           AssertionError: ssh vm failed,the reason may be is password is error,vm ip isimpassability
E           assert 200 == 400
E            +  where 400 = <bound method Test_Network_SRIOV_Stress.on_session_ssh of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f55daf5ee48>>(<libs.commons.sshInstance.sshInstance object at 0x7f55e005c358>, <paramiko.Channel 0 (open) window=2095929 -> <paramiko.Transport at 0xe005c780 (cipher aes128-ctr, 128 bits) (active; 2 open channel(s))>>, '192.168.122.208')
E            +    where <bound method Test_Network_SRIOV_Stress.on_session_ssh of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f55daf5ee48>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f55daf5ee48>.on_session_ssh
E            +    and   <libs.commons.sshInstance.sshInstance object at 0x7f55e005c358> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f55daf5ee48>.ssh_sut
E            +    and   <paramiko.Channel 0 (open) window=2095929 -> <paramiko.Transport at 0xe005c780 (cipher aes128-ctr, 128 bits) (active; 2 open channel(s))>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f55daf5ee48>.session

npxtester/Tests/testNics/test_network_sriov_stress.py:824: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-05-02 04:41:33 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-05-02/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img]_04_41_33/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img].log, case_logdir: /root/testconfig/testlogs/2022-05-02/test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img]_04_41_33
2022-05-02 04:41:33 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-05-02 04:41:33 - test_network_sriov_stress.py - [line:32] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-05-02 04:41:33 - test_network_sriov_stress.py - [line:50] - root - INFO - ssh to the sut1
2022-05-02 04:41:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-05-02 04:41:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-05-02 04:41:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-05-02 04:41:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-05-02 04:41:34 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-05-02 04:41:34 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-05-02 04:41:34 - test_network_sriov_stress.py - [line:64] - root - INFO - clean up iperf and taskset process...
2022-05-02 04:41:37 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-05-02 04:41:37 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:41:45 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-05-02 04:41:45 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:41:53 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-05-02 04:41:53 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:01 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-05-02 04:42:01 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:06 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 3] Opened sftp connection (server version 3)
2022-05-02 04:42:06 - sshInstance.py - [line:201] - root - INFO - start to rmmod irdma....
2022-05-02 04:42:09 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-05-02 04:42:09 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module irdma is not currently loaded

2022-05-02 04:42:14 - sshInstance.py - [line:204] - root - INFO - finished rmmod irdma....
2022-05-02 04:42:14 - sshInstance.py - [line:205] - root - INFO - start to rmmod ice....
2022-05-02 04:42:17 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-05-02 04:42:26 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:31 - sshInstance.py - [line:208] - root - INFO - finished rmmod ice....
2022-05-02 04:42:31 - sshInstance.py - [line:210] - root - INFO - start to modprobe ice....
2022-05-02 04:42:34 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-05-02 04:42:38 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:42:43 - sshInstance.py - [line:212] - root - INFO - finished modprobe ice....
2022-05-02 04:42:46 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens785f2
2022-05-02 04:42:46 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 3.10 0x80009be5 1.3086.0
expansion-rom-version: 
bus-info: 0000:4b:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-05-02 04:42:51 - test_network_sriov_stress.py - [line:71] - root - INFO - try to get ipv6 for ens785f2
2022-05-02 04:42:51 - test_network_sriov_stress.py - [line:73] - root - INFO - try to get ipv6 of pf for redhat...
2022-05-02 04:42:51 - sshInstance.py - [line:188] - root - INFO - starting to delete network of ens785f2:
2022-05-02 04:42:57 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon May  2 04:52:38 2022 from 10.112.97.60
[root@npx-cyp7-rh82 ~]# nmcli connection delete ens785f2
Connection 'ens785f2' (03aaab02-a667-40d0-8493-e3f2f4b8cc7f) successfully deleted.
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:00 - sshInstance.py - [line:190] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:43:06 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:09 - sshInstance.py - [line:194] - root - INFO - starting to add network of ens785f2:
2022-05-02 04:43:15 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens785f2 ifnaame ens785f2
Connection 'ens785f2' (24644a1c-ef2f-44cb-8cc7-7acd8834a506) successfully added.
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:18 - sshInstance.py - [line:197] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:43:24 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cyp7-rh82 ~]# 
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:43:27 - test_network_sriov_stress.py - [line:80] - root - INFO - try to get ipv6 for ens787f2
2022-05-02 04:43:27 - test_network_sriov_stress.py - [line:82] - root - INFO - getting ipv6 in redhat.
2022-05-02 04:43:27 - sshInstance.py - [line:188] - root - INFO - starting to delete network of ens787f2:
2022-05-02 04:43:33 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon May  2 04:50:47 2022 from 10.112.97.60
[root@npx-cypsilver1-rel84 ~]# nmcli connection delete ens787f2
Connection 'ens787f2' (e48c4b8e-5bb4-4c17-a60d-6865e19ee0f4) successfully deleted.
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:43:36 - sshInstance.py - [line:190] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:43:42 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:43:45 - sshInstance.py - [line:194] - root - INFO - starting to add network of ens787f2:
2022-05-02 04:43:51 - sshInstance.py - [line:99] - root - INFO - nmcli connection add type ethernet con-name ens7877f2 ifname ens787f2
Connection 'ens787f2' (ab43fe6d-f762-4de7-9573-9162418af3d0) successfully added.
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:43:54 - sshInstance.py - [line:197] - root - INFO - restart networkManager to make setting valid
2022-05-02 04:44:00 - sshInstance.py - [line:99] - root - INFO - systemctl restart NetworkManager
[root@npx-cypsilver1-rel84 ~]# 
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:44:03 - test_network_sriov_stress.py - [line:90] - root - INFO - trying to get ipv6 addr for pf1
2022-05-02 04:44:06 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f2
2022-05-02 04:44:06 - sshInstance.py - [line:54] - root - INFO - ens785f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::31bf:227f:3884:2119  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:72:cc:ca  txqueuelen 1000  (Ethernet)
        RX packets 12  bytes 3519 (3.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 44  bytes 7542 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-05-02 04:44:14 - sshInstance.py - [line:50] - root - INFO - ifconfig ens787f2
2022-05-02 04:44:14 - sshInstance.py - [line:54] - root - INFO - ens787f2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c9f2:229d:c7cd:d67  prefixlen 64  scopeid 0x20<link>
        ether 40:a6:b7:82:0e:b6  txqueuelen 1000  (Ethernet)
        RX packets 11271842887  bytes 17065482959175 (15.5 TiB)
        RX errors 1  dropped 17  overruns 0  frame 1
        TX packets 358577745  bytes 23675955241 (22.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-05-02 04:44:22 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-05-02 04:44:23 - sshInstance.py - [line:54] - root - INFO - 0000:4b:00.2

2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:156] - root - INFO - pf_id was found: 0000:4b:00.2

2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:754] - root - INFO - format_pf_id is 0000\:4b\:00.2

2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:757] - root - INFO - pf_id_key: 4b
2022-05-02 04:44:28 - test_network_sriov_stress.py - [line:761] - root - INFO - Start assgin sut1 192.168.10.10 ip
2022-05-02 04:44:34 - sshInstance.py - [line:99] - root - INFO - ifconfig ens785f2 192.168.10.10
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:44:37 - test_network_sriov_stress.py - [line:365] - root - INFO - Successfully assigned ip to ethernet: ens785f2
2022-05-02 04:44:37 - test_network_sriov_stress.py - [line:763] - root - INFO - Start assgin sut2 192.168.10.11 ip
2022-05-02 04:44:43 - sshInstance.py - [line:99] - root - INFO - ifconfig ens787f2 192.168.10.11
[root@npx-cypsilver1-rel84 ~]# 
2022-05-02 04:44:46 - test_network_sriov_stress.py - [line:365] - root - INFO - Successfully assigned ip to ethernet: ens787f2
2022-05-02 04:44:46 - test_network_sriov_stress.py - [line:162] - root - INFO - virtulize sut1 pf to 4 vfs
2022-05-02 04:44:49 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
2022-05-02 04:44:49 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:44:54 - test_network_sriov_stress.py - [line:171] - root - INFO - Successfully Virtualized PF to VFs.
2022-05-02 04:44:57 - sshInstance.py - [line:50] - root - INFO - lspci | grep "Virtual" |grep 4b | awk '{print $1;}'list
2022-05-02 04:44:57 - sshInstance.py - [line:54] - root - INFO - 4b:11.0
4b:11.1
4b:11.2
4b:11.3

2022-05-02 04:45:02 - test_network_sriov_stress.py - [line:185] - root - INFO - Succssfully Gotten vf_id list:

2022-05-02 04:45:05 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-05-02 04:45:05 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:45:10 - test_network_sriov_stress.py - [line:205] - root - INFO - start to bind drive in sut1
2022-05-02 04:45:13 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.0
2022-05-02 04:45:14 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:45:19 - test_network_sriov_stress.py - [line:219] - root - INFO - Successfuly bound VF to vfio-pci
2022-05-02 04:45:22 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.1
2022-05-02 04:45:23 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:45:28 - test_network_sriov_stress.py - [line:219] - root - INFO - Successfuly bound VF to vfio-pci
2022-05-02 04:45:28 - test_network_sriov_stress.py - [line:782] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-05-02 04:45:31 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 4b:11.1
2022-05-02 04:45:31 - sshInstance.py - [line:54] - root - INFO - 0000:4b:11.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-05-02 04:45:36 - test_network_sriov_stress.py - [line:794] - root - INFO - Successfully get vf device id: 8086:1889
2022-05-02 04:45:36 - test_network_sriov_stress.py - [line:242] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-05-02 04:45:39 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-05-02 04:45:40 - sshInstance.py - [line:54] - root - INFO - yes

2022-05-02 04:45:45 - test_network_sriov_stress.py - [line:245] - root - INFO - Default network is active? yes

2022-05-02 04:45:45 - test_network_sriov_stress.py - [line:804] - root - INFO - start to create VMs....
2022-05-02 04:45:45 - test_network_sriov_stress.py - [line:275] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-05-02 04:45:49 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:45:52 - test_network_sriov_stress.py - [line:278] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-05-02 04:45:56 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-05-02 04:45:59 - sshInstance.py - [line:75] - root - INFO - Domain creation completed.
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:46:02 - test_network_sriov_stress.py - [line:292] - root - INFO - Successfully created a VM: VMtest1
2022-05-02 04:46:02 - test_network_sriov_stress.py - [line:275] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole

2022-05-02 04:46:06 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5901 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:46:09 - test_network_sriov_stress.py - [line:278] - root - INFO - cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole

2022-05-02 04:46:13 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-05-02 04:46:16 - sshInstance.py - [line:75] - root - INFO - Domain creation completed.
[root@npx-cyp7-rh82 ~]# 
2022-05-02 04:46:19 - test_network_sriov_stress.py - [line:292] - root - INFO - Successfully created a VM: VMtest2
2022-05-02 04:46:22 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-05-02 04:46:22 - sshInstance.py - [line:54] - root - INFO - 
2022-05-02 04:46:27 - test_network_sriov_stress.py - [line:313] - root - ERROR - not found IP of VMtest1
2022-05-02 04:47:30 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-05-02 04:47:30 - sshInstance.py - [line:54] - root - INFO - 192.168.122.208/24

2022-05-02 04:47:35 - test_network_sriov_stress.py - [line:308] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-05-02 04:47:38 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-05-02 04:47:38 - sshInstance.py - [line:54] - root - INFO - 192.168.122.168/24

2022-05-02 04:47:43 - test_network_sriov_stress.py - [line:308] - root - INFO - Successfully got VMtest2 IP: 192.168.122.168/24

2022-05-02 04:47:43 - test_network_sriov_stress.py - [line:823] - root - INFO - Start ssh vm1 and conf VM
2022-05-02 04:47:49 - sshInstance.py - [line:99] - root - INFO - ssh-key -R 192.168.122.208
bash: ssh-key: command not found...

2022-05-02 04:47:56 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.208
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
INFO     root:sshInstance.py:54 0000:4b:00.2

INFO     root:test_network_sriov_stress.py:156 pf_id was found: 0000:4b:00.2

INFO     root:test_network_sriov_stress.py:754 format_pf_id is 0000\:4b\:00.2

INFO     root:test_network_sriov_stress.py:757 pf_id_key: 4b
INFO     root:test_network_sriov_stress.py:761 Start assgin sut1 192.168.10.10 ip
INFO     root:sshInstance.py:99 ifconfig ens785f2 192.168.10.10
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:365 Successfully assigned ip to ethernet: ens785f2
INFO     root:test_network_sriov_stress.py:763 Start assgin sut2 192.168.10.11 ip
INFO     root:sshInstance.py:99 ifconfig ens787f2 192.168.10.11
[root@npx-cypsilver1-rel84 ~]# 
INFO     root:test_network_sriov_stress.py:365 Successfully assigned ip to ethernet: ens787f2
INFO     root:test_network_sriov_stress.py:162 virtulize sut1 pf to 4 vfs
INFO     root:sshInstance.py:50 echo 4 > /sys/class/net/ens785f2/device/sriov_numvfs
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:171 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:50 lspci | grep "Virtual" |grep 4b | awk '{print $1;}'list
INFO     root:sshInstance.py:54 4b:11.0
4b:11.1
4b:11.2
4b:11.3

INFO     root:test_network_sriov_stress.py:185 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:50 modprobe vfio-pci

INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:205 start to bind drive in sut1
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.0
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:219 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -b vfio-pci 4b:11.1
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:219 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:782 lspci -Dnn | grep 4b:11.1
INFO     root:sshInstance.py:50 lspci -Dnn | grep 4b:11.1
INFO     root:sshInstance.py:54 0000:4b:11.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:794 Successfully get vf device id: 8086:1889
INFO     root:test_network_sriov_stress.py:242 get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:54 yes

INFO     root:test_network_sriov_stress.py:245 Default network is active? yes

INFO     root:test_network_sriov_stress.py:804 start to create VMs....
INFO     root:test_network_sriov_stress.py:275 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5900 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:278 cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_0 --boot hd --disk path=/hhome/image/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:75 Domain creation completed.
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:292 Successfully created a VM: VMtest1
INFO     root:test_network_sriov_stress.py:275 try to create VM with the cmd1: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest2 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=00.0.0.0,port=5901 --noautoconsole
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: --osinfo rhel8.2
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:278 cmd1 is not working, try to create VM with the cmd2: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest2 --ram 4096 --cpu host --vcpuss=5 --network network=default --hostdev pci_0000_4b_11_1 --boot hd --disk path=/hhome/image/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901  --noautoconsole
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:75 Domain creation completed.
[root@npx-cyp7-rh82 ~]# 
INFO     root:test_network_sriov_stress.py:292 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:50 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:54 
ERROR    root:test_network_sriov_stress.py:313 not found IP of VMtest1
INFO     root:sshInstance.py:50 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:54 192.168.122.208/24

INFO     root:test_network_sriov_stress.py:308 Successfully got VMtest1 IP: 192.168.122.208/24

INFO     root:sshInstance.py:50 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:54 192.168.122.168/24

INFO     root:test_network_sriov_stress.py:308 Successfully got VMtest2 IP: 192.168.122.168/24

INFO     root:test_network_sriov_stress.py:823 Start ssh vm1 and conf VM
INFO     root:sshInstance.py:99 ssh-key -R 192.168.122.208
bash: ssh-key: command not found...

INFO     root:sshInstance.py:75 ping -c 5 192.168.122.208
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:116
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_iperf_client_4hour.py:116: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:169
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_iperf_client_4hour.py:169: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:102
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_mtu.py:102: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:141
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_mtu.py:141: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:617
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:617: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:744
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:744: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:984
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:984: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_network_sriov_stress.py:1123
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:1123: PytestUnknownMarkWarning: Unknown pytest.mark.nicIperfTcpSUTGuestStress - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicIperfTcpSUTGuestStress

npxtester/Tests/testNics/test_network_sriov_stress.py:1124
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_network_sriov_stress.py:1124: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:119
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:119: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:156
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:156: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:157
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:157: PytestUnknownMarkWarning: Unknown pytest.mark.connect - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.connect

npxtester/Tests/testNics/test_nics.py:189
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:189: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:190
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:190: PytestUnknownMarkWarning: Unknown pytest.mark.static_ip - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.static_ip

npxtester/Tests/testNics/test_nics.py:221
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:221: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:222
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:222: PytestUnknownMarkWarning: Unknown pytest.mark.test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.test

npxtester/Tests/testNics/test_nics.py:308
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:308: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:334
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:334: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:377
  /root/.jenkins/workspace/cyp-test-nic-sriov-stress-2hours/npxtester/Tests/testNics/test_nics.py:377: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov2hours_case_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressTrafficBetweenPFVFAndTestClientFor2Hours_VM_Guest[uvm1.img-uvm2.img]
========== 1 failed, 19 deselected, 19 warnings in 574.60s (0:09:34) ===========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4AfI3SthhIf/wHKBxkZZVuznCBOLGICd+mTaK5J1XhvpAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMHmfoKzrT+3fkMfZ274AAAA=[0m[Pipeline] }
[8mha:////4O1G14z5oV6C9jl1Q5yIn+pZFQRmsElhyj6JiXyHA8ixAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiBB2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7BpKm1V++AAAA[0m[Pipeline] // stage
[8mha:////4KtBCOpIKS64HlRGbxVDHBnhT4546C6ceKSEgLxKWO63AAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUauVY2WZoPEGEGAOZXUwWofJEXs07yMiMlb/67zXv9cYyRRw5OtVYaj2lyqsu9G56auDYXgMPquGLqpgSB6tKO5Rc29OMJYvFvCzHQmNlqQqcPDnBWjfmYYpgyBVniZM7aOS+vuOJTE9lMVG+MEZsbn2dmH6dvwGMXSfIt3tBtvsA/gVtV70AAAA=[0m[Pipeline] }
[8mha:////4PVa+eOfGCB5ryE2GyokIfyPZOVvh3emQVgJTOuHuCGAAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IMJC7GybVh8Qsq1Fpo3sP2IUx+kb/mP0gkcfJO95zlvN5Yp4gjR6daS52nVHvVh8HNT40cu2vgUbV8UTVT4mBVZceKG3tasGKxWJblWGlsLNWBkycn2OrWPEwRDLniLHF2B43cN3c8kem5LCbKF6aI3W1oEtOv8zeAqe8FebkXZOUHjeqpjr0AAAA=[0m[Pipeline] // node
[8mha:////4OyM7hMK6utvbTfbnNkjhtaoCHWCq3+ZbQ+BNe9AvJHZAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRoKBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Lu9INt+AKvzzsS9AAAA[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
