Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","pf1":"ens2f0","os":"RHEL"},"pkg_generator":{"host":"10.112.97.60","pf1":"ens2f1"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 16 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-14 17:27:01 - NicTestFixture.py - [line:37] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-14 17:27:01 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-14 17:27:01 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 17:27:02 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 17:27:02 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-14 17:27:02 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-14 17:27:02 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 17:27:02 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 17:27:02 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-14 17:27:05 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-14 17:27:05 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-14 17:27:13 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-14 17:27:17 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:27:25 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-14 17:27:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:27:38 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-14 17:27:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:27:46 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-14 17:27:46 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-14 17:27:54 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-14 17:27:54 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 3068 (2.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 17:28:02 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-14 17:28:02 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 6097575998  bytes 9229273151795 (8.3 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 211278956  bytes 16112344002 (15.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 17:28:07 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-14 17:28:10 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 17:28:11 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 17:28:16 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 17:28:16 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 17:28:16 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 17:28:22 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 14 17:34:47 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 17:28:25 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:28:31 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 14 17:26:06 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-14 17:28:34 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:28:37 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:28:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:28:42 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 17:28:45 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 17:28:45 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 17:28:50 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 17:28:53 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 17:28:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:29:01 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 17:29:02 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:29:07 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:29:10 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 17:29:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:29:16 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:29:16 - test_network_sriov_stress.py - [line:422] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:29:19 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:29:19 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 17:29:24 - test_network_sriov_stress.py - [line:433] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 17:29:27 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 17:29:27 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 17:29:32 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 17:29:36 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:59945): [1;33mWARNING[0m **: [34m17:38:01.503[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:29:38 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:29:41 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 17:29:45 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:60001): [1;33mWARNING[0m **: [34m17:38:10.660[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:29:47 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:29:50 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 17:29:53 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:29:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:29:59 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 17:31:02 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:31:02 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 17:31:07 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-03-14 17:31:10 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:31:10 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 17:31:15 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.72/24

2022-03-14 17:31:15 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 17:31:15 - test_network_sriov_stress.py - [line:451] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 17:31:19 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.362 ms
2022-03-14 17:31:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.232 ms
2022-03-14 17:31:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.435 ms
2022-03-14 17:31:22 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.410 ms
2022-03-14 17:31:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.546 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4108ms
rtt min/avg/max/mdev = 0.232/0.397/0.546/0.102 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:31:32 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 17:31:41 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:40:02 AM EDT
  System load:  0.08               Processes:             140
  Usage of /:   36.8% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:22:52 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:31:50 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 17:31:56 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 17:32:02 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 17:32:07 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 17:32:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 17:32:16 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 17:32:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 17:32:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 17:32:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 17:32:50 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 17:32:59 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 17:33:08 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:33:15 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.343 ms
2022-03-14 17:33:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.287 ms
2022-03-14 17:33:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.371 ms
2022-03-14 17:33:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.336 ms
2022-03-14 17:33:19 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.173 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4136ms
rtt min/avg/max/mdev = 0.173/0.302/0.371/0.069 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:33:28 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 17:33:37 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:41:58 AM EDT
  System load:  0.04               Processes:             143
  Usage of /:   36.8% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:27:03 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:33:46 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 17:33:52 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 17:33:58 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 17:34:03 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 17:34:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 17:34:12 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 17:34:18 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 17:34:28 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 17:34:37 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 17:34:46 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 17:34:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1038 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 17:35:04 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:35:07 - test_network_sriov_stress.py - [line:469] - root - INFO - Ping two vms IP from SUT:
2022-03-14 17:35:11 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.391 ms
2022-03-14 17:35:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.272 ms
2022-03-14 17:35:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.139 ms
2022-03-14 17:35:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.154 ms
2022-03-14 17:35:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.199 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4100ms
rtt min/avg/max/mdev = 0.139/0.231/0.391/0.092 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:35:22 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.614 ms
2022-03-14 17:35:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.274 ms
2022-03-14 17:35:24 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.162 ms
2022-03-14 17:35:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.176 ms
2022-03-14 17:35:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.183 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4095ms
rtt min/avg/max/mdev = 0.162/0.281/0.614/0.172 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:35:29 - test_network_sriov_stress.py - [line:477] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 17:35:33 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.264 ms
2022-03-14 17:35:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.246 ms
2022-03-14 17:35:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.430 ms
2022-03-14 17:35:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.416 ms
2022-03-14 17:35:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.326 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.246/0.336/0.430/0.077 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:35:46 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 17:35:55 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:44:16 AM EDT
  System load:  0.0                Processes:             129
  Usage of /:   36.8% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:40:03 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:36:02 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.296 ms
2022-03-14 17:36:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.264 ms
2022-03-14 17:36:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.291 ms
2022-03-14 17:36:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.241 ms
2022-03-14 17:36:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.181 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.181/0.254/0.296/0.041 ms
root@localhost:~# 
2022-03-14 17:36:46 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:36:49 - test_network_sriov_stress.py - [line:485] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 17:36:53 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 17:36:56 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 17:36:59 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4125ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 17:37:05 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:37:07 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:37:12 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 17:37:15 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 17:37:16 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 17:37:21 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 17:37:24 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 17:37:24 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 17:37:29 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 17:37:32 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 17:37:32 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 17:37:37 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 17:37:40 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 17:37:40 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 17:37:45 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 17:37:45 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-03-14 17:37:48 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 17:37:49 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 17:37:54 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 17:37:54 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 17:37:54 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 17:38:00 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 17:38:03 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:38:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-14 17:38:12 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:38:15 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:38:15 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:38:20 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 17:38:23 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 17:38:23 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 17:38:28 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 17:38:31 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 17:38:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:38:39 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 17:38:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:38:45 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:38:48 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 17:38:49 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:38:54 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:38:54 - test_network_sriov_stress.py - [line:422] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:38:57 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:38:57 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 17:39:02 - test_network_sriov_stress.py - [line:433] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 17:39:05 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 17:39:05 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 17:39:10 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 17:39:14 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 17:39:15 - sshInstance.py - [line:71] - root - INFO - 
** (process:60992): [1;33mWARNING[0m **: [34m17:47:39.226[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:39:18 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:60992): [1;33mWARNING[0m **: [34m17:47:39.226[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:39:18 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 17:39:22 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 17:39:23 - sshInstance.py - [line:71] - root - INFO - 
** (process:61000): [1;33mWARNING[0m **: [34m17:47:47.243[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:39:25 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:39:28 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 17:39:32 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:61053): [1;33mWARNING[0m **: [34m17:47:57.228[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-14 17:39:33 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:39:36 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:61053): [1;33mWARNING[0m **: [34m17:47:57.228[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:39:36 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 17:39:40 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:61064): [1;33mWARNING[0m **: [34m17:48:05.203[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:39:42 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:39:45 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 17:39:48 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:39:48 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:39:53 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 17:40:56 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:40:56 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 17:41:01 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-03-14 17:41:04 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:41:04 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 17:41:09 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.72/24

2022-03-14 17:41:09 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 17:41:09 - test_network_sriov_stress.py - [line:451] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 17:41:13 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.270 ms
2022-03-14 17:41:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.360 ms
2022-03-14 17:41:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.466 ms
2022-03-14 17:41:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.461 ms
2022-03-14 17:41:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.458 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.270/0.403/0.466/0.077 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:41:26 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 17:41:35 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:49:57 AM EDT
  System load:  0.01               Processes:             136
  Usage of /:   36.8% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:44:17 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:41:44 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 17:41:50 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 17:41:56 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 17:42:01 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 17:42:07 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 17:42:10 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 17:42:16 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 17:42:26 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 17:42:35 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 17:42:44 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 17:42:53 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 17:43:02 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:43:09 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.295 ms
2022-03-14 17:43:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.285 ms
2022-03-14 17:43:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.283 ms
2022-03-14 17:43:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.280 ms
2022-03-14 17:43:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.470 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.280/0.322/0.470/0.076 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:43:22 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 17:43:31 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:51:53 AM EDT
  System load:  0.09               Processes:             140
  Usage of /:   36.8% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:41:58 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:43:40 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 17:43:46 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 17:43:53 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 17:43:58 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 17:44:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 17:44:07 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 17:44:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 17:44:23 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 17:44:32 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 17:44:41 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 17:44:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 17:44:59 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:45:02 - test_network_sriov_stress.py - [line:469] - root - INFO - Ping two vms IP from SUT:
2022-03-14 17:45:06 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.841 ms
2022-03-14 17:45:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.284 ms
2022-03-14 17:45:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.202 ms
2022-03-14 17:45:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.273 ms
2022-03-14 17:45:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.246 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4131ms
rtt min/avg/max/mdev = 0.202/0.369/0.841/0.237 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:45:17 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.466 ms
2022-03-14 17:45:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.138 ms
2022-03-14 17:45:19 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.157 ms
2022-03-14 17:45:20 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.221 ms
2022-03-14 17:45:21 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.077 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4126ms
rtt min/avg/max/mdev = 0.077/0.211/0.466/0.136 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:45:24 - test_network_sriov_stress.py - [line:477] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 17:45:28 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.322 ms
2022-03-14 17:45:29 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.467 ms
2022-03-14 17:45:30 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.430 ms
2022-03-14 17:45:31 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.323 ms
2022-03-14 17:45:32 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.384 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4120ms
rtt min/avg/max/mdev = 0.322/0.385/0.467/0.058 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:45:41 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 17:45:50 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:54:11 AM EDT
  System load:  0.0                Processes:             128
  Usage of /:   36.8% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:49:57 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:45:57 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.190 ms
2022-03-14 17:45:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.067 ms
2022-03-14 17:45:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.206 ms
2022-03-14 17:46:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.077 ms
2022-03-14 17:46:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.258 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4098ms
rtt min/avg/max/mdev = 0.067/0.159/0.258/0.075 ms
root@localhost:~# 
2022-03-14 17:46:41 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:46:44 - test_network_sriov_stress.py - [line:485] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 17:46:48 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 17:46:51 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 17:46:54 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4093ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 17:47:00 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:47:02 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:47:07 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 17:47:10 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 17:47:10 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 17:47:15 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 17:47:18 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 17:47:18 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 17:47:23 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 17:47:26 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 17:47:26 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 17:47:31 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 17:47:34 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 17:47:35 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 17:47:40 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 17:47:40 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2022-03-14 17:47:43 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 17:47:43 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 17:47:48 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 17:47:48 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 17:47:48 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 17:47:54 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 17:47:57 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:48:03 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-14 17:48:06 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:48:09 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:48:09 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:48:14 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 17:48:17 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 17:48:18 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 17:48:23 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 17:48:26 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 17:48:26 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:48:34 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 17:48:34 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:48:39 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:48:42 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 17:48:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:48:48 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:48:48 - test_network_sriov_stress.py - [line:422] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:48:51 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:48:51 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 17:48:56 - test_network_sriov_stress.py - [line:433] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 17:48:59 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 17:48:59 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 17:49:04 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 17:49:08 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:62471): [1;33mWARNING[0m **: [34m17:57:33.437[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:49:11 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:62471): [1;33mWARNING[0m **: [34m17:57:33.437[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:49:11 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 17:49:15 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:62479): [1;33mWARNING[0m **: [34m17:57:40.428[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:49:18 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:49:21 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 17:49:25 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:62523): [1;33mWARNING[0m **: [34m17:57:50.590[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-14 17:49:26 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:49:29 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:62523): [1;33mWARNING[0m **: [34m17:57:50.590[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:49:29 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 17:49:33 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:62560): [1;33mWARNING[0m **: [34m17:57:58.345[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:49:36 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:49:39 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 17:49:42 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:49:42 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 17:49:47 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-03-14 17:49:50 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:49:51 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:49:56 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-14 17:50:59 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:50:59 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 17:51:04 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.72/24

2022-03-14 17:51:04 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 17:51:04 - test_network_sriov_stress.py - [line:451] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 17:51:08 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.302 ms
2022-03-14 17:51:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.395 ms
2022-03-14 17:51:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.529 ms
2022-03-14 17:51:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.415 ms
2022-03-14 17:51:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.499 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.302/0.428/0.529/0.080 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:51:21 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 17:51:30 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 05:59:51 AM EDT
  System load:  0.08               Processes:             138
  Usage of /:   36.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:54:11 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:51:39 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 17:51:45 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 17:51:51 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 17:51:56 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 17:52:02 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 17:52:05 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 17:52:11 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 17:52:21 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 17:52:30 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 17:52:39 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 17:52:48 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 17:52:57 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:53:04 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.231 ms
2022-03-14 17:53:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.253 ms
2022-03-14 17:53:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.302 ms
2022-03-14 17:53:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.337 ms
2022-03-14 17:53:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.381 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.231/0.300/0.381/0.058 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:53:17 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 17:53:26 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:01:47 AM EDT
  System load:  0.06               Processes:             137
  Usage of /:   36.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:51:53 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:53:35 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 17:53:41 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 17:53:47 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 17:53:52 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 17:53:58 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 17:54:01 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 17:54:07 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 17:54:17 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 17:54:26 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 17:54:35 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 17:54:44 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 17:54:53 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:54:56 - test_network_sriov_stress.py - [line:469] - root - INFO - Ping two vms IP from SUT:
2022-03-14 17:55:00 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.513 ms
2022-03-14 17:55:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.285 ms
2022-03-14 17:55:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.214 ms
2022-03-14 17:55:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.218 ms
2022-03-14 17:55:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.204 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4083ms
rtt min/avg/max/mdev = 0.204/0.286/0.513/0.118 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:55:11 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.572 ms
2022-03-14 17:55:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.224 ms
2022-03-14 17:55:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.209 ms
2022-03-14 17:55:14 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.161 ms
2022-03-14 17:55:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.202 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4077ms
rtt min/avg/max/mdev = 0.161/0.273/0.572/0.151 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:55:18 - test_network_sriov_stress.py - [line:477] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 17:55:22 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.286 ms
2022-03-14 17:55:23 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.291 ms
2022-03-14 17:55:24 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.464 ms
2022-03-14 17:55:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.391 ms
2022-03-14 17:55:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.394 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4136ms
rtt min/avg/max/mdev = 0.286/0.365/0.464/0.068 ms
[root@WW25ICX2 ~]# 
2022-03-14 17:55:35 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 17:55:44 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:04:05 AM EDT
  System load:  0.0                Processes:             130
  Usage of /:   36.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 05:59:52 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 17:55:51 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.246 ms
2022-03-14 17:55:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.244 ms
2022-03-14 17:55:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.306 ms
2022-03-14 17:55:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.202 ms
2022-03-14 17:55:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.230 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.202/0.245/0.306/0.034 ms
root@localhost:~# 
2022-03-14 17:56:35 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 17:56:38 - test_network_sriov_stress.py - [line:485] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 17:56:42 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 17:56:45 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 17:56:48 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4110ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 17:56:54 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:56:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:57:01 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 17:57:04 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 17:57:04 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 17:57:09 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 17:57:12 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 17:57:13 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 17:57:18 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 17:57:21 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 17:57:21 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 17:57:26 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 17:57:29 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 17:57:29 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 17:57:34 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 17:57:34 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2022-03-14 17:57:37 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 17:57:38 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 17:57:43 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 17:57:43 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 17:57:43 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 17:57:49 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 17:57:52 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:57:58 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-14 17:58:01 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 17:58:04 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 17:58:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:58:09 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 17:58:12 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 17:58:12 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 17:58:17 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 17:58:20 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 17:58:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:58:28 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 17:58:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:58:34 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:58:37 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 17:58:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:58:43 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 17:58:43 - test_network_sriov_stress.py - [line:422] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:58:46 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 17:58:46 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 17:58:51 - test_network_sriov_stress.py - [line:433] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 17:58:54 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 17:58:54 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 17:58:59 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 17:59:03 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:63761): [1;33mWARNING[0m **: [34m18:07:27.687[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:59:06 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:63761): [1;33mWARNING[0m **: [34m18:07:27.687[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:59:06 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 17:59:10 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:63767): [1;33mWARNING[0m **: [34m18:07:34.711[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:59:12 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:59:15 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 17:59:19 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole
2022-03-14 17:59:20 - sshInstance.py - [line:71] - root - INFO - 
** (process:63811): [1;33mWARNING[0m **: [34m18:07:43.999[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:59:23 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:63811): [1;33mWARNING[0m **: [34m18:07:43.999[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 17:59:23 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 17:59:27 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:63816): [1;33mWARNING[0m **: [34m18:07:51.830[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 17:59:29 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 17:59:32 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 17:59:35 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 17:59:35 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 17:59:40 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 18:00:43 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 18:00:43 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 18:00:48 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-03-14 18:00:51 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 18:00:51 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 18:00:56 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.72/24

2022-03-14 18:00:56 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 18:00:56 - test_network_sriov_stress.py - [line:451] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 18:01:00 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.397 ms
2022-03-14 18:01:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.536 ms
2022-03-14 18:01:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.527 ms
2022-03-14 18:01:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.569 ms
2022-03-14 18:01:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.390 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4105ms
rtt min/avg/max/mdev = 0.390/0.483/0.569/0.080 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:01:13 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 18:01:22 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:09:44 AM EDT
  System load:  0.03               Processes:             135
  Usage of /:   36.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 06:04:06 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 18:01:31 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 18:01:37 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 18:01:43 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 18:01:48 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 18:01:54 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 18:01:57 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 18:02:03 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 18:02:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 18:02:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 18:02:31 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 18:02:40 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 18:02:49 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 18:02:56 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.352 ms
2022-03-14 18:02:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.353 ms
2022-03-14 18:02:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.521 ms
2022-03-14 18:02:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.320 ms
2022-03-14 18:03:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.322 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.320/0.373/0.521/0.077 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:03:09 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 18:03:18 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:11:40 AM EDT
  System load:  0.04               Processes:             140
  Usage of /:   36.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 06:01:48 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 18:03:27 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 18:03:33 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 18:03:39 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 18:03:44 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 18:03:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 18:03:53 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 18:03:59 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 18:04:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 18:04:18 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 18:04:27 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 18:04:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 18:04:45 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 18:04:48 - test_network_sriov_stress.py - [line:469] - root - INFO - Ping two vms IP from SUT:
2022-03-14 18:04:52 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.533 ms
2022-03-14 18:04:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.272 ms
2022-03-14 18:04:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.230 ms
2022-03-14 18:04:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.218 ms
2022-03-14 18:04:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.216 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.216/0.293/0.533/0.123 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:05:03 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.351 ms
2022-03-14 18:05:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.251 ms
2022-03-14 18:05:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.160 ms
2022-03-14 18:05:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.111 ms
2022-03-14 18:05:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.207 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4092ms
rtt min/avg/max/mdev = 0.111/0.216/0.351/0.082 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:05:10 - test_network_sriov_stress.py - [line:477] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 18:05:14 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.475 ms
2022-03-14 18:05:15 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.327 ms
2022-03-14 18:05:16 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.360 ms
2022-03-14 18:05:17 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.467 ms
2022-03-14 18:05:18 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.393 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.327/0.404/0.475/0.061 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:05:27 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 18:05:36 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:13:58 AM EDT
  System load:  0.0                Processes:             127
  Usage of /:   36.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 06:09:44 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 18:05:43 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.390 ms
2022-03-14 18:05:44 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.219 ms
2022-03-14 18:05:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.201 ms
2022-03-14 18:05:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.208 ms
2022-03-14 18:05:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.203 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4092ms
rtt min/avg/max/mdev = 0.201/0.244/0.390/0.073 ms
root@localhost:~# 
2022-03-14 18:06:27 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 18:06:30 - test_network_sriov_stress.py - [line:485] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 18:06:34 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 18:06:37 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 18:06:40 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4126ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 18:06:46 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 18:06:49 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:06:54 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 18:06:57 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 18:06:57 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 18:07:02 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 18:07:05 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 18:07:05 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 18:07:10 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 18:07:13 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 18:07:13 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 18:07:18 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 18:07:21 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 18:07:21 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 18:07:26 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 18:07:26 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 5 time when VF is Assigned VM guest.*************************************************************


2022-03-14 18:07:29 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 18:07:30 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 18:07:35 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 18:07:35 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 18:07:35 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 18:07:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 18:07:44 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 18:07:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-14 18:07:53 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 18:07:56 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 18:07:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:08:01 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 18:08:04 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 18:08:04 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 18:08:09 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 18:08:12 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 18:08:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:08:20 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 18:08:21 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:08:26 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 18:08:29 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 18:08:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:08:35 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 18:08:35 - test_network_sriov_stress.py - [line:422] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 18:08:38 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 18:08:38 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 18:08:43 - test_network_sriov_stress.py - [line:433] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 18:08:46 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 18:08:46 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 18:08:51 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 18:08:55 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 18:08:56 - sshInstance.py - [line:71] - root - INFO - 
** (process:69896): [1;33mWARNING[0m **: [34m18:17:20.506[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 18:08:59 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:69896): [1;33mWARNING[0m **: [34m18:17:20.506[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 18:08:59 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 18:09:03 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 18:09:04 - sshInstance.py - [line:71] - root - INFO - 
** (process:69945): [1;33mWARNING[0m **: [34m18:17:28.558[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 18:09:06 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 18:09:09 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 18:09:13 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:69995): [1;33mWARNING[0m **: [34m18:17:38.262[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 18:09:16 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:69995): [1;33mWARNING[0m **: [34m18:17:38.262[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 18:09:16 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 18:09:20 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:70310): [1;33mWARNING[0m **: [34m18:17:45.519[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-14 18:09:21 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 18:09:22 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
2022-03-14 18:09:23 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 18:09:26 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 18:09:29 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 18:09:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:09:34 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 18:10:37 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 18:10:38 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 18:10:43 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.208/24

2022-03-14 18:10:46 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 18:10:46 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 18:10:51 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.72/24

2022-03-14 18:10:51 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 18:10:51 - test_network_sriov_stress.py - [line:451] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 18:10:55 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.384 ms
2022-03-14 18:10:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.340 ms
2022-03-14 18:10:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.400 ms
2022-03-14 18:10:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.478 ms
2022-03-14 18:10:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.482 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4111ms
rtt min/avg/max/mdev = 0.340/0.416/0.482/0.060 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:11:08 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 18:11:17 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:19:37 AM EDT
  System load:  0.0                Processes:             138
  Usage of /:   37.0% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 06:13:58 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 18:11:26 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 18:11:32 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 18:11:38 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 18:11:43 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 18:11:49 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 18:11:52 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 18:11:58 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 18:12:08 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 18:12:17 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 18:12:26 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 18:12:35 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 18:12:44 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 18:12:51 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.475 ms
2022-03-14 18:12:52 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.493 ms
2022-03-14 18:12:53 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.465 ms
2022-03-14 18:12:54 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.310 ms
2022-03-14 18:12:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.493 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4076ms
rtt min/avg/max/mdev = 0.310/0.447/0.493/0.070 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:13:04 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 18:13:13 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:21:34 AM EDT
  System load:  0.0                Processes:             139
  Usage of /:   37.0% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 06:11:41 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 18:13:22 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 18:13:28 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 18:13:34 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 18:13:39 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 18:13:45 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 18:13:48 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 18:13:54 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 18:14:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 18:14:13 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 18:14:22 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 18:14:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 18:14:40 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 18:14:43 - test_network_sriov_stress.py - [line:469] - root - INFO - Ping two vms IP from SUT:
2022-03-14 18:14:47 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.428 ms
2022-03-14 18:14:48 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.301 ms
2022-03-14 18:14:49 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.278 ms
2022-03-14 18:14:50 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.198 ms
2022-03-14 18:14:51 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.271 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.198/0.295/0.428/0.075 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:14:58 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.901 ms
2022-03-14 18:14:59 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.274 ms
2022-03-14 18:15:00 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.253 ms
2022-03-14 18:15:01 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.162 ms
2022-03-14 18:15:02 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.240 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4100ms
rtt min/avg/max/mdev = 0.162/0.366/0.901/0.270 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:15:05 - test_network_sriov_stress.py - [line:477] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 18:15:09 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.421 ms
2022-03-14 18:15:10 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.568 ms
2022-03-14 18:15:11 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.514 ms
2022-03-14 18:15:12 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.489 ms
2022-03-14 18:15:13 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.420 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4095ms
rtt min/avg/max/mdev = 0.420/0.482/0.568/0.059 ms
[root@WW25ICX2 ~]# 
2022-03-14 18:15:22 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 18:15:31 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 06:23:52 AM EDT
  System load:  0.0                Processes:             130
  Usage of /:   37.0% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 06:19:38 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 18:15:38 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.702 ms
2022-03-14 18:15:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.308 ms
2022-03-14 18:15:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.328 ms
2022-03-14 18:15:41 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.333 ms
2022-03-14 18:15:42 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.216 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4100ms
rtt min/avg/max/mdev = 0.216/0.377/0.702/0.167 ms
root@localhost:~# 
2022-03-14 18:16:22 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 18:16:25 - test_network_sriov_stress.py - [line:485] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 18:16:29 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 18:16:32 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 18:16:35 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4134ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 18:16:41 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 18:16:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:16:48 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 18:16:51 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 18:16:51 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 18:16:56 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 18:17:00 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 18:17:00 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 18:17:05 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 18:17:08 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 18:17:08 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 18:17:13 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 18:17:16 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 18:17:16 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 18:17:21 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
.2022-03-14 18:17:24 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 18:17:24 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-14 18:17:29 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 18:17:32 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 18:17:32 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-14 18:17:37 - test_network_sriov_stress.py - [line:290] - root - ERROR - Failed to removed the VM VMtest2
2022-03-14 18:17:40 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 18:17:40 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-14 18:17:45 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 18:17:48 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 18:17:48 - sshInstance.py - [line:50] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-14 18:17:53 - test_network_sriov_stress.py - [line:290] - root - ERROR - Failed to removed the VM VMtest1
2022-03-14 18:17:56 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 18:17:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:18:04 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-03-14 18:18:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:18:12 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 0
2022-03-14 18:18:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:18:20 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-14 18:18:21 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:18:26 - test_network_sriov_stress.py - [line:82] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-14 18:18:26 - test_network_sriov_stress.py - [line:84] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-14/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]_17_27_01
2022-03-14 18:18:29 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-14 18:18:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 18:18:34 - test_network_sriov_stress.py - [line:86] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-14 18:18:34 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-14 18:18:34 - NicTestFixture.py - [line:41] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
                  [100%]

=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:70
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:108
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:383
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:383: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:501
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:501: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:800
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:800: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:92
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:92: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:117
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:117: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:141
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:141: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:173
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:173: PytestUnknownMarkWarning: Unknown pytest.mark.driveInstall - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.driveInstall

npxtester/Tests/testNics/test_nics.py:213
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:213: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:239
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:239: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
========== 1 passed, 16 deselected, 15 warnings in 3092.34s (0:51:32) ==========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
[8mha:////4LN/0LMxu1hyybTBeE6CHwDx82bv/lkvxFk3cdgHTSuWAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMPkEZb3/VO3favo5XL4AAAA=[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4FgvIflgycWoJq7MsZycbV9d7HENRG2WSX14oF+Me/GuAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAR2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwZyt32U/vwBq1seBO+AAAA[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4P37N80+NRbzyFlga2j1WDon6H/4VmnQwrRysqQpQX/3AAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigagQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUO62n9qHN+xdYwq+AAAA[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh
/root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/log_analyzer/log_analyzer.sh: line 7: [: too many arguments
[8mha:////4P3ih/vRXCzaXCkS1CQDBQXrb3I4EZcCr0NGGH+tKlR4AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigUSDqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFDu9p/avgEjVhSLvgAAAA==[0m[Pipeline] }
[8mha:////4ISV0Ptmba0km8a80Gq+UClogdZnPDxCJXroOoeI5sULAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiREGBqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFDu9p/avgE81EHZvgAAAA==[0m[Pipeline] // stage
[8mha:////4LmA5LOJ1yGOO5YQ6RYn+/szIsYEkfxAArsUKSFs0Xa0AAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEBCVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Nu9INt9AE/B/a+9AAAA[0m[Pipeline] }
[8mha:////4KVKO0UZMawo8C9tjXN4L1+ryWbU4zmvD2sDlsKoyYtXAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUVI5jZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0gL/eCrPwAXH35DL0AAAA=[0m[Pipeline] // node
[8mha:////4A8vvhfR6oegt+2XAbvn3Z0Fx6j3lb1QUh2abilCs+OGAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBAx/ra70AAAA=[0m[Pipeline] End of Pipeline
Finished: SUCCESS
