Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","connect_switch_sut_pf":"ens2f0","pf1":"ens2f0","pf1_ipv6":"fe80::b696:91ff:fe9c:f7a4","os":"rehat"},"dhcp":{"ipv4":"192.168.10.11","ipv6":"fe80::b696:91ff:fea5:9b45"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 15 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-02-17 02:36:16 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-02-17 02:36:16 - test_network_sriov_stress.py - [line:31] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-02-17 02:36:16 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-17 02:36:16 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-17 02:36:16 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-02-17 02:36:17 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-02-17 02:36:17 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-02-17 02:36:17 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-02-17 02:36:17 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-02-17 02:36:17 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-02-17 02:36:20 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-17 02:36:20 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-17 02:36:25 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-17 02:36:25 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-17 02:36:25 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-17 02:36:31 - sshInstance.py - [line:92] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Feb 16 22:33:31 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-17 02:36:34 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-17 02:36:37 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 02:36:37 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:36:42 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-17 02:36:45 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-17 02:36:45 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-17 02:36:50 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-17 02:36:53 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-17 02:36:53 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-17 02:36:58 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-17 02:37:01 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-17 02:37:02 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:37:07 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 02:37:10 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-17 02:37:10 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:37:15 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 02:37:15 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 02:37:18 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 02:37:18 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-17 02:37:23 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-17 02:37:26 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-17 02:37:27 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-17 02:37:32 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-17 02:37:36 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:27453): [1;33mWARNING[0m **: [34m02:47:00.891[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 02:37:38 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 02:37:41 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-17 02:37:45 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:27506): [1;33mWARNING[0m **: [34m02:47:09.833[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 02:37:47 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 02:37:50 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-17 02:37:53 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:37:53 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:37:58 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest1
2022-02-17 02:39:01 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:39:01 - sshInstance.py - [line:48] - root - INFO - 192.168.122.148/24

2022-02-17 02:39:06 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.148/24

2022-02-17 02:39:09 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:39:09 - sshInstance.py - [line:48] - root - INFO - 192.168.122.218/24

2022-02-17 02:39:14 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.218/24

2022-02-17 02:39:14 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.148
2022-02-17 02:39:14 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.218
2022-02-17 02:39:18 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.378 ms
2022-02-17 02:39:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.426 ms
2022-02-17 02:39:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.474 ms
2022-02-17 02:39:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.487 ms
2022-02-17 02:39:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.336 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4124ms
rtt min/avg/max/mdev = 0.336/0.420/0.487/0.058 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:39:31 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
The authenticity of host '192.168.122.148 (192.168.122.148)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-17 02:39:40 - sshInstance.py - [line:92] - root - INFO - yes
Warning: Permanently added '192.168.122.148' (ECDSA) to the list of known hosts.
root@192.168.122.148's password: 
2022-02-17 02:39:49 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 01:49:11 PM EST
  System load:  0.0                Processes:             139
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 09:40:52 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:39:58 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 02:40:04 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 02:40:10 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 02:40:15 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 02:40:21 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-17 02:40:24 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 02:40:30 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 02:40:40 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-17 02:40:49 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 02:40:58 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 02:41:07 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 02:41:16 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 02:41:23 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.218
PING 192.168.122.218 (192.168.122.218) 56(84) bytes of data.
64 bytes from 192.168.122.218: icmp_seq=1 ttl=64 time=0.320 ms
2022-02-17 02:41:24 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=2 ttl=64 time=0.389 ms
2022-02-17 02:41:25 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=3 ttl=64 time=0.267 ms
2022-02-17 02:41:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=4 ttl=64 time=0.454 ms
2022-02-17 02:41:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=5 ttl=64 time=0.468 ms

--- 192.168.122.218 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4104ms
rtt min/avg/max/mdev = 0.267/0.379/0.468/0.079 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:41:36 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.218
The authenticity of host '192.168.122.218 (192.168.122.218)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-02-17 02:41:45 - sshInstance.py - [line:92] - root - INFO - yes
Warning: Permanently added '192.168.122.218' (ECDSA) to the list of known hosts.
root@192.168.122.218's password: 
2022-02-17 02:41:54 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 01:51:16 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.218
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 09:41:50 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:42:03 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 02:42:09 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 02:42:15 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 02:42:20 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 02:42:26 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-17 02:42:29 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 02:42:35 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 02:42:45 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-17 02:42:54 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 02:43:03 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 02:43:12 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 4  bytes 1368 (1.3 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 02:43:21 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.218 closed.
[root@WW25ICX2 ~]# 
2022-02-17 02:43:24 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-17 02:43:28 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.653 ms
2022-02-17 02:43:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.300 ms
2022-02-17 02:43:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.213 ms
2022-02-17 02:43:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.212 ms
2022-02-17 02:43:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.128 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.128/0.301/0.653/0.184 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:43:39 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.233 ms
2022-02-17 02:43:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.129 ms
2022-02-17 02:43:41 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.200 ms
2022-02-17 02:43:42 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.201 ms
2022-02-17 02:43:43 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.128 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.128/0.178/0.233/0.043 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:43:46 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 02:43:50 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.259 ms
2022-02-17 02:43:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.346 ms
2022-02-17 02:43:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.349 ms
2022-02-17 02:43:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.247 ms
2022-02-17 02:43:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.315 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.247/0.303/0.349/0.044 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:44:03 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 02:44:12 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 01:53:35 PM EST
  System load:  0.0                Processes:             129
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 13:49:12 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:44:19 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.378 ms
2022-02-17 02:44:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.211 ms
2022-02-17 02:44:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.109 ms
2022-02-17 02:44:22 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.201 ms
2022-02-17 02:44:23 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.105 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.105/0.200/0.378/0.099 ms
root@localhost:~# 
2022-02-17 02:45:03 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 02:45:06 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 02:45:10 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.406 ms
2022-02-17 02:45:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.279 ms
2022-02-17 02:45:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.230 ms
2022-02-17 02:45:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.219 ms
2022-02-17 02:45:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.251 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4114ms
rtt min/avg/max/mdev = 0.219/0.277/0.406/0.067 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:45:20 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 02:45:22 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:45:27 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-17 02:45:30 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-17 02:45:31 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-17 02:45:36 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-17 02:45:39 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-17 02:45:39 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-17 02:45:44 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-17 02:45:47 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-17 02:45:47 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-17 02:45:52 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-17 02:45:55 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-17 02:45:55 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-17 02:46:00 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-17 02:46:00 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-02-17 02:46:03 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-17 02:46:03 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-17 02:46:08 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-17 02:46:08 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-17 02:46:08 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-17 02:46:14 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-17 02:46:17 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-17 02:46:20 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 02:46:20 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:46:25 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-17 02:46:28 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-17 02:46:29 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-17 02:46:34 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-17 02:46:37 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-17 02:46:37 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-17 02:46:42 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-17 02:46:45 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-17 02:46:45 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:46:50 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 02:46:53 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-17 02:46:54 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:46:59 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 02:46:59 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 02:47:02 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 02:47:02 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-17 02:47:07 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-17 02:47:10 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-17 02:47:10 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-17 02:47:15 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-17 02:47:19 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:28805): [1;33mWARNING[0m **: [34m02:56:43.834[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:47:22 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:28805): [1;33mWARNING[0m **: [34m02:56:43.834[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:47:22 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 02:47:26 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:28817): [1;33mWARNING[0m **: [34m02:56:50.855[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 02:47:27 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 02:47:30 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-17 02:47:34 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:28861): [1;33mWARNING[0m **: [34m02:56:58.851[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:47:37 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:28861): [1;33mWARNING[0m **: [34m02:56:58.851[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:47:37 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 02:47:41 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:28868): [1;33mWARNING[0m **: [34m02:57:05.862[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 02:47:43 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 02:47:46 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-17 02:47:49 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:47:49 - sshInstance.py - [line:48] - root - INFO - 192.168.122.148/24

2022-02-17 02:47:54 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.148/24

2022-02-17 02:47:57 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:47:57 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:48:02 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-17 02:49:05 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:49:05 - sshInstance.py - [line:48] - root - INFO - 192.168.122.218/24

2022-02-17 02:49:10 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.218/24

2022-02-17 02:49:10 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.148
2022-02-17 02:49:10 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.218
2022-02-17 02:49:14 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.326 ms
2022-02-17 02:49:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.253 ms
2022-02-17 02:49:16 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.395 ms
2022-02-17 02:49:17 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.267 ms
2022-02-17 02:49:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.500 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.253/0.348/0.500/0.091 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:49:27 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 02:49:36 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 01:58:59 PM EST
  System load:  0.0                Processes:             139
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 13:53:35 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:49:45 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 02:49:51 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 02:49:57 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 02:50:02 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 02:50:08 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-17 02:50:11 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 02:50:17 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 02:50:27 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-17 02:50:36 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 02:50:45 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 02:50:54 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 02:51:03 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 02:51:10 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.218
PING 192.168.122.218 (192.168.122.218) 56(84) bytes of data.
64 bytes from 192.168.122.218: icmp_seq=1 ttl=64 time=0.230 ms
2022-02-17 02:51:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=2 ttl=64 time=0.512 ms
2022-02-17 02:51:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=3 ttl=64 time=0.332 ms
2022-02-17 02:51:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=4 ttl=64 time=0.459 ms
2022-02-17 02:51:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=5 ttl=64 time=0.253 ms

--- 192.168.122.218 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.230/0.357/0.512/0.111 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:51:23 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.218
root@192.168.122.218's password: 
2022-02-17 02:51:32 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:00:54 PM EST
  System load:  0.0                Processes:             139
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.218
  Swap usage:   0%

366 updates can be installed immediately.
238 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 13:51:16 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:51:41 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 02:51:47 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 02:51:53 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 02:51:58 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 02:52:04 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-17 02:52:07 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 02:52:13 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 02:52:23 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-17 02:52:32 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 02:52:41 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 02:52:50 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 02:52:59 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.218 closed.
[root@WW25ICX2 ~]# 
2022-02-17 02:53:02 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-17 02:53:06 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.530 ms
2022-02-17 02:53:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.203 ms
2022-02-17 02:53:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.189 ms
2022-02-17 02:53:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.334 ms
2022-02-17 02:53:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.267 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4081ms
rtt min/avg/max/mdev = 0.189/0.304/0.530/0.125 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:53:17 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.599 ms
2022-02-17 02:53:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.837 ms
2022-02-17 02:53:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.295 ms
2022-02-17 02:53:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.178 ms
2022-02-17 02:53:21 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.270 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.178/0.435/0.837/0.246 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:53:24 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 02:53:28 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.210 ms
2022-02-17 02:53:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.315 ms
2022-02-17 02:53:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.350 ms
2022-02-17 02:53:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.255 ms
2022-02-17 02:53:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.462 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.210/0.318/0.462/0.087 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:53:41 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 02:53:50 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:03:13 PM EST
  System load:  0.0                Processes:             129
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 13:58:59 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:53:57 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.279 ms
2022-02-17 02:53:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.200 ms
2022-02-17 02:53:59 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.111 ms
2022-02-17 02:54:00 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.201 ms
2022-02-17 02:54:01 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.201 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4091ms
rtt min/avg/max/mdev = 0.111/0.198/0.279/0.053 ms
root@localhost:~# 
2022-02-17 02:54:41 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 02:54:44 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 02:54:48 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.218 ms
2022-02-17 02:54:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.234 ms
2022-02-17 02:54:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.214 ms
2022-02-17 02:54:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.238 ms
2022-02-17 02:54:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.268 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4107ms
rtt min/avg/max/mdev = 0.214/0.234/0.268/0.023 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:54:58 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 02:55:01 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:55:06 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-17 02:55:09 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-17 02:55:09 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-17 02:55:14 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-17 02:55:17 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-17 02:55:17 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-17 02:55:22 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-17 02:55:25 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-17 02:55:25 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-17 02:55:30 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-17 02:55:33 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-17 02:55:33 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-17 02:55:38 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-17 02:55:38 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 3 time when VF is Assigned VM guest.*************************************************************


2022-02-17 02:55:41 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-17 02:55:41 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-17 02:55:46 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-17 02:55:46 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-17 02:55:46 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-17 02:55:52 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-17 02:55:55 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-17 02:55:58 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 02:55:59 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:56:04 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-17 02:56:07 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-17 02:56:07 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-17 02:56:12 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-17 02:56:15 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-17 02:56:15 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-17 02:56:20 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-17 02:56:23 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-17 02:56:23 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:56:28 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 02:56:31 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-17 02:56:32 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:56:37 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 02:56:37 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 02:56:40 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 02:56:40 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-17 02:56:45 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-17 02:56:48 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-17 02:56:48 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-17 02:56:53 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-17 02:56:57 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:29958): [1;33mWARNING[0m **: [34m03:06:22.163[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:57:00 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:29958): [1;33mWARNING[0m **: [34m03:06:22.163[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:57:00 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 02:57:04 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:29963): [1;33mWARNING[0m **: [34m03:06:29.160[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 02:57:06 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 02:57:09 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-17 02:57:13 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:30007): [1;33mWARNING[0m **: [34m03:06:38.160[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:57:16 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:30007): [1;33mWARNING[0m **: [34m03:06:38.160[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 02:57:16 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 02:57:20 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:30013): [1;33mWARNING[0m **: [34m03:06:45.142[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 02:57:22 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 02:57:25 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-17 02:57:28 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:57:28 - sshInstance.py - [line:48] - root - INFO - 192.168.122.148/24

2022-02-17 02:57:33 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.148/24

2022-02-17 02:57:36 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:57:36 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 02:57:41 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-17 02:58:44 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 02:58:44 - sshInstance.py - [line:48] - root - INFO - 192.168.122.218/24

2022-02-17 02:58:49 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.218/24

2022-02-17 02:58:49 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.148
2022-02-17 02:58:49 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.218
2022-02-17 02:58:53 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.255 ms
2022-02-17 02:58:54 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.508 ms
2022-02-17 02:58:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.251 ms
2022-02-17 02:58:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.269 ms
2022-02-17 02:58:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.456 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4107ms
rtt min/avg/max/mdev = 0.251/0.347/0.508/0.113 ms
[root@WW25ICX2 ~]# 
2022-02-17 02:59:06 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 02:59:15 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:08:37 PM EST
  System load:  0.16               Processes:             135
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:03:13 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 02:59:24 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 02:59:30 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 02:59:36 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 02:59:41 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 02:59:47 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-17 02:59:50 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 02:59:56 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 03:00:06 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-17 03:00:15 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 03:00:24 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 03:00:33 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 03:00:42 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:00:49 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.218
PING 192.168.122.218 (192.168.122.218) 56(84) bytes of data.
64 bytes from 192.168.122.218: icmp_seq=1 ttl=64 time=0.478 ms
2022-02-17 03:00:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=2 ttl=64 time=0.380 ms
2022-02-17 03:00:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=3 ttl=64 time=0.266 ms
2022-02-17 03:00:52 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=4 ttl=64 time=0.468 ms
2022-02-17 03:00:53 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=5 ttl=64 time=0.313 ms

--- 192.168.122.218 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4136ms
rtt min/avg/max/mdev = 0.266/0.381/0.478/0.083 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:01:02 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.218
root@192.168.122.218's password: 
2022-02-17 03:01:11 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:10:33 PM EST
  System load:  0.0                Processes:             138
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.218
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:00:55 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:01:20 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 03:01:26 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 03:01:32 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 03:01:37 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 03:01:43 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-17 03:01:46 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 03:01:52 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 03:02:02 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-17 03:02:11 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 03:02:20 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 03:02:29 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 342 (342.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 03:02:38 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.218 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:02:41 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-17 03:02:45 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.415 ms
2022-02-17 03:02:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.127 ms
2022-02-17 03:02:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.238 ms
2022-02-17 03:02:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.187 ms
2022-02-17 03:02:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.238 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4102ms
rtt min/avg/max/mdev = 0.127/0.241/0.415/0.096 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:02:57 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.413 ms
2022-02-17 03:02:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.230 ms
2022-02-17 03:02:59 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.308 ms
2022-02-17 03:03:00 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.322 ms
2022-02-17 03:03:01 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.272 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.230/0.309/0.413/0.060 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:03:04 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 03:03:08 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.437 ms
2022-02-17 03:03:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.502 ms
2022-02-17 03:03:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.474 ms
2022-02-17 03:03:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.395 ms
2022-02-17 03:03:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.371 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4090ms
rtt min/avg/max/mdev = 0.371/0.435/0.502/0.055 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:03:21 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 03:03:30 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:12:52 PM EST
  System load:  0.0                Processes:             134
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:08:38 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:03:37 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.248 ms
2022-02-17 03:03:38 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.297 ms
2022-02-17 03:03:39 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.155 ms
2022-02-17 03:03:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.232 ms
2022-02-17 03:03:41 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.185 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4074ms
rtt min/avg/max/mdev = 0.155/0.223/0.297/0.049 ms
root@localhost:~# 
2022-02-17 03:04:21 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:04:24 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 03:04:28 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.280 ms
2022-02-17 03:04:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.241 ms
2022-02-17 03:04:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.287 ms
2022-02-17 03:04:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.235 ms
2022-02-17 03:04:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.258 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4129ms
rtt min/avg/max/mdev = 0.235/0.260/0.287/0.022 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:04:38 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 03:04:40 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:04:45 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-17 03:04:48 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-17 03:04:48 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-17 03:04:53 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-17 03:04:56 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-17 03:04:56 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-17 03:05:01 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-17 03:05:04 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-17 03:05:04 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-17 03:05:09 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-17 03:05:12 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-17 03:05:12 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-17 03:05:17 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-17 03:05:17 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 4 time when VF is Assigned VM guest.*************************************************************


2022-02-17 03:05:20 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-17 03:05:21 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-17 03:05:26 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-17 03:05:26 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-17 03:05:26 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-17 03:05:32 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-17 03:05:35 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-17 03:05:38 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 03:05:38 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:05:43 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-17 03:05:46 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-17 03:05:46 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-17 03:05:51 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-17 03:05:54 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-17 03:05:54 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-17 03:05:59 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-17 03:06:02 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-17 03:06:03 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:06:08 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 03:06:11 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-17 03:06:11 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:06:16 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 03:06:16 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 03:06:19 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 03:06:19 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-17 03:06:24 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-17 03:06:27 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-17 03:06:27 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-17 03:06:32 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-17 03:06:36 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:30964): [1;33mWARNING[0m **: [34m03:16:01.343[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:06:39 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:30964): [1;33mWARNING[0m **: [34m03:16:01.343[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:06:39 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 03:06:43 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:30970): [1;33mWARNING[0m **: [34m03:16:08.257[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 03:06:45 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 03:06:48 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-17 03:06:52 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:31014): [1;33mWARNING[0m **: [34m03:16:17.302[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:06:55 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:31014): [1;33mWARNING[0m **: [34m03:16:17.302[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:06:55 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 03:06:59 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:31020): [1;33mWARNING[0m **: [34m03:16:24.326[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 03:07:01 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 03:07:04 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-17 03:07:07 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-17 03:07:07 - sshInstance.py - [line:48] - root - INFO - 192.168.122.148/24

2022-02-17 03:07:12 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.148/24

2022-02-17 03:07:15 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 03:07:15 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:07:20 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-17 03:08:23 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 03:08:23 - sshInstance.py - [line:48] - root - INFO - 192.168.122.218/24

2022-02-17 03:08:28 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.218/24

2022-02-17 03:08:28 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.148
2022-02-17 03:08:28 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.218
2022-02-17 03:08:32 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.203 ms
2022-02-17 03:08:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.265 ms
2022-02-17 03:08:34 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.460 ms
2022-02-17 03:08:35 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.466 ms
2022-02-17 03:08:36 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.336 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4134ms
rtt min/avg/max/mdev = 0.203/0.346/0.466/0.104 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:08:45 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 03:08:54 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:18:16 PM EST
  System load:  0.0                Processes:             140
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:12:52 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:09:03 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 03:09:09 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 03:09:15 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 03:09:20 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 03:09:26 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-17 03:09:29 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 03:09:35 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 03:09:45 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-17 03:09:55 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 03:10:04 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 03:10:13 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1026 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 03:10:22 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:10:29 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.218
PING 192.168.122.218 (192.168.122.218) 56(84) bytes of data.
64 bytes from 192.168.122.218: icmp_seq=1 ttl=64 time=0.303 ms
2022-02-17 03:10:30 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=2 ttl=64 time=0.464 ms
2022-02-17 03:10:31 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=3 ttl=64 time=0.475 ms
2022-02-17 03:10:32 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=4 ttl=64 time=0.361 ms
2022-02-17 03:10:33 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=5 ttl=64 time=0.255 ms

--- 192.168.122.218 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4099ms
rtt min/avg/max/mdev = 0.255/0.371/0.475/0.089 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:10:42 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.218
root@192.168.122.218's password: 
2022-02-17 03:10:51 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:20:12 PM EST
  System load:  0.0                Processes:             137
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.218
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:10:34 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:11:00 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 03:11:06 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 03:11:12 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 03:11:17 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 03:11:23 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-17 03:11:26 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 03:11:32 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 03:11:42 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-17 03:11:51 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 03:12:00 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 03:12:09 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 03:12:18 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.218 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:12:21 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-17 03:12:25 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.429 ms
2022-02-17 03:12:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.155 ms
2022-02-17 03:12:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.200 ms
2022-02-17 03:12:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.128 ms
2022-02-17 03:12:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.208 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4128ms
rtt min/avg/max/mdev = 0.128/0.224/0.429/0.106 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:12:36 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.480 ms
2022-02-17 03:12:37 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.632 ms
2022-02-17 03:12:38 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.319 ms
2022-02-17 03:12:39 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.303 ms
2022-02-17 03:12:40 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.300 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4123ms
rtt min/avg/max/mdev = 0.300/0.406/0.632/0.133 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:12:43 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 03:12:47 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.214 ms
2022-02-17 03:12:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.315 ms
2022-02-17 03:12:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.321 ms
2022-02-17 03:12:50 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.469 ms
2022-02-17 03:12:51 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.270 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.214/0.317/0.469/0.087 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:13:00 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 03:13:09 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:22:30 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:18:16 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:13:16 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.141 ms
2022-02-17 03:13:17 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.148 ms
2022-02-17 03:13:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.054 ms
2022-02-17 03:13:19 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.203 ms
2022-02-17 03:13:20 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.237 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4087ms
rtt min/avg/max/mdev = 0.054/0.156/0.237/0.062 ms
root@localhost:~# 
2022-02-17 03:14:00 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:14:03 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 03:14:07 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.249 ms
2022-02-17 03:14:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.209 ms
2022-02-17 03:14:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.257 ms
2022-02-17 03:14:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.228 ms
2022-02-17 03:14:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.226 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4091ms
rtt min/avg/max/mdev = 0.209/0.233/0.257/0.025 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:14:17 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 03:14:19 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:14:24 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-17 03:14:27 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-17 03:14:27 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-17 03:14:32 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-17 03:14:35 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-17 03:14:35 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-17 03:14:40 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-17 03:14:43 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-17 03:14:43 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-17 03:14:48 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-17 03:14:51 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-17 03:14:51 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-17 03:14:56 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-17 03:14:56 - test_network_sriov_stress.py - [line:369] - root - INFO - 

********************************************************Stress Disable and Enable for 5 time when VF is Assigned VM guest.*************************************************************


2022-02-17 03:14:59 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-02-17 03:15:00 - sshInstance.py - [line:48] - root - INFO - 0000:4b:00.0

2022-02-17 03:15:05 - test_network_sriov_stress.py - [line:87] - root - INFO - pf_id was found: 0000:4b:00.0

2022-02-17 03:15:05 - test_network_sriov_stress.py - [line:377] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-02-17 03:15:05 - test_network_sriov_stress.py - [line:380] - root - INFO - pf_id_key: 4b
2022-02-17 03:15:11 - sshInstance.py - [line:92] - root - INFO - ifconfig ens2f0 192.168.10.12
[root@WW25ICX2 ~]# 
2022-02-17 03:15:14 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-02-17 03:15:17 - sshInstance.py - [line:44] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 03:15:17 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:15:22 - test_network_sriov_stress.py - [line:101] - root - INFO - Successfully Virtualized PF to VFs.
2022-02-17 03:15:25 - sshInstance.py - [line:44] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-02-17 03:15:25 - sshInstance.py - [line:48] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-02-17 03:15:30 - test_network_sriov_stress.py - [line:115] - root - INFO - Succssfully Gotten vf_id list:

2022-02-17 03:15:33 - sshInstance.py - [line:44] - root - INFO -  modinfo vfio-pci | grep "vfio_pci" | awk '{ print $2;}'
2022-02-17 03:15:33 - sshInstance.py - [line:48] - root - INFO - vfio_pci

2022-02-17 03:15:38 - test_network_sriov_stress.py - [line:168] - root - INFO - Successfuly modeprobe vfio-pci
2022-02-17 03:15:41 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-02-17 03:15:42 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:15:47 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 03:15:50 - sshInstance.py - [line:44] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-02-17 03:15:50 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:15:55 - test_network_sriov_stress.py - [line:147] - root - INFO - Successfuly bound VF to vfio-pci
2022-02-17 03:15:55 - test_network_sriov_stress.py - [line:401] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 03:15:58 - sshInstance.py - [line:44] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-02-17 03:15:58 - sshInstance.py - [line:48] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-02-17 03:16:03 - test_network_sriov_stress.py - [line:412] - root - INFO - Successfully get vf device id: 8086:1889
2022-02-17 03:16:06 - sshInstance.py - [line:44] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-02-17 03:16:06 - sshInstance.py - [line:48] - root - INFO - yes

2022-02-17 03:16:11 - test_network_sriov_stress.py - [line:177] - root - INFO - Default network is active? yes

2022-02-17 03:16:15 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:32338): [1;33mWARNING[0m **: [34m03:25:40.592[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:16:18 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:32338): [1;33mWARNING[0m **: [34m03:25:40.592[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:16:18 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 03:16:22 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:32352): [1;33mWARNING[0m **: [34m03:25:47.597[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 03:16:24 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 03:16:27 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest1
2022-02-17 03:16:31 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:32402): [1;33mWARNING[0m **: [34m03:25:56.581[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:16:34 - test_network_sriov_stress.py - [line:209] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:32402): [1;33mWARNING[0m **: [34m03:25:56.581[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-02-17 03:16:34 - test_network_sriov_stress.py - [line:210] - root - ERROR - Failed to create a VM: 
2022-02-17 03:16:38 - sshInstance.py - [line:69] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:32415): [1;33mWARNING[0m **: [34m03:26:03.519[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-02-17 03:16:39 - sshInstance.py - [line:69] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-02-17 03:16:42 - test_network_sriov_stress.py - [line:212] - root - INFO - Successfully created a VM: VMtest2
2022-02-17 03:16:45 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-02-17 03:16:45 - sshInstance.py - [line:48] - root - INFO - 192.168.122.148/24

2022-02-17 03:16:51 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest1 IP: 192.168.122.148/24

2022-02-17 03:16:54 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 03:16:54 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:16:59 - test_network_sriov_stress.py - [line:229] - root - ERROR - not found IP of VMtest2
2022-02-17 03:18:02 - sshInstance.py - [line:44] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-02-17 03:18:02 - sshInstance.py - [line:48] - root - INFO - 192.168.122.218/24

2022-02-17 03:18:07 - test_network_sriov_stress.py - [line:224] - root - INFO - Successfully got VMtest2 IP: 192.168.122.218/24

2022-02-17 03:18:07 - test_network_sriov_stress.py - [line:429] - root - INFO - ip of VM1: 192.168.122.148
2022-02-17 03:18:07 - test_network_sriov_stress.py - [line:430] - root - INFO - ip of VM1: 192.168.122.218
2022-02-17 03:18:11 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.294 ms
2022-02-17 03:18:12 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.466 ms
2022-02-17 03:18:13 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.263 ms
2022-02-17 03:18:14 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.462 ms
2022-02-17 03:18:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.460 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4117ms
rtt min/avg/max/mdev = 0.263/0.389/0.466/0.090 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:18:24 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 03:18:33 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:27:54 PM EST
  System load:  0.0                Processes:             138
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:22:30 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:18:42 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 03:18:48 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 03:18:54 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 03:18:59 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 03:19:05 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-02-17 03:19:08 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 03:19:14 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 03:19:24 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-02-17 03:19:33 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 03:19:42 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 03:19:51 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 3  bytes 1026 (1.0 KB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 03:20:00 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:20:07 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.218
PING 192.168.122.218 (192.168.122.218) 56(84) bytes of data.
64 bytes from 192.168.122.218: icmp_seq=1 ttl=64 time=0.436 ms
2022-02-17 03:20:08 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=2 ttl=64 time=0.312 ms
2022-02-17 03:20:09 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=3 ttl=64 time=0.468 ms
2022-02-17 03:20:10 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=4 ttl=64 time=0.263 ms
2022-02-17 03:20:11 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.218: icmp_seq=5 ttl=64 time=0.347 ms

--- 192.168.122.218 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4083ms
rtt min/avg/max/mdev = 0.263/0.365/0.468/0.077 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:20:20 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.218
root@192.168.122.218's password: 
2022-02-17 03:20:29 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:29:50 PM EST
  System load:  0.0                Processes:             144
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.218
  Swap usage:   0%

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:20:13 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:20:38 - sshInstance.py - [line:92] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-02-17 03:20:44 - test_network_sriov_stress.py - [line:322] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-02-17 03:20:50 - sshInstance.py - [line:92] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-02-17 03:20:55 - test_network_sriov_stress.py - [line:336] - root - INFO - Successfully got vf device name of vm1: ens5
2022-02-17 03:21:01 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 192.168.10.14
root@localhost:~# 
2022-02-17 03:21:04 - test_network_sriov_stress.py - [line:283] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-02-17 03:21:10 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-02-17 03:21:20 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-02-17 03:21:29 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-02-17 03:21:38 - sshInstance.py - [line:92] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-02-17 03:21:47 - sshInstance.py - [line:92] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-02-17 03:21:56 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.218 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:21:59 - test_network_sriov_stress.py - [line:450] - root - INFO - Ping two vms IP from SUT:
2022-02-17 03:22:03 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.508 ms
2022-02-17 03:22:04 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.319 ms
2022-02-17 03:22:05 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.197 ms
2022-02-17 03:22:06 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.216 ms
2022-02-17 03:22:07 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.332 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4116ms
rtt min/avg/max/mdev = 0.197/0.314/0.508/0.111 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:22:14 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.350 ms
2022-02-17 03:22:15 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.298 ms
2022-02-17 03:22:16 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.298 ms
2022-02-17 03:22:17 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.216 ms
2022-02-17 03:22:18 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.273 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4110ms
rtt min/avg/max/mdev = 0.216/0.287/0.350/0.043 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:22:21 - test_network_sriov_stress.py - [line:458] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 03:22:25 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.122.148
PING 192.168.122.148 (192.168.122.148) 56(84) bytes of data.
64 bytes from 192.168.122.148: icmp_seq=1 ttl=64 time=0.298 ms
2022-02-17 03:22:26 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=2 ttl=64 time=0.457 ms
2022-02-17 03:22:27 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=3 ttl=64 time=0.468 ms
2022-02-17 03:22:28 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=4 ttl=64 time=0.476 ms
2022-02-17 03:22:29 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.122.148: icmp_seq=5 ttl=64 time=0.308 ms

--- 192.168.122.148 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.298/0.401/0.476/0.082 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:22:38 - sshInstance.py - [line:92] - root - INFO - ssh root@192.168.122.148
root@192.168.122.148's password: 
2022-02-17 03:22:47 - sshInstance.py - [line:92] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Wed 16 Feb 2022 02:32:08 PM EST
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.148
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.13

373 updates can be installed immediately.
239 of these updates are security updates.
To see these additional updates run: apt list --upgradable

Last login: Wed Feb 16 14:27:54 2022 from 192.168.122.1
root@localhost:~# 
2022-02-17 03:22:54 - sshInstance.py - [line:69] - root - INFO - ping -c 5 192.168.10.14
PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.401 ms
2022-02-17 03:22:55 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.251 ms
2022-02-17 03:22:56 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.216 ms
2022-02-17 03:22:57 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.186 ms
2022-02-17 03:22:58 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.124 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.124/0.235/0.401/0.092 ms
root@localhost:~# 
2022-02-17 03:23:38 - sshInstance.py - [line:92] - root - INFO - exit
logout
Connection to 192.168.122.148 closed.
[root@WW25ICX2 ~]# 
2022-02-17 03:23:41 - test_network_sriov_stress.py - [line:466] - root - INFO - ping VMtest2 IP from VMtest1
2022-02-17 03:23:45 - sshInstance.py - [line:69] - root - INFO - ping -c 5 -I 192.168.10.12 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.12 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.260 ms
2022-02-17 03:23:46 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.207 ms
2022-02-17 03:23:47 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.253 ms
2022-02-17 03:23:48 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.252 ms
2022-02-17 03:23:49 - sshInstance.py - [line:69] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.183 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4077ms
rtt min/avg/max/mdev = 0.183/0.231/0.260/0.030 ms
[root@WW25ICX2 ~]# 
2022-02-17 03:23:55 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 03:23:57 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:24:02 - test_network_sriov_stress.py - [line:243] - root - INFO - Successfully removed VFs from PF.
2022-02-17 03:24:05 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-17 03:24:05 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 destroyed


2022-02-17 03:24:10 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-17 03:24:13 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-17 03:24:13 - sshInstance.py - [line:48] - root - INFO - Domain VMtest1 has been undefined


2022-02-17 03:24:18 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-17 03:24:21 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-17 03:24:22 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 destroyed


2022-02-17 03:24:27 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-17 03:24:30 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-17 03:24:30 - sshInstance.py - [line:48] - root - INFO - Domain VMtest2 has been undefined


2022-02-17 03:24:35 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
.2022-02-17 03:24:38 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest2
2022-02-17 03:24:38 - sshInstance.py - [line:48] - root - INFO - 

2022-02-17 03:24:43 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest2
2022-02-17 03:24:46 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest2
2022-02-17 03:24:46 - sshInstance.py - [line:48] - root - INFO - 

2022-02-17 03:24:51 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest2
2022-02-17 03:24:54 - sshInstance.py - [line:44] - root - INFO - virsh destroy VMtest1
2022-02-17 03:24:54 - sshInstance.py - [line:48] - root - INFO - 

2022-02-17 03:24:59 - test_network_sriov_stress.py - [line:258] - root - INFO - Successfully shut down the VM: VMtest1
2022-02-17 03:25:02 - sshInstance.py - [line:44] - root - INFO - virsh undefine VMtest1
2022-02-17 03:25:02 - sshInstance.py - [line:48] - root - INFO - 

2022-02-17 03:25:07 - test_network_sriov_stress.py - [line:268] - root - INFO - Successfully removed the VM: VMtest1
2022-02-17 03:25:10 - sshInstance.py - [line:44] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-02-17 03:25:10 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:25:18 - sshInstance.py - [line:44] - root - INFO - ifconfig ens2f0 0
2022-02-17 03:25:18 - sshInstance.py - [line:48] - root - INFO - 
2022-02-17 03:25:23 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-02-17 03:25:23 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
                  [100%]

=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:38
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:38: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:71
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:71: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:48
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:48: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:87
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:87: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:362
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:362: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:478
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:478: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:776
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:776: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:53
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:53: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:77
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:77: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:99
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:99: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:125
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:125: PytestUnknownMarkWarning: Unknown pytest.mark.drive - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.drive

npxtester/Tests/testNics/test_nics.py:163
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:163: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:187
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:187: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
========== 1 passed, 15 deselected, 13 warnings in 2946.81s (0:49:06) ==========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4Ix6O+hSs/J+WYhicXoVNFsq2LY7NwaGm8aSejP8W5cDAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8BPqPtor0AAAA=[0m[Pipeline] }
[8mha:////4GHchb786wl688erDJjASqsmJ9Hr4hPtHO8ytwYHX0MzAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkMhon14bFL6hQa6F5D9uHMPlF/pr/IJHEyTvdc5bzemOdIo4cnWotdZ5S7VUfBjc/NXLsroFH1fJF1UyJg1WVHStu7GnBisViWZZjpbGxVAdOnpxgq1vzMEUw5IqzxNkdNHLf3PFEpueymChfmCJ2t6FJTL/O3wCmvhfk5V6QlR9NTCl7vQAAAA==[0m[Pipeline] // node
[8mha:////4N3Zwv+i78+NyT5x5Iut/zlc/vu2cqXlCZqUPy9nGyYaAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkMhon14bFL6hQa6F5D9uHMPlF/pr/IJHEyTvdc5bzemOdIo4cnWotdZ5S7VUfBjc/NXLsroFH1fJF1UyJg1WVHStu7GnBisViWZZjpbGxVAdOnpxgq1vzMEUw5IqzxNkdNHLf3PFEpueymChfmCJ2t6FJTL/O3wCmvhfkZSnI9h9rVU4xvQAAAA==[0m[Pipeline] End of Pipeline
Finished: SUCCESS
