Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-simple
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-simple/npxtester
ls: cannot access '/root/.jenkins/workspace/test-test-nic-simple/npxtester': No such file or directory
[8mha:////4MftwC6NxviNjDdpfna9VBlJkoMp8EhRTGL2zcTKdEZ0AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8Brmfz270AAAA=[0m[Pipeline] }
[8mha:////4Kr9K7llyIIfXzIi7fTbyam3A+VyjB0I1hAyH+fEbXLCAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIMlYVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0gL0tBtv8Aj1Msdr0AAAA=[0m[Pipeline] // script
[8mha:////4FI2+bSiptyXTIERd0s3FW0AIUAVzDIQC15QCQE4LYPvAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRFDSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPyRmLRr0AAAA=[0m[Pipeline] }
[8mha:////4EIF7pCgSAhTUJ+YeVF144RCQBElcAy/oq5IQm3P5r/FAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRQlSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPw2Hi4r0AAAA=[0m[Pipeline] // stage
[8mha:////4O65h0jm98EO51SGQmOdf6FpfngMUfFS1Hkxj+qIATCfAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjpHSIitZywwtMYowT6y7YF5KKF/E1/oAhEhVb7ay0mucLyhThQNHJzmLvMTVeDmF0ucmJYn8JNMmOzrIhTBSs1HbS1NrjgprYwhJRwErB2mITKHl0DBvVmbupgkFXnTjmba+g8O0NHiBUNrOJ/IU5wvY6tonw5/krgHlgEDVDsas/x/INoKa7ysEAAAA=[0m[Pipeline] stage
[8mha:////4Cwh2bfnyXtsNeYvUrnMhkgZn3DOCE3ZIocZCmHhDj1kAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUSDAhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD5WQ+PfCAAAA[0m[Pipeline] { (clone)
[8mha:////4CFOXQFtiiA+7tA4CXv18jhcFszpIgsA6m3wBj5vXwoxAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCmgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHN7LjSKW+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4JxnGUheoVbdA4jH7w1zuxcsCY2poKXOhDnLMn7NKJYFAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCkSBqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGOY4V7vgAAAA==[0m[Pipeline] }
[8mha:////4D4+5H4RzROPZTW0wBHD+XjMhoO5mPw9EWUJAbCIJpuGAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiJAokRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g3N4dT9vgAAAA==[0m[Pipeline] // stage
[8mha:////4AJAGqZwaYqyNNZtbc8g6ZE112gHcOMJEUqcQ3uLTkOfAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJBqEqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A361JXbBAAAA[0m[Pipeline] stage
[8mha:////4PP68w9I/uoPNBdRzp82S+tTLGAqcpDjYGyOG/BwZs8HAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycogU2BDqxBp14QShCSFp9H9JUtKJE3E17kCgEhMeLNuS9Z4vqIKHhrxmVmFvMHSGDW7UObFEvr84SszSmXWEgZxirUotSXWca0tRwayihAWHpcLOUTCoI6y4FXdRO4G6PkWftwOH0sgbPKDgmRyFj98yeVhfRxkIf5y/AJiGCOV2n223+TyrN7xWSV3CAAAA[0m[Pipeline] { (set args)
[8mha:////4BsNiMtY/8UtmXAIxp6NV4VtqKiaHUkJeJGRvFkfJcU+AAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICtIgqreWGF5jYGCfWnbEdkooX8TX+QCASFVusdraZ5wuWKcKRo8XWUOcoNQ6D7+20cODYXTwP2PIZG6bE3qA0g2Rt6hklZwNzihIWAlaGGs/Jkc2wFq26q8orstUpx+k7CCidvsEDCjGZs4r5C2OEzbXXienn+SuAMWQo99tP7cIbaOP4NL4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-simple/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-21.02/","sut_conf":{"kernel_type":"generic","board_type":"commerical","host":"10.239.182.209","pf1":"ens785f2","pf1_ipv6":"fe80::42a6:b7ff:fe72:ccca","os":"RHEL","PF1_NIC_type":"4*25"},"sut2_conf":{"host":"10.239.182.79","pf1":"ens787f2","pf1_ipv6":"fe80::42a6:b7ff:fe82:eb6"},"drive_info":{"drive_version":"1.7.11"}}'
[8mha:////4AyFPX+UZcZf/6aTNXdj+lWE0Z2b4chbTZ9e7eCHFoeRAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKC0iIqWisNLzCJMXasO8d2cCpexNf4A4FIVGyx2tlmni9YxwBHDhqtot5QbA16N+p5YebQXx1ntHzBlimyU9io3HCnTgs2nBQsKUpYCdgoah1HQzrBVlh5l5WTpKtzCvN3EFCaboAHFGI2JxnSF6YAu9vYRaaf568AJu8TlHX9qf0b7E/nQb4AAAA=[0m[Pipeline] }
[8mha:////4AFg/aWh/jHSmrlH6sy1kKjz0TFBfVRN+miPQW2LyX/uAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcrdPtf28AEud0rYvgAAAA==[0m[Pipeline] // stage
[8mha:////4Bhd+KV1EsVM3bnXBHnMClLv0EnBj/3vPQbr+7HWEbmAAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjoXSIitZywwtMYowT6y7YF5KKF/E1/oAhEhVb7ay0mucLyhThQNHJzmLvMTVeDmF0ucmJYn8JNMmOzrIhTBSs1HbS1NrjgprYwhJRwErB2mITKHl0DBvVmbupgkFXnTjmba+g8O0NHiBUNrOJ/IU5wvY6tonw5/krgHlgEDVDsas/x/INPbxT+8EAAAA=[0m[Pipeline] stage
[8mha:////4P13TIuP26wSoF8WyLGiU1qV0Q6Z+QylTska1uSfBb7mAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUQjAhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD/hYjrHCAAAA[0m[Pipeline] { (run nic case)
[8mha:////4FM3oozjxgRBqafqHchkdSyZ1a7wU/MTBVKRbtZrSwmtAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiIUGDqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAEIWoEpvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics -s -m nicSimple --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_simple_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 9 deselected / 7 selected

npxtester/Tests/testNics/test_mtu.py 2022-03-04 09:42:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-04 09:42:56 - test_mtu.py - [line:18] - root - INFO - this is Test_mtu setup.
E2022-03-04 09:43:26 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-04 09:43:26 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-03-04 09:43:26 - test_mtu.py - [line:18] - root - INFO - this is Test_mtu setup.
E2022-03-04 09:43:56 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 28%]
npxtester/Tests/testNics/test_nics.py 2022-03-04 09:43:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-03-04 09:43:56 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
E2022-03-04 09:44:26 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-03-04 09:44:26 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-03-04 09:44:26 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
E2022-03-04 09:44:56 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_silver_ConnectivityReboot case ============================
2022-03-04 09:44:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-04 09:44:56 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 09:44:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:44:56 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:44:56 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
E2022-03-04 09:45:26 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-04 09:45:26 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_InternetProtocolv4v6_CVL case ============================
2022-03-04 09:45:26 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 09:45:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:45:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:45:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
E2022-03-04 09:45:56 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_InternetProtocolv4v6_CVL case ============================
2022-03-04 09:45:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_Link_State_Check_CVL case ============================
2022-03-04 09:45:56 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 09:45:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:45:56 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:45:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-03-04 09:45:57 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:45:57 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:45:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.79
2022-03-04 09:45:57 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 09:46:00 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 09:46:00 - sshInstance.py - [line:50] - root - INFO - version:        1.7.11

2022-03-04 09:46:08 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 09:46:18 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 09:46:26 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 09:46:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 09:46:39 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 09:46:39 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-193.19.1.rt13.70.el8_2.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.7.11
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.2
srcversion:     4AE55166A76503F69ADCE95
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        auxiliary
name:           ice
vermagic:       4.18.0-193.19.1.rt13.70.el8_2.x86_64 SMP preempt mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 09:46:47 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-21.02/usertools/dpdk-devbind.py -s | grep ens785f2 | awk '{print $1;}'
2022-03-04 09:46:48 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.2

2022-03-04 09:46:56 - sshInstance.py - [line:46] - root - INFO - lspci -vvs 00:4b:00.2 | grep LnkCap:
2022-03-04 09:46:56 - sshInstance.py - [line:50] - root - INFO - 		LnkCap:	Port #0, Speed 16GT/s, Width x16, ASPM not supported

2022-03-04 09:47:04 - sshInstance.py - [line:46] - root - INFO - lspci -vvs 00:4b:00.2 | grep LnkSta:
2022-03-04 09:47:04 - sshInstance.py - [line:50] - root - INFO - 		LnkSta:	Speed 16GT/s, Width x16, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-

2022-03-04 09:47:09 - test_nics.py - [line:230] - root - INFO - speed and width value is current
.2022-03-04 09:47:12 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 09:47:12 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 09:47:20 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 09:47:20 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 09:47:28 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 09:47:28 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 09:47:33 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:47:33 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:47:33 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
2022-03-04 09:47:33 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 09:47:36 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 09:47:36 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 09:47:44 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 09:47:44 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 09:47:52 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 09:47:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 09:47:57 - test_nics.py - [line:68] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 09:47:57 - test_nics.py - [line:70] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_PI_Networking_Link_State_Check_CVL_09_45_56
2022-03-04 09:48:00 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 09:48:00 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 09:48:05 - test_nics.py - [line:72] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 09:48:05 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-04 09:48:05 - test_nics.py - [line:74] - root - INFO - this is Test_Nics teardown
2022-03-04 09:48:05 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_Link_State_Check_CVL case ============================
                              [100%]

==================================== ERRORS ====================================
________ ERROR at setup of Test_mtu.test_PI_Networking_Jumbo_Packet_CVL ________

self = <Tests.testNics.test_mtu.Test_mtu object at 0x7f8b904fd828>

    def setup(self):
        logging.info("this is Test_mtu setup.")
        self.sut_conf = settings.__getattribute__("sut_conf")
        self.sut2_conf = settings.__getattribute__("sut2_conf")
        self.check_str = settings.__getattribute__("check_str")
        self.drive_info = settings.__getattribute__("drive_info")
        self.cn_test_sut = sshInstance()
        self.sut1_cli, self.sut1_session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
>                                                      self.sut_conf["password"], self.sut_conf["port"])

npxtester/Tests/testNics/test_mtu.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
npxtester/libs/commons/sshInstance.py:25: in get_ssh_instance
    client.connect(hostname=hostname, port=port, username=username, password=password, timeout=30)
/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/site-packages/paramiko/util.py:283: in retry_on_signal
    return function()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   retry_on_signal(lambda: sock.connect(addr))
E   socket.timeout: timed out

/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: timeout
---------------------------- Captured stdout setup -----------------------------
2022-03-04 09:42:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-04 09:42:56 - test_mtu.py - [line:18] - root - INFO - this is Test_mtu setup.
__________ ERROR at setup of Test_mtu.test_PI_Networking_MTU_set_CVL ___________

self = <Tests.testNics.test_mtu.Test_mtu object at 0x7f8b9068a208>

    def setup(self):
        logging.info("this is Test_mtu setup.")
        self.sut_conf = settings.__getattribute__("sut_conf")
        self.sut2_conf = settings.__getattribute__("sut2_conf")
        self.check_str = settings.__getattribute__("check_str")
        self.drive_info = settings.__getattribute__("drive_info")
        self.cn_test_sut = sshInstance()
        self.sut1_cli, self.sut1_session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
>                                                      self.sut_conf["password"], self.sut_conf["port"])

npxtester/Tests/testNics/test_mtu.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
npxtester/libs/commons/sshInstance.py:25: in get_ssh_instance
    client.connect(hostname=hostname, port=port, username=username, password=password, timeout=30)
/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/site-packages/paramiko/util.py:283: in retry_on_signal
    return function()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   retry_on_signal(lambda: sock.connect(addr))
E   socket.timeout: timed out

/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: timeout
---------------------------- Captured stdout setup -----------------------------
2022-03-04 09:43:26 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-03-04 09:43:26 - test_mtu.py - [line:18] - root - INFO - this is Test_mtu setup.
_ ERROR at setup of Test_Nics.test_silver_Networking_ConnectivityEnableDisable _

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f8b941a7b70>

    def setup(self):
        logging.info("this is Test_Nics setup.")
        self.sut_conf = settings.__getattribute__("sut_conf")
        self.sut2_conf = settings.__getattribute__("sut2_conf")
        self.drive_info = settings.__getattribute__("drive_info")
        self.dhcp = settings.__getattribute__("dhcp")
        self.check_str = settings.__getattribute__("check_str")
        self.dpdk_dir = settings.__getattribute__("dpdk_dir")
        self.cn_test_sut = sshInstance()
        self.client, self.session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
>                                                      self.sut_conf["password"], self.sut_conf["port"])

npxtester/Tests/testNics/test_nics.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
npxtester/libs/commons/sshInstance.py:25: in get_ssh_instance
    client.connect(hostname=hostname, port=port, username=username, password=password, timeout=30)
/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/site-packages/paramiko/util.py:283: in retry_on_signal
    return function()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   retry_on_signal(lambda: sock.connect(addr))
E   socket.timeout: timed out

/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: timeout
---------------------------- Captured stdout setup -----------------------------
2022-03-04 09:43:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-03-04 09:43:56 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
__________ ERROR at setup of Test_Nics.test_silver_ConnectivityReboot __________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f8b905d1c88>

    def setup(self):
        logging.info("this is Test_Nics setup.")
        self.sut_conf = settings.__getattribute__("sut_conf")
        self.sut2_conf = settings.__getattribute__("sut2_conf")
        self.drive_info = settings.__getattribute__("drive_info")
        self.dhcp = settings.__getattribute__("dhcp")
        self.check_str = settings.__getattribute__("check_str")
        self.dpdk_dir = settings.__getattribute__("dpdk_dir")
        self.cn_test_sut = sshInstance()
        self.client, self.session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
>                                                      self.sut_conf["password"], self.sut_conf["port"])

npxtester/Tests/testNics/test_nics.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
npxtester/libs/commons/sshInstance.py:25: in get_ssh_instance
    client.connect(hostname=hostname, port=port, username=username, password=password, timeout=30)
/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/site-packages/paramiko/util.py:283: in retry_on_signal
    return function()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   retry_on_signal(lambda: sock.connect(addr))
E   socket.timeout: timed out

/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: timeout
---------------------------- Captured stdout setup -----------------------------
2022-03-04 09:44:26 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-03-04 09:44:26 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
____ ERROR at setup of Test_Nics.test_gold_PI_Networking_SRIOV_CheckDevice _____

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f8b906ae6a0>

    def setup(self):
        logging.info("this is Test_Nics setup.")
        self.sut_conf = settings.__getattribute__("sut_conf")
        self.sut2_conf = settings.__getattribute__("sut2_conf")
        self.drive_info = settings.__getattribute__("drive_info")
        self.dhcp = settings.__getattribute__("dhcp")
        self.check_str = settings.__getattribute__("check_str")
        self.dpdk_dir = settings.__getattribute__("dpdk_dir")
        self.cn_test_sut = sshInstance()
        self.client, self.session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
                                                       self.sut_conf["password"], self.sut_conf["port"])
        self.client2, self.session2 = self.cn_test_sut.get_ssh_instance(self.sut2_conf["host"], self.sut2_conf["user"],
>                                                      self.sut2_conf["password"], self.sut2_conf["port"])

npxtester/Tests/testNics/test_nics.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
npxtester/libs/commons/sshInstance.py:25: in get_ssh_instance
    client.connect(hostname=hostname, port=port, username=username, password=password, timeout=30)
/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/site-packages/paramiko/util.py:283: in retry_on_signal
    return function()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   retry_on_signal(lambda: sock.connect(addr))
E   socket.timeout: timed out

/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: timeout
---------------------------- Captured stdout setup -----------------------------
2022-03-04 09:44:56 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-04 09:44:56 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 09:44:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:44:56 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:44:56 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
___ ERROR at setup of Test_Nics.test_PI_Networking_InternetProtocolv4v6_CVL ____

self = <Tests.testNics.test_nics.Test_Nics object at 0x7f8b906ae1d0>

    def setup(self):
        logging.info("this is Test_Nics setup.")
        self.sut_conf = settings.__getattribute__("sut_conf")
        self.sut2_conf = settings.__getattribute__("sut2_conf")
        self.drive_info = settings.__getattribute__("drive_info")
        self.dhcp = settings.__getattribute__("dhcp")
        self.check_str = settings.__getattribute__("check_str")
        self.dpdk_dir = settings.__getattribute__("dpdk_dir")
        self.cn_test_sut = sshInstance()
        self.client, self.session = self.cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
                                                       self.sut_conf["password"], self.sut_conf["port"])
        self.client2, self.session2 = self.cn_test_sut.get_ssh_instance(self.sut2_conf["host"], self.sut2_conf["user"],
>                                                      self.sut2_conf["password"], self.sut2_conf["port"])

npxtester/Tests/testNics/test_nics.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
npxtester/libs/commons/sshInstance.py:25: in get_ssh_instance
    client.connect(hostname=hostname, port=port, username=username, password=password, timeout=30)
/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: in connect
    retry_on_signal(lambda: sock.connect(addr))
/usr/local/lib/python3.6/site-packages/paramiko/util.py:283: in retry_on_signal
    return function()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   retry_on_signal(lambda: sock.connect(addr))
E   socket.timeout: timed out

/usr/local/lib/python3.6/site-packages/paramiko/client.py:349: timeout
---------------------------- Captured stdout setup -----------------------------
2022-03-04 09:45:26 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_InternetProtocolv4v6_CVL case ============================
2022-03-04 09:45:26 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 09:45:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 09:45:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 09:45:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.209
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:62
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:62: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:101
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:101: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:71
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:71: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:381
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:381: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:498
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:498: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:797
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:797: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:78
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:78: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:102
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:102: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:124
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:124: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:188
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:188: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:212
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:212: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_simple_report.html -
=========================== short test summary info ============================
ERROR npxtester/Tests/testNics/test_mtu.py::Test_mtu::test_PI_Networking_Jumbo_Packet_CVL
ERROR npxtester/Tests/testNics/test_mtu.py::Test_mtu::test_PI_Networking_MTU_set_CVL
ERROR npxtester/Tests/testNics/test_nics.py::Test_Nics::test_silver_Networking_ConnectivityEnableDisable
ERROR npxtester/Tests/testNics/test_nics.py::Test_Nics::test_silver_ConnectivityReboot
ERROR npxtester/Tests/testNics/test_nics.py::Test_Nics::test_gold_PI_Networking_SRIOV_CheckDevice
ERROR npxtester/Tests/testNics/test_nics.py::Test_Nics::test_PI_Networking_InternetProtocolv4v6_CVL
====== 1 passed, 9 deselected, 12 warnings, 6 errors in 309.65s (0:05:09) ======
[8mha:////4JadWPtzQEFx9CzixTlssp2D6uuorSv3wnTa6h1wuGrmAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiISEKRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g3QKkBhvgAAAA==[0m[Pipeline] }
[8mha:////4Goa9rseL6gCK8+j51lIjOVJAeE64BF71YmRtb4KtKxFAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiIQokRJXWcsMLTGyME+vO2A5JxYv4Gn8gEImKLVY728zzBcsU4cjRYmuoc5Qah8H3dlo4cOwungds+YwNU2JvUJpBsjb1jJKzgTlFCQsBK0ON5+TIZliLVt1V5RXZ6pTj9B0ElE7f4AGFmMxZxfyFMcLm2uvE9PP8FcAYQoZyu//U7g2TqBHnvgAAAA==[0m[Pipeline] // stage
[8mha:////4AK444efjkykafC1HGbgxn6nPSQkL/HNauaXETS7R91oAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIRqEqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A+OvzUfBAAAA[0m[Pipeline] stage
[8mha:////4EqpMgzslAWPDRl1bp4feAKRfPoiBNazp8uDBURuqJGsAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycogUwYRQJ9aoCycITQhJo/9LkpJOnIircQcClZjwYNmWrPd8QRU8NOQ1swp7g6EzbHCjzokl8v3FUWKWzqwjDOQUa1VqSarjXFuKCmYVJSw4LBV2joJBHWHFrbiL2gnU9Sn6vB04lEbe4AEFz+QofPyWycP6OspA+OP8BcA0RCi3+2y7zedZvQH4j6CMwgAAAA==[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4M0P44+7KKMsBaEAgOPFTC6kJ9gOLfRk2xH1/27GZQUTAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICokRUaS03vMDExjix7oztkFS8iK/xBwKRqNhitbPNPF+wTBGOHC22hjpHqXEYfG+nhQPH7uJ5wJbP2DAl9galGSRrU88oORuYU5SwELAy1HhOjmyGtWjVXVVeka1OOU7fQUDp9A0eUIjJnFXMXxgjbK69Tkw/z18BjCFkKPe7T23ftwcfeL4AAAA=[0m[Pipeline] }
[8mha:////4ME5TlbHmzr5qdpFH/mkGWKP7XmPx2rIKtfLHFMqug00AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAczeJyj3da768AH8/EyevgAAAA==[0m[Pipeline] // stage
[8mha:////4Fe3eqQpZrcpnjrK1jN1d/MbMZ7ufuA8IOyekGcoBhh7AAAAoh+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIU2DlWthkaTxAhxkBmF5NFqDyRV/MOMjJj5a/+e817vbFOEUeOTrWWOk+p9qoPg5ufGjl218CjavmiaqbEwarKjhU39rRgxWKxLMux0thYqgMnT06w1a15mCIYcsVZ4uwOGrlv7ngi03NZTJQvTBG729Akpl/nbwBT3wvyshRk+w9e8C3YvQAAAA==[0m[Pipeline] }
[8mha:////4Fl8XDDe7BXdXsXj7uDbwTY/cDAcq+nOEdlmagh5XH3DAAAAoh+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIU2DlWthkaTxAhxkBmF5NFqDyRV/MOMjJj5a/+e817vbFOEUeOTrWWOk+p9qoPg5ufGjl218CjavmiaqbEwarKjhU39rRgxWKxLMux0thYqgMnT06w1a15mCIYcsVZ4uwOGrlv7ngi03NZTJQvTBG729Akpl/nbwBT3wvyci/Iyg/tuWn0vQAAAA==[0m[Pipeline] // node
[8mha:////4Oc/DLR66YI1esGEMsMY02BciEZxcpD10WBUR6yLP96pAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRQFSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLcXZNsPy6AOvr0AAAA=[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
