Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/spr-test-nicGold
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/spr-test-nicGold/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/spr-test-nicGold/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/spr-test-nicGold/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"4.18.0-369.el8.x86_64"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-22.03","vm_image_conf":{"image1":"rhel86.img","image2":"rhel862.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.239.182.80","pf1":"ens43f0","os":"RHEL"},"pkg_generator":{"host":"10.239.182.88","pf1":"ens785f0"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4Dqouna/UALz1cds/DYDIib12lRO4R4U9QQgmUx/wyv5AAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgEJMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAnLfKUwgAAAA==[0m[Pipeline] script
[8mha:////4JUhH4fIWh5icAEY6zBr3HRHHu0lnMalVyM2fPsu3/3sAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgIhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD0QKVszCAAAA[0m[Pipeline] {
[8mha:////4PJRxj8hD/CuSHgtWDRwAQ67XTdBRcldvWih24U4ysBWAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCoEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AHN/bm5vgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics -s -m nicGold --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nicGold_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 19 items / 15 deselected / 4 selected

npxtester/Tests/testNics/test_mtu.py 2022-04-18 06:22:58 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_Jumbo_Packet_CVL_06_22_58/test_PI_Networking_Jumbo_Packet_CVL.log, case_logdir: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_Jumbo_Packet_CVL_06_22_58
2022-04-18 06:22:58 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-04-18 06:22:58 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-04-18 06:22:58 - test_mtu.py - [line:22] - root - INFO - ssh to the sut1
2022-04-18 06:22:58 - test_mtu.py - [line:24] - root - INFO - ssh to the sut1
2022-04-18 06:22:58 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:22:58 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:22:58 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.80
2022-04-18 06:22:58 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:22:58 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:22:58 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-04-18 06:22:58 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-18 06:22:58 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-18 06:23:01 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-18 06:23:01 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:23:06 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-18 06:23:06 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-18 06:23:09 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-18 06:23:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:23:25 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-18 06:23:25 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-18 06:23:28 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-18 06:24:04 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:24:09 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-18 06:24:12 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens43f0
2022-04-18 06:24:12 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 4.18.0-369.el8.x86_64
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:98:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-18 06:24:20 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0 mtu 1500
2022-04-18 06:24:20 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:24:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 1500
2022-04-18 06:24:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:24:36 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0
2022-04-18 06:24:36 - sshInstance.py - [line:54] - root - INFO - ens43f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::abb2:4a56:6a65:c232  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:20:d8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13  bytes 2130 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:24:45 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Mon Apr 18 06:35:50 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | We are in France, we say Skappee.[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | OK? Merci.[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |             -- Sebastien Chabal[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-04-18 06:24:52 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:20:d8")/IP(len=46)/Raw(load='X'*14480)],iface="ens785f0")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-04-18 06:24:55 - test_mtu.py - [line:92] - root - INFO - success to send package to network
2022-04-18 06:24:59 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:20:d8")/IP(len=46)/Raw(load='X'*15500)],iface="ens785f0")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-04-18 06:25:02 - test_mtu.py - [line:102] - root - INFO - result is right
.2022-04-18 06:25:05 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0 mtu 1500
2022-04-18 06:25:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:25:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 1500
2022-04-18 06:25:13 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:25:21 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:25:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:25:29 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-18 06:25:29 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:25:34 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-18 06:25:35 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-18/test_PI_Networking_Jumbo_Packet_CVL_06_22_58
2022-04-18 06:25:38 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-18 06:25:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:25:43 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-18 06:25:43 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-04-18 06:25:43 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-04-18 06:25:43 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_MTU_set_CVL_06_25_43/test_PI_Networking_MTU_set_CVL.log, case_logdir: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_MTU_set_CVL_06_25_43
2022-04-18 06:25:43 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-04-18 06:25:43 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-04-18 06:25:43 - test_mtu.py - [line:22] - root - INFO - ssh to the sut1
2022-04-18 06:25:43 - test_mtu.py - [line:24] - root - INFO - ssh to the sut1
2022-04-18 06:25:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:25:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:25:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.80
2022-04-18 06:25:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:25:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:25:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-04-18 06:25:43 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-18 06:25:43 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-18 06:25:46 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-18 06:25:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:25:51 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-18 06:25:51 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-18 06:25:54 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-18 06:26:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:26:10 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-18 06:26:10 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-18 06:26:13 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-18 06:26:49 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:26:54 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-18 06:26:57 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens43f0
2022-04-18 06:26:57 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 4.18.0-369.el8.x86_64
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:98:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-18 06:27:05 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0 mtu 1500
2022-04-18 06:27:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:27:13 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 2000
2022-04-18 06:27:17 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:27:25 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0
2022-04-18 06:27:25 - sshInstance.py - [line:54] - root - INFO - ens43f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::abb2:4a56:6a65:c232  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:20:d8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 2895 (2.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:27:34 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Mon Apr 18 06:38:55 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Craft me if you can.[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   |                   -- IPv6 layer[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-04-18 06:27:41 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:20:d8")/IP(len=46)/Raw(load='X'*18890)],iface="ens785f0")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-04-18 06:27:44 - test_mtu.py - [line:132] - root - INFO - success to send package to network
2022-04-18 06:27:48 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:20:d8")/IP(len=46)/Raw(load='X'*20010)],iface="ens785f0")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-04-18 06:27:51 - test_mtu.py - [line:142] - root - INFO - result is right
.2022-04-18 06:27:54 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0 mtu 1500
2022-04-18 06:27:54 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:02 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 1500
2022-04-18 06:28:06 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:14 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:28:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:22 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-18 06:28:22 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:27 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-18 06:28:27 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-18/test_PI_Networking_MTU_set_CVL_06_25_43
2022-04-18 06:28:30 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-18 06:28:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:35 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-18 06:28:35 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-04-18 06:28:35 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 50%]
npxtester/Tests/testNics/test_network_sriov_stress.py 2022-04-18 06:28:35 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-04-18 06:28:35 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img]_06_28_35/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img].log, case_logdir: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img]_06_28_35
2022-04-18 06:28:35 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img] case ============================
2022-04-18 06:28:35 - test_network_sriov_stress.py - [line:32] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-04-18 06:28:35 - test_network_sriov_stress.py - [line:50] - root - INFO - ssh to the sut1
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:28:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.80
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:28:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-04-18 06:28:35 - test_network_sriov_stress.py - [line:64] - root - INFO - clean up iperf and taskset process...
2022-04-18 06:28:38 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-18 06:28:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:46 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-18 06:28:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:54 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-18 06:28:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:03 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-18 06:29:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:08 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 3] Opened sftp connection (server version 3)
2022-04-18 06:29:08 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-18 06:29:11 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-18 06:29:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:16 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-18 06:29:16 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-18 06:29:19 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-18 06:29:29 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:34 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-18 06:29:34 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-18 06:29:38 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-18 06:30:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:30:19 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-18 06:30:22 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens43f0
2022-04-18 06:30:22 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 4.18.0-369.el8.x86_64
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:98:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-18 06:30:27 - test_network_sriov_stress.py - [line:72] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-18 06:30:27 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0:
2022-04-18 06:30:30 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0
2022-04-18 06:30:30 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0' (18e7cccf-fb4c-40f2-960c-d7e2b0b15d06) successfully deleted.

2022-04-18 06:30:35 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:30:38 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:30:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:30:43 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0:
2022-04-18 06:30:46 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0 ifname ens43f0
2022-04-18 06:30:46 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0' (032e2133-1fcb-4054-a9e5-fcacd106aff3) successfully added.

2022-04-18 06:30:51 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:30:54 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:30:54 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:30:59 - test_network_sriov_stress.py - [line:79] - root - INFO - trying to get ipv6 addr for pf1
2022-04-18 06:31:02 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0
2022-04-18 06:31:02 - sshInstance.py - [line:54] - root - INFO - ens43f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::aac6:502c:14ca:edbc  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:20:d8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 3454 (3.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:31:10 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-04-18 06:31:10 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 11902775582  bytes 18020192935675 (16.3 TiB)
        RX errors 0  dropped 943  overruns 0  frame 0
        TX packets 484835901  bytes 36210431058 (33.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:31:15 - test_network_sriov_stress.py - [line:585] - root - INFO - 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

2022-04-18 06:31:18 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -s | grep ens43f0 | awk '{print $1;}'
2022-04-18 06:31:19 - sshInstance.py - [line:54] - root - INFO - 0000:98:00.0

2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:130] - root - INFO - pf_id was found: 0000:98:00.0

2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:593] - root - INFO - format_pf_id is 0000\:98\:00.0

2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:596] - root - INFO - pf_id_key: 98
2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:600] - root - INFO - start to assign ip for ens43f0 of SUT1: 192.168.10.10
2022-04-18 06:31:30 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Apr 18 06:42:14 2022 from 10.112.97.60
[root@npx-auto-SPR-quanta ~]# ifconfig ens43f0 192.168.10.10
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:31:33 - test_network_sriov_stress.py - [line:333] - root - INFO - Successfully assigned ip to ethernet: ens43f0
2022-04-18 06:31:33 - test_network_sriov_stress.py - [line:602] - root - INFO - start to assign ip for ens785f0 of SUT2: 192.168.10.11
2022-04-18 06:31:39 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Apr 18 06:41:44 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-04-18 06:31:42 - test_network_sriov_stress.py - [line:333] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-04-18 06:31:42 - test_network_sriov_stress.py - [line:136] - root - INFO - virtulize sut1 pf to 4 vfs
2022-04-18 06:31:45 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:31:49 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:31:54 - test_network_sriov_stress.py - [line:145] - root - INFO - Successfully Virtualized PF to VFs.
2022-04-18 06:31:57 - sshInstance.py - [line:50] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-04-18 06:31:57 - sshInstance.py - [line:54] - root - INFO - 98:01.0
98:01.1
98:01.2
98:01.3

2022-04-18 06:32:02 - test_network_sriov_stress.py - [line:159] - root - INFO - Succssfully Gotten vf_id list:

2022-04-18 06:32:05 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-04-18 06:32:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:32:10 - test_network_sriov_stress.py - [line:179] - root - INFO - start to bind drive in sut1
2022-04-18 06:32:13 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -b vfio-pci 98:01.0
2022-04-18 06:32:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:32:21 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-18 06:32:24 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -b vfio-pci 98:01.1
2022-04-18 06:32:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:32:32 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-18 06:32:32 - test_network_sriov_stress.py - [line:620] - root - INFO - lspci -Dnn | grep 98:01.1
2022-04-18 06:32:35 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 98:01.1
2022-04-18 06:32:35 - sshInstance.py - [line:54] - root - INFO - 0000:98:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-04-18 06:32:40 - test_network_sriov_stress.py - [line:632] - root - INFO - Successfully get vf device id: 8086:1889
2022-04-18 06:32:40 - test_network_sriov_stress.py - [line:216] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-18 06:32:43 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-18 06:32:43 - sshInstance.py - [line:54] - root - INFO - yes

2022-04-18 06:32:48 - test_network_sriov_stress.py - [line:219] - root - INFO - Default network is active? yes

2022-04-18 06:32:48 - test_network_sriov_stress.py - [line:645] - root - INFO - start to create VMs....
2022-04-18 06:32:48 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-18 06:32:52 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
2022-04-18 06:32:53 - sshInstance.py - [line:75] - root - INFO - ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:32:56 - test_network_sriov_stress.py - [line:256] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:32:56 - test_network_sriov_stress.py - [line:257] - root - INFO - Failed to create a VM: 
2022-04-18 06:32:56 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-18 06:33:00 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
2022-04-18 06:33:02 - sshInstance.py - [line:75] - root - INFO - ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:05 - test_network_sriov_stress.py - [line:256] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:05 - test_network_sriov_stress.py - [line:257] - root - INFO - Failed to create a VM: 
2022-04-18 06:33:05 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-18 06:33:09 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
2022-04-18 06:33:10 - sshInstance.py - [line:75] - root - INFO - ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:256] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:257] - root - INFO - Failed to create a VM: 
2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:265] - root - ERROR - Failed to create a VM: VMtest1)
F2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:91] - root - INFO - removing VMs: VMtest1, VMtest2
2022-04-18 06:33:16 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest2
2022-04-18 06:33:16 - sshInstance.py - [line:54] - root - INFO - error: Failed to destroy domain 'VMtest2'
error: Requested operation is not valid: domain is not running


2022-04-18 06:33:21 - test_network_sriov_stress.py - [line:310] - root - ERROR - Failed to shut down the VM VMtest2
2022-04-18 06:33:24 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest1
2022-04-18 06:33:24 - sshInstance.py - [line:54] - root - INFO - error: Failed to destroy domain 'VMtest1'
error: Requested operation is not valid: domain is not running


2022-04-18 06:33:29 - test_network_sriov_stress.py - [line:310] - root - ERROR - Failed to shut down the VM VMtest1
2022-04-18 06:33:32 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:33:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:33:46 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0 0
2022-04-18 06:33:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:33:54 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 0
2022-04-18 06:33:54 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:34:02 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-18 06:34:02 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:34:07 - test_network_sriov_stress.py - [line:100] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-18 06:34:07 - test_network_sriov_stress.py - [line:102] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-18/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img]_06_28_35
2022-04-18 06:34:10 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-18 06:34:10 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:34:15 - test_network_sriov_stress.py - [line:104] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-18 06:34:18 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/*.txt
2022-04-18 06:34:18 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:34:23 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-18 06:34:23 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img] case ============================
                  [ 75%]
npxtester/Tests/testNics/test_nics.py 2022-04-18 06:34:23 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-04-18 06:34:23 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-18/test_gold_PI_Networking_SRIOV_CheckDevice_06_34_23/test_gold_PI_Networking_SRIOV_CheckDevice.log, case_logdir: /root/testconfig/testlogs/2022-04-18/test_gold_PI_Networking_SRIOV_CheckDevice_06_34_23
2022-04-18 06:34:23 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-04-18 06:34:23 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-04-18 06:34:23 - test_nics.py - [line:28] - root - INFO - ssh to the sut1
2022-04-18 06:34:23 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:34:23 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:34:24 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.80
2022-04-18 06:34:24 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:34:24 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:34:24 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-04-18 06:34:24 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-04-18 06:34:24 - test_nics.py - [line:43] - root - INFO - --Start rmmod irdma --
2022-04-18 06:34:24 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-18 06:34:27 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-18 06:34:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:34:32 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-18 06:34:32 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-18 06:34:35 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-18 06:34:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:34:51 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-18 06:34:51 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-18 06:34:54 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-18 06:35:30 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:35:35 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-18 06:35:38 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens43f0
2022-04-18 06:35:38 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 4.18.0-369.el8.x86_64
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:98:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-18 06:35:43 - test_nics.py - [line:47] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-18 06:35:43 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0:
2022-04-18 06:35:46 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0
2022-04-18 06:35:46 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0' (032e2133-1fcb-4054-a9e5-fcacd106aff3) successfully deleted.

2022-04-18 06:35:51 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:35:54 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:35:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:36:00 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0:
2022-04-18 06:36:03 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0 ifname ens43f0
2022-04-18 06:36:03 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0' (03a4b2af-a974-41f2-a2aa-4483d42d42a9) successfully added.

2022-04-18 06:36:08 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:36:11 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:36:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:36:16 - test_nics.py - [line:53] - root - INFO - --Finish modprobe iavf --
2022-04-18 06:36:19 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0
2022-04-18 06:36:19 - sshInstance.py - [line:54] - root - INFO - ens43f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fe97:9880:2c46:73f0  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:20:d8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 35  bytes 6168 (6.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:36:27 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-04-18 06:36:27 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 11902775636  bytes 18020192945550 (16.3 TiB)
        RX errors 0  dropped 953  overruns 0  frame 0
        TX packets 484835914  bytes 36210433660 (33.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:36:35 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:36:39 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:36:52 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 192.168.10.11

2022-04-18 06:36:52 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:36:57 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v0:
2022-04-18 06:37:00 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v0
2022-04-18 06:37:00 - sshInstance.py - [line:54] - root - INFO - Error: unknown connection 'ens43f0v0'.
Error: cannot delete unknown connection(s): 'ens43f0v0'.

2022-04-18 06:37:05 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:37:08 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:37:08 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:37:13 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0v0:
2022-04-18 06:37:16 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0v0 ifname ens43f0v0
2022-04-18 06:37:16 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v0' (a62035ab-a118-4276-bd57-727226e59e20) successfully added.

2022-04-18 06:37:21 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:37:24 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:37:25 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:37:33 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v0 192.168.10.12
2022-04-18 06:37:33 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:37:44 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.12
2022-04-18 06:37:48 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.375 ms
64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.139 ms
64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.136 ms
64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.135 ms
64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.137 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.135/0.184/0.375/0.096 ms

2022-04-18 06:37:56 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v0 | grep inet6
2022-04-18 06:37:56 - sshInstance.py - [line:54] - root - INFO -         inet6 fe80::cce0:1ea:4842:f6f7  prefixlen 64  scopeid 0x20<link>

2022-04-18 06:38:04 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens43f0v0 fe80::b696:91ff:fea0:2170
2022-04-18 06:38:08 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than ens43f0v0.
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens43f0v0: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v0: icmp_seq=1 ttl=64 time=0.362 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v0: icmp_seq=2 ttl=64 time=0.149 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v0: icmp_seq=3 ttl=64 time=0.140 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v0: icmp_seq=4 ttl=64 time=0.143 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v0: icmp_seq=5 ttl=64 time=0.140 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4129ms
rtt min/avg/max/mdev = 0.140/0.186/0.362/0.089 ms

2022-04-18 06:38:13 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v1:
2022-04-18 06:38:16 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v1
2022-04-18 06:38:16 - sshInstance.py - [line:54] - root - INFO - Error: unknown connection 'ens43f0v1'.
Error: cannot delete unknown connection(s): 'ens43f0v1'.

2022-04-18 06:38:21 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:38:24 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:38:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:38:29 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0v1:
2022-04-18 06:38:32 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0v1 ifname ens43f0v1
2022-04-18 06:38:32 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v1' (f237be46-84a7-4961-9b6a-51ad334c87cf) successfully added.

2022-04-18 06:38:37 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:38:40 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:38:40 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:38:48 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v1 192.168.10.13
2022-04-18 06:38:49 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:39:00 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.13
2022-04-18 06:39:04 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.314 ms
64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.159 ms
64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.147 ms
64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.154 ms
64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.151 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4106ms
rtt min/avg/max/mdev = 0.147/0.185/0.314/0.064 ms

2022-04-18 06:39:12 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v1 | grep inet6
2022-04-18 06:39:12 - sshInstance.py - [line:54] - root - INFO -         inet6 fe80::b4e4:2027:e9ee:f1f4  prefixlen 64  scopeid 0x20<link>

2022-04-18 06:39:20 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens43f0v1 fe80::b696:91ff:fea0:2170
2022-04-18 06:39:24 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than ens43f0v1.
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens43f0v1: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v1: icmp_seq=1 ttl=64 time=0.402 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v1: icmp_seq=2 ttl=64 time=0.145 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v1: icmp_seq=3 ttl=64 time=0.142 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v1: icmp_seq=4 ttl=64 time=0.139 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v1: icmp_seq=5 ttl=64 time=0.144 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4129ms
rtt min/avg/max/mdev = 0.139/0.194/0.402/0.104 ms

2022-04-18 06:39:29 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v2:
2022-04-18 06:39:32 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v2
2022-04-18 06:39:32 - sshInstance.py - [line:54] - root - INFO - Error: unknown connection 'ens43f0v2'.
Error: cannot delete unknown connection(s): 'ens43f0v2'.

2022-04-18 06:39:37 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:39:40 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:39:40 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:39:45 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0v2:
2022-04-18 06:39:48 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0v2 ifname ens43f0v2
2022-04-18 06:39:48 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v2' (b319a7e3-c4d8-4e79-a71a-fbca18b5e4c8) successfully added.

2022-04-18 06:39:53 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:39:56 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:39:56 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:40:04 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v2 192.168.10.14
2022-04-18 06:40:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:40:16 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.14
2022-04-18 06:40:20 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.14 (192.168.10.14) 56(84) bytes of data.
64 bytes from 192.168.10.14: icmp_seq=1 ttl=64 time=0.305 ms
64 bytes from 192.168.10.14: icmp_seq=2 ttl=64 time=0.113 ms
64 bytes from 192.168.10.14: icmp_seq=3 ttl=64 time=0.134 ms
64 bytes from 192.168.10.14: icmp_seq=4 ttl=64 time=0.128 ms
64 bytes from 192.168.10.14: icmp_seq=5 ttl=64 time=0.105 ms

--- 192.168.10.14 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4086ms
rtt min/avg/max/mdev = 0.105/0.157/0.305/0.074 ms

2022-04-18 06:40:28 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v2 | grep inet6
2022-04-18 06:40:28 - sshInstance.py - [line:54] - root - INFO -         inet6 fe80::3d68:3a1b:f848:bced  prefixlen 64  scopeid 0x20<link>

2022-04-18 06:40:36 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens43f0v2 fe80::b696:91ff:fea0:2170
2022-04-18 06:40:40 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than ens43f0v2.
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens43f0v2: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v2: icmp_seq=1 ttl=64 time=0.386 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v2: icmp_seq=2 ttl=64 time=0.117 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v2: icmp_seq=3 ttl=64 time=0.138 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v2: icmp_seq=4 ttl=64 time=0.141 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v2: icmp_seq=5 ttl=64 time=0.142 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4129ms
rtt min/avg/max/mdev = 0.117/0.184/0.386/0.102 ms

2022-04-18 06:40:45 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v3:
2022-04-18 06:40:48 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v3
2022-04-18 06:40:48 - sshInstance.py - [line:54] - root - INFO - Error: unknown connection 'ens43f0v3'.
Error: cannot delete unknown connection(s): 'ens43f0v3'.

2022-04-18 06:40:53 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:40:56 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:40:56 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:41:01 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0v3:
2022-04-18 06:41:04 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0v3 ifname ens43f0v3
2022-04-18 06:41:04 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v3' (31526a66-39f6-4954-8c00-8ccd33b3c3ad) successfully added.

2022-04-18 06:41:09 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:41:12 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:41:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:41:20 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v3 192.168.10.15
2022-04-18 06:41:21 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:41:32 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.15
2022-04-18 06:41:36 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.15 (192.168.10.15) 56(84) bytes of data.
64 bytes from 192.168.10.15: icmp_seq=1 ttl=64 time=0.380 ms
64 bytes from 192.168.10.15: icmp_seq=2 ttl=64 time=0.188 ms
64 bytes from 192.168.10.15: icmp_seq=3 ttl=64 time=0.124 ms
64 bytes from 192.168.10.15: icmp_seq=4 ttl=64 time=0.122 ms
64 bytes from 192.168.10.15: icmp_seq=5 ttl=64 time=0.122 ms

--- 192.168.10.15 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4116ms
rtt min/avg/max/mdev = 0.122/0.187/0.380/0.100 ms

2022-04-18 06:41:44 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0v3 | grep inet6
2022-04-18 06:41:44 - sshInstance.py - [line:54] - root - INFO -         inet6 fe80::7978:3b1:e7ed:b8d3  prefixlen 64  scopeid 0x20<link>

2022-04-18 06:41:52 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens43f0v3 fe80::b696:91ff:fea0:2170
2022-04-18 06:41:56 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than ens43f0v3.
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens43f0v3: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v3: icmp_seq=1 ttl=64 time=0.417 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v3: icmp_seq=2 ttl=64 time=0.143 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v3: icmp_seq=3 ttl=64 time=0.141 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v3: icmp_seq=4 ttl=64 time=0.141 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens43f0v3: icmp_seq=5 ttl=64 time=0.142 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4127ms
rtt min/avg/max/mdev = 0.141/0.196/0.417/0.111 ms

2022-04-18 06:42:01 - test_nics.py - [line:192] - root - INFO - deleting vf network for redhat.
2022-04-18 06:42:01 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v0:
2022-04-18 06:42:04 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v0
2022-04-18 06:42:04 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v0' (a62035ab-a118-4276-bd57-727226e59e20) successfully deleted.

2022-04-18 06:42:09 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:42:12 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:42:12 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:42:17 - test_nics.py - [line:192] - root - INFO - deleting vf network for redhat.
2022-04-18 06:42:17 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v1:
2022-04-18 06:42:20 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v1
2022-04-18 06:42:20 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v1' (f237be46-84a7-4961-9b6a-51ad334c87cf) successfully deleted.

2022-04-18 06:42:25 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:42:28 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:42:28 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:42:33 - test_nics.py - [line:192] - root - INFO - deleting vf network for redhat.
2022-04-18 06:42:33 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v2:
2022-04-18 06:42:36 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v2
2022-04-18 06:42:37 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v2' (b319a7e3-c4d8-4e79-a71a-fbca18b5e4c8) successfully deleted.

2022-04-18 06:42:42 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:42:45 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:42:45 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:42:50 - test_nics.py - [line:192] - root - INFO - deleting vf network for redhat.
2022-04-18 06:42:50 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0v3:
2022-04-18 06:42:53 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0v3
2022-04-18 06:42:53 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0v3' (31526a66-39f6-4954-8c00-8ccd33b3c3ad) successfully deleted.

2022-04-18 06:42:58 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:43:01 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:43:01 - sshInstance.py - [line:54] - root - INFO - 
.2022-04-18 06:43:09 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:43:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:43:24 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:43:24 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:43:32 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0 0
2022-04-18 06:43:33 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:43:41 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 0
2022-04-18 06:43:41 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:43:49 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-04-18 06:43:49 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:43:54 - test_nics.py - [line:80] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-04-18 06:43:54 - test_nics.py - [line:82] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-04-18/test_gold_PI_Networking_SRIOV_CheckDevice_06_34_23
2022-04-18 06:43:57 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-04-18 06:43:57 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:44:02 - test_nics.py - [line:84] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-04-18 06:44:02 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-04-18 06:44:02 - test_nics.py - [line:86] - root - INFO - this is Test_Nics teardown
2022-04-18 06:44:02 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
                                  [100%]

=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f93947d09e8>
vm1_image = 'rhel86.img', vm2_image = 'rhel862.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSriov5times
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest(self, vm1_image, vm2_image):
        for j in range(1, 2):
            logging.info("\nStress Disable and Enable for {} time when VF is Assigned VM guest.\n".format(j))
            # get pf id: 0000:xx:xx.x
            pf_id, status = self.get_pf_id(self.client, self.pf_name)
            # transfer pf_id to 0000\:00\:00.0 format
            if not pf_id:
                assert 200 == status
            else:
                pf_id_format = pf_id.replace(":", "\\:", 2)
                logging.info("format_pf_id is {}".format(pf_id_format))
                # get the number key of pf_id
                pf_id_key = pf_id.split(":")[1]
                logging.info("pf_id_key: {}".format(pf_id_key))
                # assign IP to PF in SUT and sut2
                pf_ip = "192.168.10.10"
                sut2_ip = "192.168.10.11"
                logging.info("start to assign ip for {} of SUT1: {}".format(self.pf_name, pf_ip))
                assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
                logging.info("start to assign ip for {} of SUT2: {}".format(self.pf2_name, sut2_ip))
                assert 200 == self.assign_ip_ehternet(self.session2, sut2_ip, self.pf2_name)
                # virtulize the pf to vfs
                assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
                # get vf ids
                vf_id_list, status = self.get_vf_ids(self.client, pf_id_key)
                vf_id_list = [i.strip() for i in vf_id_list]
                if status == 200:
                    # modprobe vfio-pci
                    assert 200 == self.modprobe("vfio-pci")
                    # bind vf with vfio-pci
                    host_dev_id_list, status = self.bind_vf_to_vfio_pci(self.client, vf_id_list)
                    assert 200 == status
                else:
                    assert 200 == status
                # get vF device ida
                # tmp code
                cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
                logging.info(cmd)
                vf_device_id = ""
                vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
                vf_device_id_rs = vf_device_id_rs.strip()
                if vf_device_id_rs:
                    st = False
                    vf_device_id = None
                    for one in vf_device_id_rs.split(" "):
                        one = " " + one + " "
                        if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                            vf_device_id = one.replace("[", "").replace("]", "").strip()
                    if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                    logging.info("Successfully get vf device id: {}".format(vf_device_id))
                    assert 200 == 200
                else:
                    logging.error("Fail to get vf device id.")
                    assert 200 == 400
    
                # set network
                status = self.default_network_isActive(self.client, self.defult_network)
                if status == "no":
                    logging.info("start to check default network status...")
                    assert 200 == self.start_default_network(self.client, self.defult_network)
    
                # start VMs
                logging.info("start to create VMs....")
                if self.sut_info["os"] == "UBUNTU":
                    assert 200 == self.create_vm(vm1_image, host_dev_id_list[0],  self.vm1_name, "ubuntu20.04", "5900")
                    assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "ubuntu20.04", "5901")
                else:
>                   assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "rhel8.2", "5900")
E                   AssertionError: assert 200 == 400
E                    +  where 400 = <bound method Test_Network_SRIOV_Stress.create_vm of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f93947d09e8>>('rhel86.img', 'pci_0000_98_01_0', 'VMtest1', 'rhel8.2', '5900')
E                    +    where <bound method Test_Network_SRIOV_Stress.create_vm of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f93947d09e8>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f93947d09e8>.create_vm
E                    +    and   'VMtest1' = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f93947d09e8>.vm1_name

npxtester/Tests/testNics/test_network_sriov_stress.py:650: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-04-18 06:28:35 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-04-18 06:28:35 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img]_06_28_35/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img].log, case_logdir: /root/testconfig/testlogs/2022-04-18/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img]_06_28_35
2022-04-18 06:28:35 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img] case ============================
2022-04-18 06:28:35 - test_network_sriov_stress.py - [line:32] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-04-18 06:28:35 - test_network_sriov_stress.py - [line:50] - root - INFO - ssh to the sut1
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:28:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.80
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-04-18 06:28:35 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-04-18 06:28:35 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-04-18 06:28:35 - test_network_sriov_stress.py - [line:64] - root - INFO - clean up iperf and taskset process...
2022-04-18 06:28:38 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-18 06:28:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:46 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-18 06:28:46 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:28:54 - sshInstance.py - [line:50] - root - INFO - pkill -9 iperf
2022-04-18 06:28:55 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:03 - sshInstance.py - [line:50] - root - INFO - pkill -9 taskset
2022-04-18 06:29:03 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:08 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 3] Opened sftp connection (server version 3)
2022-04-18 06:29:08 - sshInstance.py - [line:199] - root - INFO - start to rmmod irdma....
2022-04-18 06:29:11 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-04-18 06:29:11 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:16 - sshInstance.py - [line:202] - root - INFO - finished rmmod irdma....
2022-04-18 06:29:16 - sshInstance.py - [line:203] - root - INFO - start to rmmod ice....
2022-04-18 06:29:19 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-04-18 06:29:29 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:29:34 - sshInstance.py - [line:206] - root - INFO - finished rmmod ice....
2022-04-18 06:29:34 - sshInstance.py - [line:208] - root - INFO - start to modprobe ice....
2022-04-18 06:29:38 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-04-18 06:30:14 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:30:19 - sshInstance.py - [line:210] - root - INFO - finished modprobe ice....
2022-04-18 06:30:22 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens43f0
2022-04-18 06:30:22 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 4.18.0-369.el8.x86_64
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:98:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-04-18 06:30:27 - test_network_sriov_stress.py - [line:72] - root - INFO - try to get ipv6 of pf for redhat...
2022-04-18 06:30:27 - sshInstance.py - [line:187] - root - INFO - starting to delete network of ens43f0:
2022-04-18 06:30:30 - sshInstance.py - [line:50] - root - INFO - nmcli connection delete ens43f0
2022-04-18 06:30:30 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0' (18e7cccf-fb4c-40f2-960c-d7e2b0b15d06) successfully deleted.

2022-04-18 06:30:35 - sshInstance.py - [line:189] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:30:38 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:30:38 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:30:43 - sshInstance.py - [line:192] - root - INFO - starting to add network of ens43f0:
2022-04-18 06:30:46 - sshInstance.py - [line:50] - root - INFO - nmcli connection add type ethernet con-name ens43f0 ifname ens43f0
2022-04-18 06:30:46 - sshInstance.py - [line:54] - root - INFO - Connection 'ens43f0' (032e2133-1fcb-4054-a9e5-fcacd106aff3) successfully added.

2022-04-18 06:30:51 - sshInstance.py - [line:195] - root - INFO - restart networkManager to make setting valid
2022-04-18 06:30:54 - sshInstance.py - [line:50] - root - INFO - systemctl restart NetworkManager
2022-04-18 06:30:54 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:30:59 - test_network_sriov_stress.py - [line:79] - root - INFO - trying to get ipv6 addr for pf1
2022-04-18 06:31:02 - sshInstance.py - [line:50] - root - INFO - ifconfig ens43f0
2022-04-18 06:31:02 - sshInstance.py - [line:54] - root - INFO - ens43f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::aac6:502c:14ca:edbc  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:20:d8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 3454 (3.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-04-18 06:31:10 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-04-18 06:31:10 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 11902775582  bytes 18020192935675 (16.3 TiB)
        RX errors 0  dropped 943  overruns 0  frame 0
        TX packets 484835901  bytes 36210431058 (33.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


------------------------------ Captured log setup ------------------------------
INFO     root:NicTestFixture.py:20 test -------
----------------------------- Captured stdout call -----------------------------
2022-04-18 06:31:15 - test_network_sriov_stress.py - [line:585] - root - INFO - 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

2022-04-18 06:31:18 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -s | grep ens43f0 | awk '{print $1;}'
2022-04-18 06:31:19 - sshInstance.py - [line:54] - root - INFO - 0000:98:00.0

2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:130] - root - INFO - pf_id was found: 0000:98:00.0

2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:593] - root - INFO - format_pf_id is 0000\:98\:00.0

2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:596] - root - INFO - pf_id_key: 98
2022-04-18 06:31:24 - test_network_sriov_stress.py - [line:600] - root - INFO - start to assign ip for ens43f0 of SUT1: 192.168.10.10
2022-04-18 06:31:30 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Apr 18 06:42:14 2022 from 10.112.97.60
[root@npx-auto-SPR-quanta ~]# ifconfig ens43f0 192.168.10.10
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:31:33 - test_network_sriov_stress.py - [line:333] - root - INFO - Successfully assigned ip to ethernet: ens43f0
2022-04-18 06:31:33 - test_network_sriov_stress.py - [line:602] - root - INFO - start to assign ip for ens785f0 of SUT2: 192.168.10.11
2022-04-18 06:31:39 - sshInstance.py - [line:99] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Apr 18 06:41:44 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-04-18 06:31:42 - test_network_sriov_stress.py - [line:333] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-04-18 06:31:42 - test_network_sriov_stress.py - [line:136] - root - INFO - virtulize sut1 pf to 4 vfs
2022-04-18 06:31:45 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens43f0/device/sriov_numvfs
2022-04-18 06:31:49 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:31:54 - test_network_sriov_stress.py - [line:145] - root - INFO - Successfully Virtualized PF to VFs.
2022-04-18 06:31:57 - sshInstance.py - [line:50] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-04-18 06:31:57 - sshInstance.py - [line:54] - root - INFO - 98:01.0
98:01.1
98:01.2
98:01.3

2022-04-18 06:32:02 - test_network_sriov_stress.py - [line:159] - root - INFO - Succssfully Gotten vf_id list:

2022-04-18 06:32:05 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-04-18 06:32:05 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:32:10 - test_network_sriov_stress.py - [line:179] - root - INFO - start to bind drive in sut1
2022-04-18 06:32:13 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -b vfio-pci 98:01.0
2022-04-18 06:32:16 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:32:21 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-18 06:32:24 - sshInstance.py - [line:50] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -b vfio-pci 98:01.1
2022-04-18 06:32:27 - sshInstance.py - [line:54] - root - INFO - 
2022-04-18 06:32:32 - test_network_sriov_stress.py - [line:193] - root - INFO - Successfuly bound VF to vfio-pci
2022-04-18 06:32:32 - test_network_sriov_stress.py - [line:620] - root - INFO - lspci -Dnn | grep 98:01.1
2022-04-18 06:32:35 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 98:01.1
2022-04-18 06:32:35 - sshInstance.py - [line:54] - root - INFO - 0000:98:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-04-18 06:32:40 - test_network_sriov_stress.py - [line:632] - root - INFO - Successfully get vf device id: 8086:1889
2022-04-18 06:32:40 - test_network_sriov_stress.py - [line:216] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-18 06:32:43 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-04-18 06:32:43 - sshInstance.py - [line:54] - root - INFO - yes

2022-04-18 06:32:48 - test_network_sriov_stress.py - [line:219] - root - INFO - Default network is active? yes

2022-04-18 06:32:48 - test_network_sriov_stress.py - [line:645] - root - INFO - start to create VMs....
2022-04-18 06:32:48 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-18 06:32:52 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
2022-04-18 06:32:53 - sshInstance.py - [line:75] - root - INFO - ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:32:56 - test_network_sriov_stress.py - [line:256] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:32:56 - test_network_sriov_stress.py - [line:257] - root - INFO - Failed to create a VM: 
2022-04-18 06:32:56 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-18 06:33:00 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
2022-04-18 06:33:02 - sshInstance.py - [line:75] - root - INFO - ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:05 - test_network_sriov_stress.py - [line:256] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:05 - test_network_sriov_stress.py - [line:257] - root - INFO - Failed to create a VM: 
2022-04-18 06:33:05 - test_network_sriov_stress.py - [line:249] - root - INFO - try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

2022-04-18 06:33:09 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
2022-04-18 06:33:10 - sshInstance.py - [line:75] - root - INFO - ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:256] - root - INFO - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:257] - root - INFO - Failed to create a VM: 
2022-04-18 06:33:13 - test_network_sriov_stress.py - [line:265] - root - ERROR - Failed to create a VM: VMtest1)
------------------------------ Captured log call -------------------------------
INFO     root:test_network_sriov_stress.py:585 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -s | grep ens43f0 | awk '{print $1;}'
INFO     root:sshInstance.py:54 0000:98:00.0

INFO     root:test_network_sriov_stress.py:130 pf_id was found: 0000:98:00.0

INFO     root:test_network_sriov_stress.py:593 format_pf_id is 0000\:98\:00.0

INFO     root:test_network_sriov_stress.py:596 pf_id_key: 98
INFO     root:test_network_sriov_stress.py:600 start to assign ip for ens43f0 of SUT1: 192.168.10.10
INFO     root:sshInstance.py:99 Activate the web console with: systemctl enable --now cockpit.socket
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Apr 18 06:42:14 2022 from 10.112.97.60
[root@npx-auto-SPR-quanta ~]# ifconfig ens43f0 192.168.10.10
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:333 Successfully assigned ip to ethernet: ens43f0
INFO     root:test_network_sriov_stress.py:602 start to assign ip for ens785f0 of SUT2: 192.168.10.11
INFO     root:sshInstance.py:99 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Apr 18 06:41:44 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
INFO     root:test_network_sriov_stress.py:333 Successfully assigned ip to ethernet: ens785f0
INFO     root:test_network_sriov_stress.py:136 virtulize sut1 pf to 4 vfs
INFO     root:sshInstance.py:50 echo 4 > /sys/class/net/ens43f0/device/sriov_numvfs
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:145 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:50  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:54 98:01.0
98:01.1
98:01.2
98:01.3

INFO     root:test_network_sriov_stress.py:159 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:50 modprobe vfio-pci

INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:179 start to bind drive in sut1
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -b vfio-pci 98:01.0
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:193 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:50 /opt/APP/utility/DPDK_install/dpdk-22.03/usertools/dpdk-devbind.py -b vfio-pci 98:01.1
INFO     root:sshInstance.py:54 
INFO     root:test_network_sriov_stress.py:193 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:620 lspci -Dnn | grep 98:01.1
INFO     root:sshInstance.py:50 lspci -Dnn | grep 98:01.1
INFO     root:sshInstance.py:54 0000:98:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:632 Successfully get vf device id: 8086:1889
INFO     root:test_network_sriov_stress.py:216 get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:54 yes

INFO     root:test_network_sriov_stress.py:219 Default network is active? yes

INFO     root:test_network_sriov_stress.py:645 start to create VMs....
INFO     root:test_network_sriov_stress.py:249 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
INFO     root:sshInstance.py:75 ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:256 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:257 Failed to create a VM: 
INFO     root:test_network_sriov_stress.py:249 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
INFO     root:sshInstance.py:75 ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:256 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:257 Failed to create a VM: 
INFO     root:test_network_sriov_stress.py:249 try to create VM with the cmd1: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk path=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole

INFO     root:sshInstance.py:75 virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
INFO     root:sshInstance.py:75 ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:256 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host ---vcpus=5 --network network=default --hostdev pci_0000_98_01_0 --boot hd --disk ppath=/home/image/rhel86.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,,listen=0.0.0.0,port=5900 --noautoconsole
ERROR    Disk /home/image/rhel86.img is already in use by other guests ['VMtest1']. (Use --check path_in_use=off or --check all=off to override)
[root@npx-auto-SPR-quanta ~]# 
INFO     root:test_network_sriov_stress.py:257 Failed to create a VM: 
ERROR    root:test_network_sriov_stress.py:265 Failed to create a VM: VMtest1)
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:88
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_iperf_client_4hour.py:88: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:137
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_iperf_client_4hour.py:137: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:581
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:581: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:707
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:707: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:947
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:947: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_network_sriov_stress.py:1083
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:1083: PytestUnknownMarkWarning: Unknown pytest.mark.nicIperfTcpSUTGuestStress - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicIperfTcpSUTGuestStress

npxtester/Tests/testNics/test_network_sriov_stress.py:1084
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:1084: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:93
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:93: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:119
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:119: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:149
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:149: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:150
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:150: PytestUnknownMarkWarning: Unknown pytest.mark.test - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.test

npxtester/Tests/testNics/test_nics.py:238
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:238: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:264
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:264: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:307
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:307: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nicGold_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[rhel86.img-rhel862.img]
===== 1 failed, 3 passed, 15 deselected, 18 warnings in 1264.26s (0:21:04) =====
[8mha:////4DDaF6xD1n97fCJC17HEPtC4MvFSxjBMoUPdpyGs71EZAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AGMzKKgvgAAAA==[0m[Pipeline] echo
1
[8mha:////4JdwCG2vyNU1vR63Cq0h1I9fweuZdBzoUYFbNZMa07ZpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAcw+QVkfcu1r/wFPn4+LvgAAAA==[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4J0lAWMm8HuBR5s3oE3lokuIt9KB2+AHQUkjEiJ+aQGpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPMKRSIUQVVorDS8w8WGcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThyM6JEGS7GzwrvR5CUmDsPV8SR6voiOKbJD0eLUssZmwZYTwpKihJWEDVLnOFoyCbayVw9VOUWmOqeQv6OE0uo7PKGQ2ZxUSF+YA+xuo45MP89fAcw+Qbk/5Kpr/wEOrpSSvgAAAA==[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4Mt0DSsxkJzZfVcF7hGhEOllvDy/ttdaA/Rf0YiZvcahAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAQ1CqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKYhQrk95Nrthw/JONXdvgAAAA==[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4BJ3niM699yfMaO4XlYckMNVxHBxF/A/6tXrT01aXGOTAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigSgQSkVrueEFJjHGiXUXbAen4kV8jT9gEYmKLVY728zrDcvgoWZvsNPUWwqNxcGNJi9M7Pur44QdX7BhCuw0Sp0kt/o0o+SoYU5RwkLASlPjOFgyEdaiUw9VOUWmOkefv6OA0rZ3eEIhsjkqH78wedjcxjYw/Tx/BTANQ4Ryt8+1PXwARMxJg74AAAA=[0m[Pipeline] }
[8mha:////4KLOGR+83vgrLFidGueNeEu4h+87+yS5qW1q0kigPKEkAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu32u7eEDfI7acr4AAAA=[0m[Pipeline] // script
[8mha:////4B/bjeg5xruNbbx3kITLupXWvVAJcKllvbrOrw34K5MTAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiQZECUaW10vACExvjxLoztkNS8SK+xh+wiETFFqudbeb1hnUMcOJgsNc0WIqdRe9GkxdOHIar4wl7vmDHFNlpbPXUstLNgi0nDUuKElYCNpo6x9GSSbAVvXzIykky1TmF/B0FlFbd4QmFyOYkQ/rCHGB3G1Vk+nn+CmD2PkF5qHPt6w9IQDkpvgAAAA==[0m[Pipeline] }
[8mha:////4Pysn2p6Cuaw38A5WKCzX3hZbaQrVsudvseeZZRTcVjBAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu0Ou7f4DC8Jor74AAAA=[0m[Pipeline] // stage
[8mha:////4AtNwyaW/AZqBd3OKxZrkWfAC6zB3HxngMFQ9sJmqFs1AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEGIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsP/+idkr0AAAA=[0m[Pipeline] }
[8mha:////4I5dJP3UyABwbWbQZBRGWAtgfXC/GfHsQ3SW1rlV0+rIAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBlS/sHL0AAAA=[0m[Pipeline] // node
[8mha:////4OCxxHdXTRYePL6pNSOSjI/nVmiKF6Ardumg4UkWHzykAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBszaLVr0AAAA=[0m[Pipeline] End of Pipeline
Finished: FAILURE
