Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","pf1":"ens2f0","os":"RHEL"},"pkg_generator":{"host":"10.112.97.60","pf1":"ens2f1"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 16 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-16 02:44:55 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-16 02:44:55 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-16 02:44:55 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-16 02:44:55 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-16 02:44:55 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-16 02:44:58 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-16 02:44:58 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-16 02:45:06 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-16 02:45:10 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:18 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-16 02:45:23 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:31 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-16 02:45:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:39 - sshInstance.py - [line:46] - root - INFO - ethtool -i ens2f0
2022-03-16 02:45:39 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 2.50 0x80006a16 1.2852.0
expansion-rom-version: 
bus-info: 0000:4b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-16 02:45:47 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-16 02:45:47 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 19  bytes 3138 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-16 02:45:55 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-16 02:45:55 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 8657981297  bytes 13105540134786 (11.9 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 318586911  bytes 25226623093 (23.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-16 02:46:00 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-16 02:46:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-16 02:46:04 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-16 02:46:15 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:38:47 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-16 02:46:18 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-16 02:46:24 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:29:58 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-16 02:46:27 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-16 02:46:30 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-16 02:46:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:46:35 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-16 02:46:38 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-16 02:46:38 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-16 02:46:43 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-16 02:46:46 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-16 02:46:47 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:46:55 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-16 02:46:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:47:00 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-16 02:47:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-16 02:47:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:47:09 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-16 02:47:09 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-16 02:47:12 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-16 02:47:12 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-16 02:47:17 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-16 02:47:20 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-16 02:47:20 - sshInstance.py - [line:50] - root - INFO - no

2022-03-16 02:47:25 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? no

2022-03-16 02:47:25 - test_network_sriov_stress.py - [line:207] - root - INFO - virsh net-start default
2022-03-16 02:47:28 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-16 02:47:29 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-16 02:47:34 - test_network_sriov_stress.py - [line:211] - root - INFO - Successfully started network default.
2022-03-16 02:47:38 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-16 02:47:39 - sshInstance.py - [line:71] - root - INFO - 
** (process:13450): [1;33mWARNING[0m **: [34m02:56:11.393[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-16 02:47:41 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-16 02:47:44 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-16 02:47:48 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13499): [1;33mWARNING[0m **: [34m02:56:21.174[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-16 02:47:50 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-16 02:47:53 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-16 02:47:56 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:47:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:48:01 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-16 02:49:04 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:49:04 - sshInstance.py - [line:50] - root - INFO - 192.168.122.67/24

2022-03-16 02:49:09 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.67/24

2022-03-16 02:49:12 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:49:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:49:17 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:50:20 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:50:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:50:25 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:51:28 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:51:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:51:34 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:52:37 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:52:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:52:42 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:53:45 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:53:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:53:50 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:54:53 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:54:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:54:58 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:55:58 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.67
2022-03-16 02:55:58 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 
2022-03-16 02:56:02 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.67
PING 192.168.122.67 (192.168.122.67) 56(84) bytes of data.
64 bytes from 192.168.122.67: icmp_seq=1 ttl=64 time=0.403 ms
2022-03-16 02:56:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=2 ttl=64 time=0.418 ms
2022-03-16 02:56:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=3 ttl=64 time=0.427 ms
2022-03-16 02:56:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=4 ttl=64 time=0.476 ms
2022-03-16 02:56:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=5 ttl=64 time=0.405 ms

--- 192.168.122.67 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.403/0.425/0.476/0.037 ms
[root@WW25ICX2 ~]# 
2022-03-16 02:56:15 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.67
root@192.168.122.67's password: 
2022-03-16 02:56:25 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Mar 2022 03:04:54 PM EDT
  System load:  0.0                Processes:             128
  Usage of /:   36.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.67
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Dec 28 01:16:15 2021
root@localhost:~# 
2022-03-16 02:56:34 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-16 02:56:40 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-16 02:56:46 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-16 02:56:51 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-16 02:56:57 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-16 02:57:00 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-16 02:57:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-16 02:57:16 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-16 02:57:25 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-16 02:57:34 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-16 02:57:43 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-16 02:57:52 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.67 closed.
[root@WW25ICX2 ~]# 
2022-03-16 02:57:59 - sshInstance.py - [line:71] - root - INFO - ping -c 5 
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[root@WW25ICX2 ~]# 
F2022-03-16 02:58:05 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-16 02:58:06 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-16 02:58:11 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-16 02:58:14 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-16 02:58:14 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-16 02:58:19 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-16 02:58:22 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-16 02:58:22 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-16 02:58:27 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-16 02:58:30 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-16 02:58:30 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-16 02:58:35 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-16 02:58:38 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-16 02:58:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:58:48 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-03-16 02:58:48 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:58:56 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 0
2022-03-16 02:58:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:59:04 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-16 02:59:04 - sshInstance.py - [line:50] - root - INFO - bash: /tmp/dmesg.log: No space left on device

2022-03-16 02:59:09 - test_network_sriov_stress.py - [line:82] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-16 02:59:09 - NicTestFixture.py - [line:34] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
E                 [100%]

==================================== ERRORS ====================================
_ ERROR at call of Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] _
self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>
vm1_image = 'uvm1.img', vm2_image = 'uvm2.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSriov5times
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest(self, vm1_image, vm2_image):
        for j in range(1, 6):
            logging.info(
                "\n\n********************************************************Stress Disable and Enable for {} time when VF is Assigned VM guest.*************************************************************\n\n".format(
                    j))
            # get pf id: 0000:xx:xx.x
            pf_id, status = self.get_pf_id(self.pf_name)
            # transfer pf_id to 0000\:00\:00.0 format
            if not pf_id:
                assert 200 == status
            else:
                pf_id_format = pf_id.replace(":", "\\:", 2)
                logging.info("format_pf_id is {}".format(pf_id_format))
                # get the number key of pf_id
                pf_id_key = pf_id.split(":")[1]
                logging.info("pf_id_key: {}".format(pf_id_key))
                # assign IP to PF in SUT and sut2
                pf_ip = "192.168.10.10"
                sut2_ip = "192.168.10.11"
                assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
                assert 200 == self.assign_ip_ehternet(self.session2, sut2_ip, self.pf_name)
                # virtulize the pf to vfs
                assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
                # get vf ids
                vf_id_list, status = self.get_vf_ids(pf_id_key)
                vf_id_list = [i.strip() for i in vf_id_list]
                if status == 200:
                    # modprobe vfio-pci
                    assert 200 == self.modprobe("vfio-pci")
                    # bind vf with vfio-pci
                    host_dev_id_list, status = self.bind_vf_to_vfio_pci(vf_id_list)
                    assert 200 == status
                else:
                    assert 200 == status
                # get vF device ida
                # tmp code
                cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
                logging.info(cmd)
                vf_device_id = ""
                vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
                if vf_device_id_rs:
                    st = False
                    vf_device_id = None
                    for one in vf_device_id_rs.split(" "):
                        one = " " + one + " "
                        if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                            vf_device_id = one.replace("[", "").replace("]", "").strip()
                    if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                    logging.info("Successfully get vf device id: {}".format(vf_device_id))
                    assert 200 == 200
                else:
                    logging.error("Fail to get vf device id.")
                    assert 200 == 400
    
                # set network
                status = self.default_network_isActive(self.defult_network)
                if status == "no":
                    assert 200 == self.start_default_network(self.defult_network)
    
                # start VMs
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "5901")
                # get VM ssh IP
                vm1_ip, status1 = self.get_vm_ip(self.vm1_name)
                vm2_ip, status2 = self.get_vm_ip(self.vm2_name)
                logging.info("ip of VM1: {}".format(vm1_ip))
                logging.info("ip of VM1: {}".format(vm2_ip))
    
                # ssh VM1 to set VF
                vm1_vf_ip = "192.168.10.12"
                vm2_vf_ip = "192.168.10.13"
                assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                                  vm1_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
                vm1_vf_name, vm1_ipv6, status = self.ssh_vm_set_VF(vm1_ip, vf_device_id, vm1_vf_ip, "1234567890ac")
                self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
    
                assert 200 == status, "vm1 vf related settings failed"
>               assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                                  vm2_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
E               AssertionError: ssh vm failed,the reason may be is password is error,vm ip isimpassability
E               assert 200 == 400
E                +  where 400 = <bound method Test_Network_SRIOV_Stress.on_session_ssh of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>>(<libs.commons.sshInstance.sshInstance object at 0x7f3c85bfe198>, <paramiko.Channel 0 (open) window=2096321 -> <paramiko.Transport at 0x85bfeda0 (cipher aes128-ctr, 128 bits) (active; 2 open channel(s))>>, '')
E                +    where <bound method Test_Network_SRIOV_Stress.on_session_ssh of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>.on_session_ssh
E                +    and   <libs.commons.sshInstance.sshInstance object at 0x7f3c85bfe198> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>.ssh_sut
E                +    and   <paramiko.Channel 0 (open) window=2096321 -> <paramiko.Transport at 0x85bfeda0 (cipher aes128-ctr, 128 bits) (active; 2 open channel(s))>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>.session

npxtester/Tests/testNics/test_network_sriov_stress.py:461: AssertionErrorself = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>

    def teardown(self):
        # status = self.remove_vf_from_pf()
        status = self.remove_vm(self.vm2_name)
        status = self.remove_vm(self.vm1_name)
        cmd = "echo 0 > /sys/class/net/{}/device/sriov_numvfs".format(self.sut_info["pf1"])
        self.ssh_sut.ssh_exec_cmd(self.client, cmd)
        self.ssh_sut.ssh_exec_cmd(self.client, "ifconfig {} 0".format(self.sut_info["pf1"]))
        self.ssh_sut.ssh_exec_cmd(self.client2, "ifconfig {} 0".format(self.sut2_info["pf1"]))
        #dmesg log
        self.ssh_sut.ssh_exec_cmd(self.client, "dmesg > /tmp/dmesg.log")
        logging.info("generate dmesg.log file on sut /tmp/dmesg.log")
>       self.sftp.get("/tmp/dmesg.log", os.path.join(self.case_logdir, "dmesg.log"))

npxtester/Tests/testNics/test_network_sriov_stress.py:83: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py:802: in get
    size = self.getfo(remotepath, fl, callback)
/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py:778: in getfo
    file_size = self.stat(remotepath).st_size
/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py:493: in stat
    t, msg = self._request(CMD_STAT, path)
/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py:813: in _request
    return self._read_response(num)
/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py:865: in _read_response
    self._convert_status(msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <paramiko.sftp_client.SFTPClient object at 0x7f3c87f7b828>
msg = paramiko.Message(b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x0cNo such file\x00\x00\x00\x00')

    def _convert_status(self, msg):
        """
        Raises EOFError or IOError on error status; otherwise does nothing.
        """
        code = msg.get_int()
        text = msg.get_text()
        if code == SFTP_OK:
            return
        elif code == SFTP_EOF:
            raise EOFError(text)
        elif code == SFTP_NO_SUCH_FILE:
            # clever idea from john a. meinel: map the error codes to errno
>           raise IOError(errno.ENOENT, text)
E           FileNotFoundError: [Errno 2] No such file

/usr/local/lib/python3.6/site-packages/paramiko/sftp_client.py:894: FileNotFoundError
---------------------------- Captured stdout setup -----------------------------
2022-03-16 02:44:55 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-16 02:44:55 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-16 02:44:55 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-16 02:44:55 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-16 02:44:55 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-16 02:44:58 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-16 02:44:58 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-16 02:45:06 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-16 02:45:10 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:18 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-16 02:45:23 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:31 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-16 02:45:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:39 - sshInstance.py - [line:46] - root - INFO - ethtool -i ens2f0
2022-03-16 02:45:39 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 2.50 0x80006a16 1.2852.0
expansion-rom-version: 
bus-info: 0000:4b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-16 02:45:47 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-16 02:45:47 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 19  bytes 3138 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-16 02:45:55 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-16 02:45:55 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 8657981297  bytes 13105540134786 (11.9 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 318586911  bytes 25226623093 (23.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-03-16 02:46:00 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-16 02:46:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-16 02:46:04 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-16 02:46:15 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:38:47 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-16 02:46:18 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-16 02:46:24 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:29:58 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-16 02:46:27 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-16 02:46:30 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-16 02:46:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:46:35 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-16 02:46:38 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-16 02:46:38 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-16 02:46:43 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-16 02:46:46 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-16 02:46:47 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:46:55 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-16 02:46:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:47:00 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-16 02:47:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-16 02:47:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:47:09 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-16 02:47:09 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-16 02:47:12 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-16 02:47:12 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-16 02:47:17 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-16 02:47:20 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-16 02:47:20 - sshInstance.py - [line:50] - root - INFO - no

2022-03-16 02:47:25 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? no

2022-03-16 02:47:25 - test_network_sriov_stress.py - [line:207] - root - INFO - virsh net-start default
2022-03-16 02:47:28 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-16 02:47:29 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-16 02:47:34 - test_network_sriov_stress.py - [line:211] - root - INFO - Successfully started network default.
2022-03-16 02:47:38 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-16 02:47:39 - sshInstance.py - [line:71] - root - INFO - 
** (process:13450): [1;33mWARNING[0m **: [34m02:56:11.393[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-16 02:47:41 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-16 02:47:44 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-16 02:47:48 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13499): [1;33mWARNING[0m **: [34m02:56:21.174[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-16 02:47:50 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-16 02:47:53 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-16 02:47:56 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:47:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:48:01 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-16 02:49:04 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:49:04 - sshInstance.py - [line:50] - root - INFO - 192.168.122.67/24

2022-03-16 02:49:09 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.67/24

2022-03-16 02:49:12 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:49:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:49:17 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:50:20 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:50:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:50:25 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:51:28 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:51:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:51:34 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:52:37 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:52:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:52:42 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:53:45 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:53:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:53:50 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:54:53 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:54:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:54:58 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:55:58 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.67
2022-03-16 02:55:58 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 
2022-03-16 02:56:02 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.67
PING 192.168.122.67 (192.168.122.67) 56(84) bytes of data.
64 bytes from 192.168.122.67: icmp_seq=1 ttl=64 time=0.403 ms
2022-03-16 02:56:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=2 ttl=64 time=0.418 ms
2022-03-16 02:56:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=3 ttl=64 time=0.427 ms
2022-03-16 02:56:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=4 ttl=64 time=0.476 ms
2022-03-16 02:56:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=5 ttl=64 time=0.405 ms

--- 192.168.122.67 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.403/0.425/0.476/0.037 ms
[root@WW25ICX2 ~]# 
2022-03-16 02:56:15 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.67
root@192.168.122.67's password: 
2022-03-16 02:56:25 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Mar 2022 03:04:54 PM EDT
  System load:  0.0                Processes:             128
  Usage of /:   36.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.67
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Dec 28 01:16:15 2021
root@localhost:~# 
2022-03-16 02:56:34 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-16 02:56:40 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-16 02:56:46 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-16 02:56:51 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-16 02:56:57 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-16 02:57:00 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-16 02:57:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-16 02:57:16 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-16 02:57:25 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-16 02:57:34 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-16 02:57:43 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-16 02:57:52 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.67 closed.
[root@WW25ICX2 ~]# 
2022-03-16 02:57:59 - sshInstance.py - [line:71] - root - INFO - ping -c 5 
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[root@WW25ICX2 ~]# 
------------------------------ Captured log call -------------------------------
INFO     root:test_network_sriov_stress.py:388 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
INFO     root:sshInstance.py:50 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:111 pf_id was found: 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:396 format_pf_id is 0000\:4b\:00.0

INFO     root:test_network_sriov_stress.py:399 pf_id_key: 4b
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:38:47 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:29:58 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:125 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:46  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:50 4b:01.0
4b:01.1
4b:01.2
4b:01.3

INFO     root:test_network_sriov_stress.py:139 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:46 modprobe vfio-pci

INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:421 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:46 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:50 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:432 Successfully get vf device id: 8086:1889
INFO     root:sshInstance.py:46 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 no

INFO     root:test_network_sriov_stress.py:198 Default network is active? no

INFO     root:test_network_sriov_stress.py:207 virsh net-start default
INFO     root:sshInstance.py:46 virsh net-start default
INFO     root:sshInstance.py:50 Network default started


INFO     root:test_network_sriov_stress.py:211 Successfully started network default.
INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
INFO     root:sshInstance.py:71 
** (process:13450): [1;33mWARNING[0m **: [34m02:56:11.393[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest1
INFO     root:sshInstance.py:71 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13499): [1;33mWARNING[0m **: [34m02:56:21.174[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest1
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.67/24

INFO     root:test_network_sriov_stress.py:245 Successfully got VMtest1 IP: 192.168.122.67/24

INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:test_network_sriov_stress.py:449 ip of VM1: 192.168.122.67
INFO     root:test_network_sriov_stress.py:450 ip of VM1: 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.67
PING 192.168.122.67 (192.168.122.67) 56(84) bytes of data.
64 bytes from 192.168.122.67: icmp_seq=1 ttl=64 time=0.403 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=2 ttl=64 time=0.418 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=3 ttl=64 time=0.427 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=4 ttl=64 time=0.476 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=5 ttl=64 time=0.405 ms

--- 192.168.122.67 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.403/0.425/0.476/0.037 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.67
root@192.168.122.67's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Mar 2022 03:04:54 PM EDT
  System load:  0.0                Processes:             128
  Usage of /:   36.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.67
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Dec 28 01:16:15 2021
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:341 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.12
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.67 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[root@WW25ICX2 ~]#
--------------------------- Captured stdout teardown ---------------------------
2022-03-16 02:58:05 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-16 02:58:06 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-16 02:58:11 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-16 02:58:14 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-16 02:58:14 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-16 02:58:19 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-16 02:58:22 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-16 02:58:22 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-16 02:58:27 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-16 02:58:30 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-16 02:58:30 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-16 02:58:35 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-16 02:58:38 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-16 02:58:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:58:48 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-03-16 02:58:48 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:58:56 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 0
2022-03-16 02:58:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:59:04 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-16 02:59:04 - sshInstance.py - [line:50] - root - INFO - bash: /tmp/dmesg.log: No space left on device

2022-03-16 02:59:09 - test_network_sriov_stress.py - [line:82] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-16 02:59:09 - NicTestFixture.py - [line:34] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
---------------------------- Captured log teardown -----------------------------
INFO     root:sshInstance.py:46 virsh destroy VMtest2
INFO     root:sshInstance.py:50 Domain VMtest2 destroyed


INFO     root:test_network_sriov_stress.py:277 Successfully shut down the VM: VMtest2
INFO     root:sshInstance.py:46 virsh undefine VMtest2
INFO     root:sshInstance.py:50 Domain VMtest2 has been undefined


INFO     root:test_network_sriov_stress.py:287 Successfully removed the VM: VMtest2
INFO     root:sshInstance.py:46 virsh destroy VMtest1
INFO     root:sshInstance.py:50 Domain VMtest1 destroyed


INFO     root:test_network_sriov_stress.py:277 Successfully shut down the VM: VMtest1
INFO     root:sshInstance.py:46 virsh undefine VMtest1
INFO     root:sshInstance.py:50 Domain VMtest1 has been undefined


INFO     root:test_network_sriov_stress.py:287 Successfully removed the VM: VMtest1
INFO     root:sshInstance.py:46 echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 ifconfig ens2f0 0
INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 ifconfig ens2f1 0
INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 dmesg > /tmp/dmesg.log
INFO     root:sshInstance.py:50 bash: /tmp/dmesg.log: No space left on device

INFO     root:test_network_sriov_stress.py:82 generate dmesg.log file on sut /tmp/dmesg.log
INFO     root:NicTestFixture.py:34 ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>
vm1_image = 'uvm1.img', vm2_image = 'uvm2.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSriov5times
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest(self, vm1_image, vm2_image):
        for j in range(1, 6):
            logging.info(
                "\n\n********************************************************Stress Disable and Enable for {} time when VF is Assigned VM guest.*************************************************************\n\n".format(
                    j))
            # get pf id: 0000:xx:xx.x
            pf_id, status = self.get_pf_id(self.pf_name)
            # transfer pf_id to 0000\:00\:00.0 format
            if not pf_id:
                assert 200 == status
            else:
                pf_id_format = pf_id.replace(":", "\\:", 2)
                logging.info("format_pf_id is {}".format(pf_id_format))
                # get the number key of pf_id
                pf_id_key = pf_id.split(":")[1]
                logging.info("pf_id_key: {}".format(pf_id_key))
                # assign IP to PF in SUT and sut2
                pf_ip = "192.168.10.10"
                sut2_ip = "192.168.10.11"
                assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
                assert 200 == self.assign_ip_ehternet(self.session2, sut2_ip, self.pf_name)
                # virtulize the pf to vfs
                assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
                # get vf ids
                vf_id_list, status = self.get_vf_ids(pf_id_key)
                vf_id_list = [i.strip() for i in vf_id_list]
                if status == 200:
                    # modprobe vfio-pci
                    assert 200 == self.modprobe("vfio-pci")
                    # bind vf with vfio-pci
                    host_dev_id_list, status = self.bind_vf_to_vfio_pci(vf_id_list)
                    assert 200 == status
                else:
                    assert 200 == status
                # get vF device ida
                # tmp code
                cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
                logging.info(cmd)
                vf_device_id = ""
                vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
                if vf_device_id_rs:
                    st = False
                    vf_device_id = None
                    for one in vf_device_id_rs.split(" "):
                        one = " " + one + " "
                        if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                            vf_device_id = one.replace("[", "").replace("]", "").strip()
                    if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                    logging.info("Successfully get vf device id: {}".format(vf_device_id))
                    assert 200 == 200
                else:
                    logging.error("Fail to get vf device id.")
                    assert 200 == 400
    
                # set network
                status = self.default_network_isActive(self.defult_network)
                if status == "no":
                    assert 200 == self.start_default_network(self.defult_network)
    
                # start VMs
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "5901")
                # get VM ssh IP
                vm1_ip, status1 = self.get_vm_ip(self.vm1_name)
                vm2_ip, status2 = self.get_vm_ip(self.vm2_name)
                logging.info("ip of VM1: {}".format(vm1_ip))
                logging.info("ip of VM1: {}".format(vm2_ip))
    
                # ssh VM1 to set VF
                vm1_vf_ip = "192.168.10.12"
                vm2_vf_ip = "192.168.10.13"
                assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                                  vm1_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
                vm1_vf_name, vm1_ipv6, status = self.ssh_vm_set_VF(vm1_ip, vf_device_id, vm1_vf_ip, "1234567890ac")
                self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
    
                assert 200 == status, "vm1 vf related settings failed"
>               assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                                  vm2_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
E               AssertionError: ssh vm failed,the reason may be is password is error,vm ip isimpassability
E               assert 200 == 400
E                +  where 400 = <bound method Test_Network_SRIOV_Stress.on_session_ssh of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>>(<libs.commons.sshInstance.sshInstance object at 0x7f3c85bfe198>, <paramiko.Channel 0 (open) window=2096321 -> <paramiko.Transport at 0x85bfeda0 (cipher aes128-ctr, 128 bits) (active; 2 open channel(s))>>, '')
E                +    where <bound method Test_Network_SRIOV_Stress.on_session_ssh of <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>.on_session_ssh
E                +    and   <libs.commons.sshInstance.sshInstance object at 0x7f3c85bfe198> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>.ssh_sut
E                +    and   <paramiko.Channel 0 (open) window=2096321 -> <paramiko.Transport at 0x85bfeda0 (cipher aes128-ctr, 128 bits) (active; 2 open channel(s))>> = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f3c85bfedd8>.session

npxtester/Tests/testNics/test_network_sriov_stress.py:461: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-16 02:44:55 - NicTestFixture.py - [line:30] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-16 02:44:55 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-16 02:44:55 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-16 02:44:55 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-16 02:44:55 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-16 02:44:55 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-16 02:44:58 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-16 02:44:58 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-16 02:45:06 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-16 02:45:10 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:18 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-16 02:45:23 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:31 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-16 02:45:31 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:45:39 - sshInstance.py - [line:46] - root - INFO - ethtool -i ens2f0
2022-03-16 02:45:39 - sshInstance.py - [line:50] - root - INFO - driver: ice
version: 1.6.4
firmware-version: 2.50 0x80006a16 1.2852.0
expansion-rom-version: 
bus-info: 0000:4b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-16 02:45:47 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-16 02:45:47 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 19  bytes 3138 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-16 02:45:55 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-16 02:45:55 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 8657981297  bytes 13105540134786 (11.9 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 318586911  bytes 25226623093 (23.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-03-16 02:46:00 - test_network_sriov_stress.py - [line:388] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-16 02:46:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-16 02:46:04 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:396] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-16 02:46:09 - test_network_sriov_stress.py - [line:399] - root - INFO - pf_id_key: 4b
2022-03-16 02:46:15 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:38:47 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-16 02:46:18 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-16 02:46:24 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:29:58 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
2022-03-16 02:46:27 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-16 02:46:30 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-16 02:46:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:46:35 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-16 02:46:38 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-16 02:46:38 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-16 02:46:43 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-16 02:46:46 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-16 02:46:47 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:46:55 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-16 02:46:55 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:47:00 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-16 02:47:03 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-16 02:47:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:47:09 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-16 02:47:09 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-16 02:47:12 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-16 02:47:12 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-16 02:47:17 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-16 02:47:20 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-16 02:47:20 - sshInstance.py - [line:50] - root - INFO - no

2022-03-16 02:47:25 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? no

2022-03-16 02:47:25 - test_network_sriov_stress.py - [line:207] - root - INFO - virsh net-start default
2022-03-16 02:47:28 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-16 02:47:29 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-16 02:47:34 - test_network_sriov_stress.py - [line:211] - root - INFO - Successfully started network default.
2022-03-16 02:47:38 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-16 02:47:39 - sshInstance.py - [line:71] - root - INFO - 
** (process:13450): [1;33mWARNING[0m **: [34m02:56:11.393[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-16 02:47:41 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-16 02:47:44 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-16 02:47:48 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13499): [1;33mWARNING[0m **: [34m02:56:21.174[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-16 02:47:50 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-16 02:47:53 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-16 02:47:56 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:47:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:48:01 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-16 02:49:04 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:49:04 - sshInstance.py - [line:50] - root - INFO - 192.168.122.67/24

2022-03-16 02:49:09 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.67/24

2022-03-16 02:49:12 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:49:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:49:17 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:50:20 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:50:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:50:25 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:51:28 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:51:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:51:34 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:52:37 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:52:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:52:42 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:53:45 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:53:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:53:50 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:54:53 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-16 02:54:53 - sshInstance.py - [line:50] - root - INFO - 
2022-03-16 02:54:58 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest2
2022-03-16 02:55:58 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.67
2022-03-16 02:55:58 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 
2022-03-16 02:56:02 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.67
PING 192.168.122.67 (192.168.122.67) 56(84) bytes of data.
64 bytes from 192.168.122.67: icmp_seq=1 ttl=64 time=0.403 ms
2022-03-16 02:56:03 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=2 ttl=64 time=0.418 ms
2022-03-16 02:56:04 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=3 ttl=64 time=0.427 ms
2022-03-16 02:56:05 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=4 ttl=64 time=0.476 ms
2022-03-16 02:56:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.67: icmp_seq=5 ttl=64 time=0.405 ms

--- 192.168.122.67 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.403/0.425/0.476/0.037 ms
[root@WW25ICX2 ~]# 
2022-03-16 02:56:15 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.67
root@192.168.122.67's password: 
2022-03-16 02:56:25 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Mar 2022 03:04:54 PM EDT
  System load:  0.0                Processes:             128
  Usage of /:   36.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.67
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Dec 28 01:16:15 2021
root@localhost:~# 
2022-03-16 02:56:34 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-16 02:56:40 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-16 02:56:46 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-16 02:56:51 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-16 02:56:57 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-16 02:57:00 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-16 02:57:06 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-16 02:57:16 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-16 02:57:25 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-16 02:57:34 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-16 02:57:43 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-16 02:57:52 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.67 closed.
[root@WW25ICX2 ~]# 
2022-03-16 02:57:59 - sshInstance.py - [line:71] - root - INFO - ping -c 5 
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[root@WW25ICX2 ~]# 
------------------------------ Captured log call -------------------------------
INFO     root:test_network_sriov_stress.py:388 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
INFO     root:sshInstance.py:50 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:111 pf_id was found: 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:396 format_pf_id is 0000\:4b\:00.0

INFO     root:test_network_sriov_stress.py:399 pf_id_key: 4b
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:38:47 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Wed Mar 16 02:29:58 2022 from 10.112.97.60
[root@localhost ~]# ifconfig ens2f0 192.168.10.11
[root@localhost ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:125 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:46  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:50 4b:01.0
4b:01.1
4b:01.2
4b:01.3

INFO     root:test_network_sriov_stress.py:139 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:46 modprobe vfio-pci

INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:421 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:46 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:50 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:432 Successfully get vf device id: 8086:1889
INFO     root:sshInstance.py:46 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 no

INFO     root:test_network_sriov_stress.py:198 Default network is active? no

INFO     root:test_network_sriov_stress.py:207 virsh net-start default
INFO     root:sshInstance.py:46 virsh net-start default
INFO     root:sshInstance.py:50 Network default started


INFO     root:test_network_sriov_stress.py:211 Successfully started network default.
INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
INFO     root:sshInstance.py:71 
** (process:13450): [1;33mWARNING[0m **: [34m02:56:11.393[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest1
INFO     root:sshInstance.py:71 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13499): [1;33mWARNING[0m **: [34m02:56:21.174[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest1
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.67/24

INFO     root:test_network_sriov_stress.py:245 Successfully got VMtest1 IP: 192.168.122.67/24

INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest2
INFO     root:test_network_sriov_stress.py:449 ip of VM1: 192.168.122.67
INFO     root:test_network_sriov_stress.py:450 ip of VM1: 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.67
PING 192.168.122.67 (192.168.122.67) 56(84) bytes of data.
64 bytes from 192.168.122.67: icmp_seq=1 ttl=64 time=0.403 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=2 ttl=64 time=0.418 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=3 ttl=64 time=0.427 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=4 ttl=64 time=0.476 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.67: icmp_seq=5 ttl=64 time=0.405 ms

--- 192.168.122.67 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4103ms
rtt min/avg/max/mdev = 0.403/0.425/0.476/0.037 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.67
root@192.168.122.67's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Tue 15 Mar 2022 03:04:54 PM EDT
  System load:  0.0                Processes:             128
  Usage of /:   36.6% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.67
  Swap usage:   0%

363 updates can be installed immediately.
221 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Tue Dec 28 01:16:15 2021
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:341 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.12
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 692 (692.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.67 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 
Usage: ping [-aAbBdDfhLnOqrRUvV64] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination
Usage: ping -6 [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
             [-l preload] [-m mark] [-M pmtudisc_option]
             [-N nodeinfo_option] [-p pattern] [-Q tclass] [-s packetsize]
             [-S sndbuf] [-t ttl] [-T timestamp_option] [-w deadline]
             [-W timeout] destination
[root@WW25ICX2 ~]#
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:70
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:108
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:382
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:382: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:500
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:500: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:799
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:799: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:91
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:91: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:116
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:116: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:140
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:140: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:211
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:211: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:237
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:237: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]
====== 1 failed, 16 deselected, 14 warnings, 1 error in 854.71s (0:14:14) ======
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4AfI3SthhIf/wHKBxkZZVuznCBOLGICd+mTaK5J1XhvpAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMHmfoKzrT+3fkMfZ274AAAA=[0m[Pipeline] }
[8mha:////4O1G14z5oV6C9jl1Q5yIn+pZFQRmsElhyj6JiXyHA8ixAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiBB2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7BpKm1V++AAAA[0m[Pipeline] // stage
[8mha:////4KtBCOpIKS64HlRGbxVDHBnhT4546C6ceKSEgLxKWO63AAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUauVY2WZoPEGEGAOZXUwWofJEXs07yMiMlb/67zXv9cYyRRw5OtVYaj2lyqsu9G56auDYXgMPquGLqpgSB6tKO5Rc29OMJYvFvCzHQmNlqQqcPDnBWjfmYYpgyBVniZM7aOS+vuOJTE9lMVG+MEZsbn2dmH6dvwGMXSfIt3tBtvsA/gVtV70AAAA=[0m[Pipeline] }
[8mha:////4PVa+eOfGCB5ryE2GyokIfyPZOVvh3emQVgJTOuHuCGAAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IMJC7GybVh8Qsq1Fpo3sP2IUx+kb/mP0gkcfJO95zlvN5Yp4gjR6daS52nVHvVh8HNT40cu2vgUbV8UTVT4mBVZceKG3tasGKxWJblWGlsLNWBkycn2OrWPEwRDLniLHF2B43cN3c8kem5LCbKF6aI3W1oEtOv8zeAqe8FebkXZOUHjeqpjr0AAAA=[0m[Pipeline] // node
[8mha:////4OyM7hMK6utvbTfbnNkjhtaoCHWCq3+ZbQ+BNe9AvJHZAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRoKBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Lu9INt+AKvzzsS9AAAA[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
