Started by timer
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/spr-test-nicGold
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/spr-test-nicGold/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/spr-test-nicGold/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/spr-test-nicGold/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"5.15.0-1003-realtime"},"dpdk_dir":"/root/dpdk-stable-20.11.3/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.239.183.130","pf1":"ens4f0","os":"RHEL"},"pkg_generator":{"host":"10.239.182.88","pf1":"ens785f0"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4Dqouna/UALz1cds/DYDIib12lRO4R4U9QQgmUx/wyv5AAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgEJMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAnLfKUwgAAAA==[0m[Pipeline] script
[8mha:////4JUhH4fIWh5icAEY6zBr3HRHHu0lnMalVyM2fPsu3/3sAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYgIhpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD0QKVszCAAAA[0m[Pipeline] {
[8mha:////4PJRxj8hD/CuSHgtWDRwAQ67XTdBRcldvWih24U4ysBWAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCoEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AHN/bm5vgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics -s -m nicGold --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nicGold_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 13 deselected / 4 selected

npxtester/Tests/testNics/test_mtu.py 2022-03-28 02:52:26 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-03-28/test_PI_Networking_Jumbo_Packet_CVL_02_52_26/test_PI_Networking_Jumbo_Packet_CVL.log, case_logdir: /root/testconfig/testlogs/2022-03-28/test_PI_Networking_Jumbo_Packet_CVL_02_52_26
2022-03-28 02:52:26 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-28 02:52:26 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-03-28 02:52:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-28 02:52:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 02:52:26 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-28 02:52:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-28 02:52:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 02:52:27 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-28 02:52:27 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-28 02:52:30 - sshInstance.py - [line:50] - root - INFO - modinfo ice | grep ^version:
2022-03-28 02:52:30 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:52:38 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-03-28 02:52:38 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-28 02:52:46 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-03-28 02:52:46 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:52:54 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens4f0
2022-03-28 02:52:54 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-28 02:53:02 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 mtu 1500
2022-03-28 02:53:02 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:53:10 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 1500
2022-03-28 02:53:10 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:53:18 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0
2022-03-28 02:53:18 - sshInstance.py - [line:54] - root - INFO - ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 20  bytes 6840 (6.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 46  bytes 12072 (12.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 02:53:27 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Mon Mar 28 02:43:42 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | What is dead may never die![0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   |                     -- Python 2[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-03-28 02:53:27 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:53:34 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*14480)],iface="ens785f0")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-03-28 02:53:34 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:53:37 - test_mtu.py - [line:92] - root - INFO - success to send package to network
2022-03-28 02:53:41 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*15500)],iface="ens785f0")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-03-28 02:53:41 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:53:44 - test_mtu.py - [line:102] - root - INFO - result is right
.2022-03-28 02:53:47 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 mtu 1500
2022-03-28 02:53:47 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:53:55 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 1500
2022-03-28 02:53:55 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:54:03 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 02:54:03 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:54:11 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-28 02:54:11 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:54:16 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-28 02:54:16 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-28/test_PI_Networking_Jumbo_Packet_CVL_02_52_26
2022-03-28 02:54:19 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-03-28 02:54:19 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:54:24 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-28 02:54:24 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-03-28 02:54:24 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-28 02:54:24 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-03-28/test_PI_Networking_MTU_set_CVL_02_54_24/test_PI_Networking_MTU_set_CVL.log, case_logdir: /root/testconfig/testlogs/2022-03-28/test_PI_Networking_MTU_set_CVL_02_54_24
2022-03-28 02:54:24 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-03-28 02:54:24 - test_mtu.py - [line:16] - root - INFO - this is Test_mtu setup.
2022-03-28 02:54:24 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-28 02:54:24 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 02:54:25 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-28 02:54:25 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-28 02:54:25 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 02:54:25 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-28 02:54:25 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-28 02:54:28 - sshInstance.py - [line:50] - root - INFO - modinfo ice | grep ^version:
2022-03-28 02:54:28 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:54:36 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-03-28 02:54:36 - sshInstance.py - [line:54] - root - INFO - rmmod: ERROR: Module ice is in use by: irdma

2022-03-28 02:54:44 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-03-28 02:54:44 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:54:52 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens4f0
2022-03-28 02:54:52 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-28 02:55:00 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 mtu 1500
2022-03-28 02:55:00 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:55:08 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 2000
2022-03-28 02:55:11 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:55:19 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0
2022-03-28 02:55:19 - sshInstance.py - [line:54] - root - INFO - ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 24  bytes 9380 (9.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 64  bytes 18232 (18.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 02:55:28 - sshInstance.py - [line:75] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Mon Mar 28 03:05:58 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption. (Dot11)[0m
[39mINFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.5[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | We are in France, we say Skappee.[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | OK? Merci.[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |             -- Sebastien Chabal[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-03-28 02:55:28 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:55:35 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*18890)],iface="ens785f0")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-03-28 02:55:35 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:55:38 - test_mtu.py - [line:132] - root - INFO - success to send package to network
2022-03-28 02:55:42 - sshInstance.py - [line:75] - root - INFO - sendp([Ether(dst="b4:96:91:a0:21:40")/IP(len=46)/Raw(load='X'*20010)],iface="ens785f0")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 463, in sendp
    **kargs
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy/arch/linux.py", line 569, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy/supersocket.py", line 108, in send
    return self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-03-28 02:55:42 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:55:45 - test_mtu.py - [line:142] - root - INFO - result is right
.2022-03-28 02:55:48 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 mtu 1500
2022-03-28 02:55:48 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:55:57 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 mtu 1500
2022-03-28 02:56:00 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:56:08 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 02:56:08 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:56:16 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-28 02:56:16 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:56:21 - test_mtu.py - [line:51] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-28 02:56:21 - test_mtu.py - [line:53] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-28/test_PI_Networking_MTU_set_CVL_02_54_24
2022-03-28 02:56:24 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-03-28 02:56:24 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:56:29 - test_mtu.py - [line:55] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-28 02:56:29 - test_mtu.py - [line:56] - root - INFO - this is Test_Nics teardown
2022-03-28 02:56:29 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 50%]
npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-28 02:56:29 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-03-28 02:56:29 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-03-28/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]_02_56_29/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img].log, case_logdir: /root/testconfig/testlogs/2022-03-28/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]_02_56_29
2022-03-28 02:56:29 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
2022-03-28 02:56:29 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-28 02:56:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-28 02:56:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 02:56:30 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-28 02:56:30 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-28 02:56:30 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-28 02:56:30 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 02:56:30 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-28 02:56:30 - test_network_sriov_stress.py - [line:54] - root - INFO - start to rmmod irdma....
2022-03-28 02:56:33 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-03-28 02:56:33 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:56:38 - test_network_sriov_stress.py - [line:57] - root - INFO - finished rmmod irdma....
2022-03-28 02:56:38 - test_network_sriov_stress.py - [line:58] - root - INFO - start to rmmod ice....
2022-03-28 02:56:41 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-03-28 02:56:47 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:56:52 - test_network_sriov_stress.py - [line:61] - root - INFO - finished rmmod ice....
2022-03-28 02:56:52 - test_network_sriov_stress.py - [line:63] - root - INFO - start to modprobe ice....
2022-03-28 02:56:55 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-03-28 02:57:29 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:57:34 - test_network_sriov_stress.py - [line:65] - root - INFO - finished modprobe ice....
2022-03-28 02:57:37 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 up
2022-03-28 02:57:37 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:57:45 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens4f0
2022-03-28 02:57:45 - sshInstance.py - [line:54] - root - INFO - driver: ice
version: 5.15.0-1003-realtime
firmware-version: 3.10 0x8000ad67 1.3106.0
expansion-rom-version: 
bus-info: 0000:6f:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

2022-03-28 02:57:50 - test_network_sriov_stress.py - [line:75] - root - INFO - trying to get ipv6 addr for pf1
2022-03-28 02:57:53 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0
2022-03-28 02:57:53 - sshInstance.py - [line:54] - root - INFO - ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 2032 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 02:58:01 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-03-28 02:58:02 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 8348735969  bytes 12634867012016 (11.4 TiB)
        RX errors 0  dropped 6836  overruns 0  frame 0
        TX packets 98249564  bytes 6485535519 (6.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 02:58:07 - test_network_sriov_stress.py - [line:400] - root - INFO - 
Stress Disable and Enable for 1 time when VF is Assigned VM guest.

2022-03-28 02:58:10 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -s | grep ens4f0 | awk '{print $1;}'
2022-03-28 02:58:10 - sshInstance.py - [line:54] - root - INFO - 0000:6f:00.0

2022-03-28 02:58:15 - test_network_sriov_stress.py - [line:122] - root - INFO - pf_id was found: 0000:6f:00.0

2022-03-28 02:58:15 - test_network_sriov_stress.py - [line:408] - root - INFO - format_pf_id is 0000\:6f\:00.0

2022-03-28 02:58:15 - test_network_sriov_stress.py - [line:411] - root - INFO - pf_id_key: 6f
2022-03-28 02:58:15 - test_network_sriov_stress.py - [line:415] - root - INFO - start to assign ip for ens4f0 of SUT1: 192.168.10.10
2022-03-28 02:58:21 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:58:21 - sshInstance.py - [line:100] - root - INFO - Last login: Sun Mar 27 19:06:29 2022 from 10.112.97.60
RTNETLINK answers: File exists
[?2004hroot@npx-SPR-automation:~# ifconfig ens4f0 192.168.10.10
[?2004l[?2004hroot@npx-SPR-automation:~# 
2022-03-28 02:58:24 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: ens4f0
2022-03-28 02:58:24 - test_network_sriov_stress.py - [line:417] - root - INFO - start to assign ip for ens785f0 of SUT2: 192.168.10.11
2022-03-28 02:58:30 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 02:58:30 - sshInstance.py - [line:100] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 28 03:08:00 2022 from 10.112.97.60
xhost:  unable to open display ""
[root@CYP10RT ~]# ifconfig ens785f0 192.168.10.11
[root@CYP10RT ~]# 
2022-03-28 02:58:33 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: ens785f0
2022-03-28 02:58:36 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 02:58:40 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:58:45 - test_network_sriov_stress.py - [line:136] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-28 02:58:48 - sshInstance.py - [line:50] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-28 02:58:48 - sshInstance.py - [line:54] - root - INFO - 6f:01.0
6f:01.1
6f:01.2
6f:01.3

2022-03-28 02:58:53 - test_network_sriov_stress.py - [line:150] - root - INFO - Succssfully Gotten vf_id list:

2022-03-28 02:58:56 - sshInstance.py - [line:50] - root - INFO - modprobe vfio-pci

2022-03-28 02:58:56 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:59:04 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.0
2022-03-28 02:59:06 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:59:11 - test_network_sriov_stress.py - [line:183] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-28 02:59:14 - sshInstance.py - [line:50] - root - INFO - /root/dpdk-stable-20.11.3/usertools/dpdk-devbind.py -b vfio-pci 6f:01.1
2022-03-28 02:59:15 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 02:59:20 - test_network_sriov_stress.py - [line:183] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-28 02:59:20 - test_network_sriov_stress.py - [line:435] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-28 02:59:23 - sshInstance.py - [line:50] - root - INFO - lspci -Dnn | grep 6f:01.1
2022-03-28 02:59:23 - sshInstance.py - [line:54] - root - INFO - 0000:6f:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-28 02:59:28 - test_network_sriov_stress.py - [line:447] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-28 02:59:28 - test_network_sriov_stress.py - [line:206] - root - INFO - get default network info: virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-28 02:59:31 - sshInstance.py - [line:50] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-28 02:59:31 - sshInstance.py - [line:54] - root - INFO - yes

2022-03-28 02:59:36 - test_network_sriov_stress.py - [line:209] - root - INFO - Default network is active? yes

2022-03-28 02:59:36 - test_network_sriov_stress.py - [line:460] - root - INFO - start to create VMs....
2022-03-28 02:59:40 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_0 --boot hd --disk path=/home/image/uvm1.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5900 --noautoconsole
[?2004l
2022-03-28 02:59:43 - sshInstance.py - [line:75] - root - INFO - 
Starting install...
2022-03-28 02:59:47 - sshInstance.py - [line:75] - root - INFO - Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:00:13 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:00:16 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully created a VM: VMtest1
2022-03-28 03:00:20 - sshInstance.py - [line:75] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 --network network=default --hostdev pci_0000_6f_01_1 --boot hd --disk path=/home/image/uvm2.img,size=50,format=qcow2 --osinfo rhel8.2 --graphics vnc,listen=0.0.0.0,port=5901 --noautoconsole
[?2004l
2022-03-28 03:00:22 - sshInstance.py - [line:75] - root - INFO - 
Starting install...
2022-03-28 03:00:26 - sshInstance.py - [line:75] - root - INFO - Creating domain...                                          |    0 B  00:00     
Domain creation completed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:00:53 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:00:56 - test_network_sriov_stress.py - [line:247] - root - INFO - Successfully created a VM: VMtest2
2022-03-28 03:00:59 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-28 03:00:59 - sshInstance.py - [line:54] - root - INFO - 192.168.122.97/24

2022-03-28 03:01:04 - test_network_sriov_stress.py - [line:259] - root - INFO - Successfully got VMtest1 IP: 192.168.122.97/24

2022-03-28 03:01:07 - sshInstance.py - [line:50] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-28 03:01:08 - sshInstance.py - [line:54] - root - INFO - 192.168.122.117/24

2022-03-28 03:01:13 - test_network_sriov_stress.py - [line:259] - root - INFO - Successfully got VMtest2 IP: 192.168.122.117/24

2022-03-28 03:01:13 - test_network_sriov_stress.py - [line:470] - root - INFO - ip of VM1: 192.168.122.97
2022-03-28 03:01:13 - test_network_sriov_stress.py - [line:471] - root - INFO - ip of VM1: 192.168.122.117
2022-03-28 03:01:17 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.97
[?2004lPING 192.168.122.97 (192.168.122.97) 56(84) bytes of data.
64 bytes from 192.168.122.97: icmp_seq=1 ttl=64 time=0.280 ms
2022-03-28 03:01:18 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=2 ttl=64 time=0.188 ms
2022-03-28 03:01:19 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=3 ttl=64 time=0.178 ms
2022-03-28 03:01:20 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=4 ttl=64 time=0.186 ms
2022-03-28 03:01:21 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=5 ttl=64 time=0.191 ms

--- 192.168.122.97 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.178/0.204/0.280/0.037 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:01:52 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:01 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:01 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.97
[?2004lThe authenticity of host '192.168.122.97 (192.168.122.97)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (16 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-28 03:02:10 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:10 - sshInstance.py - [line:100] - root - INFO - yes
Warning: Permanently added '192.168.122.97' (ED25519) to the list of known hosts.
root@192.168.122.97's password: 
2022-03-28 03:02:20 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:20 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 03:12:21 PM EDT
  System load:  0.11               Processes:               175
  Usage of /:   39.1% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.97
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 02:51:51 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.5WFC2JjD9q which is empty
root@localhost:~# 
2022-03-28 03:02:29 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:29 - sshInstance.py - [line:100] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
2022-03-28 03:02:35 - test_network_sriov_stress.py - [line:355] - root - INFO - successfully got vf pci id of vm1: 0000:05:00.0
2022-03-28 03:02:41 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:41 - sshInstance.py - [line:100] - root - INFO - ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
2022-03-28 03:02:46 - test_network_sriov_stress.py - [line:369] - root - INFO - Successfully got vf device name of vm1: enp5s0
2022-03-28 03:02:52 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:02:52 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 192.168.10.12
root@localhost:~# 
2022-03-28 03:02:55 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: enp5s0
2022-03-28 03:03:01 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:03:01 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 down
root@localhost:~# 
2022-03-28 03:03:11 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:03:11 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 hw ether 1234567890ac
root@localhost:~# 
2022-03-28 03:03:20 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:03:20 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 up
root@localhost:~# 
2022-03-28 03:03:29 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:03:29 - sshInstance.py - [line:100] - root - INFO - nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
2022-03-28 03:03:38 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:03:38 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 8  bytes 2762 (2.7 KB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 21  bytes 2790 (2.7 KB)
        TX errors 1  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-28 03:03:47 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:03:47 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.97 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:03:54 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.117
[?2004lPING 192.168.122.117 (192.168.122.117) 56(84) bytes of data.
64 bytes from 192.168.122.117: icmp_seq=1 ttl=64 time=0.220 ms
2022-03-28 03:03:55 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.117: icmp_seq=2 ttl=64 time=0.191 ms
2022-03-28 03:03:56 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.117: icmp_seq=3 ttl=64 time=0.199 ms
2022-03-28 03:03:57 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.117: icmp_seq=4 ttl=64 time=0.182 ms
2022-03-28 03:03:58 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.117: icmp_seq=5 ttl=64 time=0.193 ms

--- 192.168.122.117 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4124ms
rtt min/avg/max/mdev = 0.182/0.197/0.220/0.012 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:04:29 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:04:38 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:04:38 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.117
[?2004lThe authenticity of host '192.168.122.117 (192.168.122.117)' can't be established.
ED25519 key fingerprint is SHA256:iwdy+msopcBky5vcy4vHK28+vCfb0ZylVCAr9Baaikk.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:7: [hashed name]
    ~/.ssh/known_hosts:10: [hashed name]
    ~/.ssh/known_hosts:11: [hashed name]
    ~/.ssh/known_hosts:12: [hashed name]
    ~/.ssh/known_hosts:13: [hashed name]
    ~/.ssh/known_hosts:14: [hashed name]
    ~/.ssh/known_hosts:15: [hashed name]
    ~/.ssh/known_hosts:16: [hashed name]
    (17 additional names omitted)
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-28 03:04:47 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:04:47 - sshInstance.py - [line:100] - root - INFO - yes
Warning: Permanently added '192.168.122.117' (ED25519) to the list of known hosts.
root@192.168.122.117's password: 
2022-03-28 03:04:57 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:04:57 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 03:14:58 PM EDT
  System load:  0.04               Processes:               170
  Usage of /:   39.2% of 19.07GB   Users logged in:         0
  Memory usage: 4%                 IPv4 address for enp1s0: 192.168.122.117
  Swap usage:   0%

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 02:50:54 2022 from 192.168.122.1
cmp: EOF on /tmp/tmp.i7kQHlGtvA which is empty
root@localhost:~# 
2022-03-28 03:05:06 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:05:06 - sshInstance.py - [line:100] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:05:00.0
root@localhost:~# 
2022-03-28 03:05:12 - test_network_sriov_stress.py - [line:355] - root - INFO - successfully got vf pci id of vm1: 0000:05:00.0
2022-03-28 03:05:18 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:05:18 - sshInstance.py - [line:100] - root - INFO - ls /sys/bus/pci/devices/0000\:05\:00.0/net/ --color=never
enp5s0
root@localhost:~# 
2022-03-28 03:05:23 - test_network_sriov_stress.py - [line:369] - root - INFO - Successfully got vf device name of vm1: enp5s0
2022-03-28 03:05:29 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:05:29 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 192.168.10.13
root@localhost:~# 
2022-03-28 03:05:32 - test_network_sriov_stress.py - [line:316] - root - INFO - Successfully assigned ip to ethernet: enp5s0
2022-03-28 03:05:38 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:05:38 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 down
root@localhost:~# 
2022-03-28 03:05:48 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:05:48 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 hw ether 1234567890ab
root@localhost:~# 
2022-03-28 03:05:57 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:05:57 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0 up
root@localhost:~# 
2022-03-28 03:06:06 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:06:06 - sshInstance.py - [line:100] - root - INFO - nmcli device connect enp5s0
Error: Failed to add/activate new connection: Connection 'enp5s0' is not available on device enp5s0 because device is strictly unmanaged
root@localhost:~# 
2022-03-28 03:06:15 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:06:15 - sshInstance.py - [line:100] - root - INFO - ifconfig enp5s0
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 2  bytes 688 (688.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 1932 (1.9 KB)
        TX errors 1  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-28 03:06:24 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:06:24 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.117 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:06:27 - test_network_sriov_stress.py - [line:489] - root - INFO - Ping two vms IP from SUT:
2022-03-28 03:06:31 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.12
[?2004lPING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.933 ms
2022-03-28 03:06:32 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.143 ms
2022-03-28 03:06:33 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.117 ms
2022-03-28 03:06:34 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.129 ms
2022-03-28 03:06:35 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.179 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.117/0.300/0.933/0.317 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:07:06 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:07:13 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.13
[?2004lPING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.888 ms
2022-03-28 03:07:14 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.151 ms
2022-03-28 03:07:15 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.156 ms
2022-03-28 03:07:16 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.177 ms
2022-03-28 03:07:17 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.237 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4089ms
rtt min/avg/max/mdev = 0.151/0.321/0.888/0.284 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:07:48 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:07:51 - test_network_sriov_stress.py - [line:497] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-28 03:07:55 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.122.97
[?2004lPING 192.168.122.97 (192.168.122.97) 56(84) bytes of data.
64 bytes from 192.168.122.97: icmp_seq=1 ttl=64 time=0.293 ms
2022-03-28 03:07:56 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=2 ttl=64 time=0.199 ms
2022-03-28 03:07:57 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=3 ttl=64 time=0.190 ms
2022-03-28 03:07:58 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=4 ttl=64 time=0.185 ms
2022-03-28 03:07:59 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.122.97: icmp_seq=5 ttl=64 time=0.189 ms

--- 192.168.122.97 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.185/0.211/0.293/0.041 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:08:30 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:08:39 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:08:39 - sshInstance.py - [line:100] - root - INFO - ssh root@192.168.122.97
[?2004lroot@192.168.122.97's password: 
2022-03-28 03:08:49 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:08:49 - sshInstance.py - [line:100] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Sun 27 Mar 2022 03:18:50 PM EDT
  System load:  0.08               Processes:               153
  Usage of /:   39.1% of 19.07GB   Users logged in:         0
  Memory usage: 5%                 IPv4 address for enp1s0: 192.168.122.97
  Swap usage:   0%                 IPv4 address for enp5s0: 192.168.10.12

381 updates can be installed immediately.
261 of these updates are security updates.
To see these additional updates run: apt list --upgradable
Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings

Last login: Sun Mar 27 15:12:21 2022 from 192.168.122.1
RTNETLINK answers: File exists
root@localhost:~# 
2022-03-28 03:08:56 - sshInstance.py - [line:75] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=7.76 ms
2022-03-28 03:08:57 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.242 ms
2022-03-28 03:08:58 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.395 ms
2022-03-28 03:08:59 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.248 ms
2022-03-28 03:09:00 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.316 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4073ms
rtt min/avg/max/mdev = 0.242/1.791/7.755/2.982 ms
root@localhost:~# 
2022-03-28 03:09:31 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:09:40 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:09:40 - sshInstance.py - [line:100] - root - INFO - exit
logout
Connection to 192.168.122.97 closed.
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:09:43 - test_network_sriov_stress.py - [line:505] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-28 03:09:47 - sshInstance.py - [line:75] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
[?2004lPING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.892 ms
2022-03-28 03:09:48 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.196 ms
2022-03-28 03:09:49 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.202 ms
2022-03-28 03:09:50 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.199 ms
2022-03-28 03:09:51 - sshInstance.py - [line:75] - root - INFO - 64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.200 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4123ms
rtt min/avg/max/mdev = 0.196/0.337/0.892/0.277 ms
[?2004hroot@npx-SPR-automation:~# 
2022-03-28 03:10:22 - sshInstance.py - [line:98] - root - INFO - --cmd is end--
2022-03-28 03:10:28 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 03:10:33 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:10:38 - test_network_sriov_stress.py - [line:278] - root - INFO - Successfully removed VFs from PF.
2022-03-28 03:10:41 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest1
2022-03-28 03:10:43 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest1' destroyed


2022-03-28 03:10:48 - test_network_sriov_stress.py - [line:291] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-28 03:10:51 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest1
2022-03-28 03:10:51 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest1' has been undefined


2022-03-28 03:10:56 - test_network_sriov_stress.py - [line:301] - root - INFO - Successfully removed the VM: VMtest1
2022-03-28 03:10:59 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest2
2022-03-28 03:11:00 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest2' destroyed


2022-03-28 03:11:05 - test_network_sriov_stress.py - [line:291] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-28 03:11:08 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest2
2022-03-28 03:11:09 - sshInstance.py - [line:54] - root - INFO - Domain 'VMtest2' has been undefined


2022-03-28 03:11:14 - test_network_sriov_stress.py - [line:301] - root - INFO - Successfully removed the VM: VMtest2
.2022-03-28 03:11:14 - test_network_sriov_stress.py - [line:84] - root - INFO - removing VMs: VMtest1, VMtest2
2022-03-28 03:11:17 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest2
2022-03-28 03:11:17 - sshInstance.py - [line:54] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-28 03:11:22 - test_network_sriov_stress.py - [line:291] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-28 03:11:25 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest2
2022-03-28 03:11:25 - sshInstance.py - [line:54] - root - INFO - error: failed to get domain 'VMtest2'


2022-03-28 03:11:30 - test_network_sriov_stress.py - [line:304] - root - ERROR - Failed to removed the VM VMtest2
2022-03-28 03:11:33 - sshInstance.py - [line:50] - root - INFO - virsh destroy VMtest1
2022-03-28 03:11:33 - sshInstance.py - [line:54] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-28 03:11:38 - test_network_sriov_stress.py - [line:291] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-28 03:11:41 - sshInstance.py - [line:50] - root - INFO - virsh undefine VMtest1
2022-03-28 03:11:41 - sshInstance.py - [line:54] - root - INFO - error: failed to get domain 'VMtest1'


2022-03-28 03:11:46 - test_network_sriov_stress.py - [line:304] - root - ERROR - Failed to removed the VM VMtest1
2022-03-28 03:11:49 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 03:11:49 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:11:57 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 0
2022-03-28 03:11:57 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:12:05 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 0
2022-03-28 03:12:05 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:12:13 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-28 03:12:13 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:12:18 - test_network_sriov_stress.py - [line:93] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-28 03:12:18 - test_network_sriov_stress.py - [line:95] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-28/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img]_02_56_29
2022-03-28 03:12:21 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-03-28 03:12:21 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:12:26 - test_network_sriov_stress.py - [line:97] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-28 03:12:26 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-03-28 03:12:26 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm1.img-uvm2.img] case ============================
                  [ 75%]
npxtester/Tests/testNics/test_nics.py 2022-03-28 03:12:26 - NicTestFixture.py - [line:20] - root - INFO - test -------
2022-03-28 03:12:26 - NicTestFixture.py - [line:27] - root - INFO - case_logpath: /root/testconfig/testlogs/2022-03-28/test_gold_PI_Networking_SRIOV_CheckDevice_03_12_26/test_gold_PI_Networking_SRIOV_CheckDevice.log, case_logdir: /root/testconfig/testlogs/2022-03-28/test_gold_PI_Networking_SRIOV_CheckDevice_03_12_26
2022-03-28 03:12:26 - NicTestFixture.py - [line:31] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-28 03:12:26 - test_nics.py - [line:21] - root - INFO - this is Test_Nics setup.
2022-03-28 03:12:26 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.8p1)
2022-03-28 03:12:26 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 03:12:27 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.183.130
2022-03-28 03:12:27 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-28 03:12:27 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-28 03:12:27 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.239.182.88
2022-03-28 03:12:27 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-28 03:12:27 - test_nics.py - [line:31] - root - INFO - --Start rmmod irdma --
2022-03-28 03:12:30 - sshInstance.py - [line:50] - root - INFO - rmmod irdma
2022-03-28 03:12:30 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:12:35 - test_nics.py - [line:33] - root - INFO - --Finish rmmod irdma --
2022-03-28 03:12:35 - test_nics.py - [line:34] - root - INFO - --Start rmmod ice --
2022-03-28 03:12:38 - sshInstance.py - [line:50] - root - INFO - rmmod ice
2022-03-28 03:12:44 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:12:49 - test_nics.py - [line:36] - root - INFO - --Finish rmmod ice --
2022-03-28 03:12:49 - test_nics.py - [line:37] - root - INFO - --Start modprobe ice --
2022-03-28 03:12:52 - sshInstance.py - [line:50] - root - INFO - modprobe ice
2022-03-28 03:13:26 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:13:31 - test_nics.py - [line:39] - root - INFO - --Finish modprobe ice --
2022-03-28 03:13:34 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 up
2022-03-28 03:13:34 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:13:42 - sshInstance.py - [line:50] - root - INFO - ethtool -i ens4f0 | grep ^version:
2022-03-28 03:13:42 - sshInstance.py - [line:54] - root - INFO - version: 5.15.0-1003-realtime

2022-03-28 03:13:50 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0
2022-03-28 03:13:50 - sshInstance.py - [line:54] - root - INFO - ens4f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2140  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:40  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 2032 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 03:13:58 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0
2022-03-28 03:13:58 - sshInstance.py - [line:54] - root - INFO - ens785f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea0:2170  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a0:21:70  txqueuelen 1000  (Ethernet)
        RX packets 8348736074  bytes 12634867030662 (11.4 TiB)
        RX errors 0  dropped 6836  overruns 0  frame 0
        TX packets 98249597  bytes 6485543177 (6.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-28 03:14:06 - sshInstance.py - [line:50] - root - INFO - echo 4 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 03:14:10 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:14:18 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 192.168.10.11

2022-03-28 03:14:19 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:14:27 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v0 192.168.10.11
2022-03-28 03:14:27 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:14:35 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v1 192.168.10.12
2022-03-28 03:14:35 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:14:43 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v2 192.168.10.13
2022-03-28 03:14:43 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:14:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v3 192.168.10.14
2022-03-28 03:14:51 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:14:59 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11
2022-03-28 03:15:03 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.046 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.038 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.055 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.044 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4112ms
rtt min/avg/max/mdev = 0.038/0.046/0.055/0.005 ms

2022-03-28 03:15:11 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v0 up
2022-03-28 03:15:11 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:15:19 - sshInstance.py - [line:50] - root - INFO - nmcli device connect ens4f0v0
2022-03-28 03:15:19 - sshInstance.py - [line:54] - root - INFO - bash: line 1: nmcli: command not found

2022-03-28 03:15:27 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens4f0v0 fe80::b696:91ff:fea0:2170
2022-03-28 03:15:31 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than: ens4f0v0
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens4f0v0: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v0: icmp_seq=1 ttl=64 time=0.383 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v0: icmp_seq=2 ttl=64 time=0.178 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v0: icmp_seq=3 ttl=64 time=0.173 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v0: icmp_seq=4 ttl=64 time=0.169 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v0: icmp_seq=5 ttl=64 time=0.163 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.163/0.213/0.383/0.085 ms

2022-03-28 03:15:39 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11
2022-03-28 03:15:43 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.042 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.042 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.045 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.044 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.042 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.042/0.043/0.045/0.001 ms

2022-03-28 03:15:51 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v1 up
2022-03-28 03:15:51 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:15:59 - sshInstance.py - [line:50] - root - INFO - nmcli device connect ens4f0v1
2022-03-28 03:15:59 - sshInstance.py - [line:54] - root - INFO - bash: line 1: nmcli: command not found

2022-03-28 03:16:07 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens4f0v1 fe80::b696:91ff:fea0:2170
2022-03-28 03:16:11 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than: ens4f0v1
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens4f0v1: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v1: icmp_seq=1 ttl=64 time=0.349 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v1: icmp_seq=2 ttl=64 time=0.166 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v1: icmp_seq=3 ttl=64 time=0.154 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v1: icmp_seq=4 ttl=64 time=0.166 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v1: icmp_seq=5 ttl=64 time=0.163 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4080ms
rtt min/avg/max/mdev = 0.154/0.199/0.349/0.074 ms

2022-03-28 03:16:19 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11
2022-03-28 03:16:23 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.040 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.038 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.034 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.048 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4131ms
rtt min/avg/max/mdev = 0.034/0.040/0.048/0.004 ms

2022-03-28 03:16:31 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v2 up
2022-03-28 03:16:31 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:16:39 - sshInstance.py - [line:50] - root - INFO - nmcli device connect ens4f0v2
2022-03-28 03:16:39 - sshInstance.py - [line:54] - root - INFO - bash: line 1: nmcli: command not found

2022-03-28 03:16:47 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens4f0v2 fe80::b696:91ff:fea0:2170
2022-03-28 03:16:52 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than: ens4f0v2
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens4f0v2: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v2: icmp_seq=1 ttl=64 time=0.389 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v2: icmp_seq=2 ttl=64 time=0.169 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v2: icmp_seq=3 ttl=64 time=0.172 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v2: icmp_seq=4 ttl=64 time=0.183 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v2: icmp_seq=5 ttl=64 time=0.164 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4079ms
rtt min/avg/max/mdev = 0.164/0.215/0.389/0.087 ms

2022-03-28 03:17:00 - sshInstance.py - [line:50] - root - INFO - ping -c 5 192.168.10.11
2022-03-28 03:17:04 - sshInstance.py - [line:54] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.039 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.022 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.033 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.030 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4130ms
rtt min/avg/max/mdev = 0.022/0.033/0.044/0.007 ms

2022-03-28 03:17:12 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0v3 up
2022-03-28 03:17:12 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:17:20 - sshInstance.py - [line:50] - root - INFO - nmcli device connect ens4f0v3
2022-03-28 03:17:20 - sshInstance.py - [line:54] - root - INFO - bash: line 1: nmcli: command not found

2022-03-28 03:17:28 - sshInstance.py - [line:50] - root - INFO - ping6 -c 5 -I ens4f0v3 fe80::b696:91ff:fea0:2170
2022-03-28 03:17:32 - sshInstance.py - [line:54] - root - INFO - ping6: Warning: source address might be selected on device other than: ens4f0v3
PING fe80::b696:91ff:fea0:2170(fe80::b696:91ff:fea0:2170) from :: ens4f0v3: 56 data bytes
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v3: icmp_seq=1 ttl=64 time=0.421 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v3: icmp_seq=2 ttl=64 time=0.189 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v3: icmp_seq=3 ttl=64 time=0.184 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v3: icmp_seq=4 ttl=64 time=0.177 ms
64 bytes from fe80::b696:91ff:fea0:2170%ens4f0v3: icmp_seq=5 ttl=64 time=0.170 ms

--- fe80::b696:91ff:fea0:2170 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4078ms
rtt min/avg/max/mdev = 0.170/0.228/0.421/0.096 ms

.2022-03-28 03:17:40 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 03:17:48 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:17:56 - sshInstance.py - [line:50] - root - INFO - echo 0 > /sys/class/net/ens4f0/device/sriov_numvfs
2022-03-28 03:17:56 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:18:04 - sshInstance.py - [line:50] - root - INFO - ifconfig ens4f0 0
2022-03-28 03:18:04 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:18:12 - sshInstance.py - [line:50] - root - INFO - ifconfig ens785f0 0
2022-03-28 03:18:12 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:18:20 - sshInstance.py - [line:50] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-28 03:18:20 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:18:25 - test_nics.py - [line:71] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-28 03:18:25 - test_nics.py - [line:73] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-28/test_gold_PI_Networking_SRIOV_CheckDevice_03_12_26
2022-03-28 03:18:28 - sshInstance.py - [line:50] - root - INFO - rm -f /tmp/dmesg.log
2022-03-28 03:18:28 - sshInstance.py - [line:54] - root - INFO - 
2022-03-28 03:18:33 - test_nics.py - [line:75] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-28 03:18:33 - sshInstance.py - [line:43] - root - INFO - closing ssh client on SUT
2022-03-28 03:18:33 - test_nics.py - [line:77] - root - INFO - this is Test_Nics teardown
2022-03-28 03:18:33 - NicTestFixture.py - [line:35] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
                                  [100%]

=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:74
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_iperf_client_4hour.py:74: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:121
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_iperf_client_4hour.py:121: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:396
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:396: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:521
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:521: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:829
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_network_sriov_stress.py:829: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:84
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:84: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:111
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:111: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:141
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:141: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:212
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:212: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:238
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:238: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:281
  /root/.jenkins/workspace/spr-test-nicGold/npxtester/Tests/testNics/test_nics.py:281: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nicGold_report.html -
========== 4 passed, 13 deselected, 15 warnings in 1567.37s (0:26:07) ==========
[8mha:////4DDaF6xD1n97fCJC17HEPtC4MvFSxjBMoUPdpyGs71EZAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIioEIoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDREKHeHXPvt8AGMzKKgvgAAAA==[0m[Pipeline] echo
0
[8mha:////4JdwCG2vyNU1vR63Cq0h1I9fweuZdBzoUYFbNZMa07ZpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIihQohqrRWGl5gYmOcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThwM9poGS7Gz6N1o8sKJw3B1PGHPF+yYIjuNrZ5aVrpZsOWkYUlRwkrARlPnOFoyCbailw9ZOUmmOqeQv6OA0qo7PKEQ2ZxkSF+YA+xuo4pMP89fAcw+QVkfcu1r/wFPn4+LvgAAAA==[0m[Pipeline] sh
+ sed -i $'s/\r//g' /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4J0lAWMm8HuBR5s3oE3lokuIt9KB2+AHQUkjEiJ+aQGpAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPMKRSIUQVVorDS8w8WGcWHfGdkgqXsTX+AMWkajYYrWzzbzesI4BThyM6JEGS7GzwrvR5CUmDsPV8SR6voiOKbJD0eLUssZmwZYTwpKihJWEDVLnOFoyCbayVw9VOUWmOqeQv6OE0uo7PKGQ2ZxUSF+YA+xuo45MP89fAcw+Qbk/5Kpr/wEOrpSSvgAAAA==[0m[Pipeline] sh
+ chmod a+x /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4Mt0DSsxkJzZfVcF7hGhEOllvDy/ttdaA/Rf0YiZvcahAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiAQ1CqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKYhQrk95Nrthw/JONXdvgAAAA==[0m[Pipeline] sh
+ sh /root/.jenkins/workspace/spr-test-nicGold/npxtester/log_analyzer/log_analyzer.sh
[8mha:////4BJ3niM699yfMaO4XlYckMNVxHBxF/A/6tXrT01aXGOTAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigSgQSkVrueEFJjHGiXUXbAen4kV8jT9gEYmKLVY728zrDcvgoWZvsNPUWwqNxcGNJi9M7Pur44QdX7BhCuw0Sp0kt/o0o+SoYU5RwkLASlPjOFgyEdaiUw9VOUWmOkefv6OA0rZ3eEIhsjkqH78wedjcxjYw/Tx/BTANQ4Ryt8+1PXwARMxJg74AAAA=[0m[Pipeline] }
[8mha:////4KLOGR+83vgrLFidGueNeEu4h+87+yS5qW1q0kigPKEkAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu32u7eEDfI7acr4AAAA=[0m[Pipeline] // script
[8mha:////4B/bjeg5xruNbbx3kITLupXWvVAJcKllvbrOrw34K5MTAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiQZECUaW10vACExvjxLoztkNS8SK+xh+wiETFFqudbeb1hnUMcOJgsNc0WIqdRe9GkxdOHIar4wl7vmDHFNlpbPXUstLNgi0nDUuKElYCNpo6x9GSSbAVvXzIykky1TmF/B0FlFbd4QmFyOYkQ/rCHGB3G1Vk+nn+CmD2PkF5qHPt6w9IQDkpvgAAAA==[0m[Pipeline] }
[8mha:////4Pysn2p6Cuaw38A5WKCzX3hZbaQrVsudvseeZZRTcVjBAAAAph+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIigYSQUCpayw0vMIkxTqy7YDs4FS/ia/wBi0hUbLHa2WZeb1gGDzV7g52m3lJoLA5uNHlhYt9fHSfs+IINU2CnUeokudWnGSVHDXOKEhYCVpoax8GSibAWnXqoyiky1Tn6/B0FlLa9wxMKkc1R+fiFycPmNraB6ef5K4BpGCKUu0Ou7f4DC8Jor74AAAA=[0m[Pipeline] // stage
[8mha:////4AtNwyaW/AZqBd3OKxZrkWfAC6zB3HxngMFQ9sJmqFs1AAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIpoEGIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsP/+idkr0AAAA=[0m[Pipeline] }
[8mha:////4I5dJP3UyABwbWbQZBRGWAtgfXC/GfHsQ3SW1rlV0+rIAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBgg5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBlS/sHL0AAAA=[0m[Pipeline] // node
[8mha:////4OCxxHdXTRYePL6pNSOSjI/nVmiKF6Ardumg4UkWHzykAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77eCbPcBszaLVr0AAAA=[0m[Pipeline] End of Pipeline
Finished: SUCCESS
