Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-simple
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-simple/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-simple/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/intel-innersource/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (set args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-simple/npxtester/conf/change_args.py '{"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","sut_conf":{"kernel_type":"generic","board_type":"commerical","host":"10.112.97.62","pf1":"ens2f0","pf1_ipv6":"fe80::b696:91ff:fe9c:f7a4","os":"RHEL","PF1_NIC_type":"4*25"},"sut2_conf":{"host":"10.112.97.60","pf1":"ens2f1","pf1_ipv6":"fe80::b696:91ff:fea5:9b45"},"drive_info":{"drive_version":"1.6.4"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics -s -m nicSimple --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_simple_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 16 items / 9 deselected / 7 selected

npxtester/Tests/testNics/test_mtu.py 2022-03-04 13:03:14 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-04 13:03:14 - test_mtu.py - [line:18] - root - INFO - this is Test_mtu setup.
2022-03-04 13:03:14 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:03:14 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:03:14 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:03:14 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:03:14 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:03:14 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:03:14 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:03:17 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:03:17 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:03:25 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:03:30 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:03:38 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:03:43 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:03:51 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:03:51 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:03:59 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 mtu 1500
2022-03-04 13:03:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:04:07 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 mtu 1500
2022-03-04 13:04:07 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:04:15 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-04 13:04:15 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-04 13:04:24 - sshInstance.py - [line:71] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Mar  4 11:07:02 2022 from 10.238.4.27
[root@localhost ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[33m[1mWARNING: No route found for IPv6 destination :: (no default route?)[0m[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.3[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Wanna support scapy? Rate it on[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   | sectools![0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   | http://sectools.org/tool/scapy/[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m[34m[1m   |             -- Satoshi Nakamoto[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m[34m[1m   |[0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-03-04 13:04:31 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:9c:f7:a4")/IP(len=46)/Raw(load='X'*14480)],iface="ens2f1")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-03-04 13:04:34 - test_mtu.py - [line:93] - root - INFO - success to send package to network
2022-03-04 13:04:38 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:9c:f7:a4")/IP(len=46)/Raw(load='X'*15500)],iface="ens2f1")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/sendrecv.py", line 338, in sendp
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/sendrecv.py", line 291, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/arch/linux.py", line 559, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/supersocket.py", line 49, in send
    sent = self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-03-04 13:04:41 - test_mtu.py - [line:103] - root - INFO - result is right
.2022-03-04 13:04:44 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 mtu 1500
2022-03-04 13:04:44 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:04:52 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 mtu 1500
2022-03-04 13:04:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:05:00 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-04 13:05:00 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:05:08 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:05:08 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:05:13 - test_mtu.py - [line:54] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:05:13 - test_mtu.py - [line:56] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_PI_Networking_Jumbo_Packet_CVL_13_03_14
2022-03-04 13:05:16 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:05:16 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:05:21 - test_mtu.py - [line:58] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:05:21 - test_mtu.py - [line:59] - root - INFO - this is Test_Nics teardown
2022-03-04 13:05:21 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_Jumbo_Packet_CVL case ============================
2022-03-04 13:05:21 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_MTU_set_CVL case ============================
2022-03-04 13:05:21 - test_mtu.py - [line:18] - root - INFO - this is Test_mtu setup.
2022-03-04 13:05:21 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:05:21 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:05:22 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:05:22 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:05:22 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:05:22 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:05:22 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:05:25 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:05:25 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:05:33 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:05:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:05:45 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:05:50 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:05:58 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:05:58 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:06:06 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 mtu 1500
2022-03-04 13:06:06 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:06:14 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 mtu 2000
2022-03-04 13:06:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:06:22 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-04 13:06:23 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-04 13:06:32 - sshInstance.py - [line:71] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket

This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register

Last login: Fri Mar  4 13:04:52 2022 from 10.112.97.60
[root@localhost ~]# scapy
[39mINFO: Can't import matplotlib. Won't be able to plot.[0m
[39mINFO: Can't import PyX. Won't be able to use psdump() or pdfdump().[0m
[33m[1mWARNING: No route found for IPv6 destination :: (no default route?)[0m[0m
[33m[1mWARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.[0m[0m
[32m[1m                                      [0m[34m[1m[0m
[32m[1m                     aSPY//YASa       [0m[34m[1m[0m
[32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
[32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
[32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 2.4.3[0m
[32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
[32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
[32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
[32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
[32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
[32m[1m              P////YCpc           A//A[0m[34m[1m   | Craft me if you can.[0m
[32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   |                   -- IPv6 layer[0m
[32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |[0m
[32m[1m       cayCyayP//Ya              pY/Ya[0m
[32m[1m        sY/PsY////YCc          aC//Yp [0m
[32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
[32m[1m                  spCPY//////YPSps    [0m
[32m[1m                       ccaacs         [0m
[32m[1m                                      [0m
[34m[1m>>> [0m
2022-03-04 13:06:39 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:9c:f7:a4")/IP(len=46)/Raw(load='X'*18890)],iface="ens2f1")
.
Sent 1 packets.
[34m[1m>>> [0m
2022-03-04 13:06:42 - test_mtu.py - [line:132] - root - INFO - success to send package to network
2022-03-04 13:06:46 - sshInstance.py - [line:71] - root - INFO - sendp([Ether(dst="b4:96:91:9c:f7:a4")/IP(len=46)/Raw(load='X'*20010)],iface="ens2f1")
Traceback (most recent call last):
  File "/usr/lib64/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/sendrecv.py", line 338, in sendp
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/sendrecv.py", line 291, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/arch/linux.py", line 559, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python3.6/site-packages/scapy-2.4.3-py3.6.egg/scapy/supersocket.py", line 49, in send
    sent = self.outs.send(sx)
OSError: [Errno 90] Message too long
[34m[1m>>> [0m
2022-03-04 13:06:49 - test_mtu.py - [line:142] - root - INFO - result is right
.2022-03-04 13:06:52 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 mtu 1500
2022-03-04 13:06:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:00 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 mtu 1500
2022-03-04 13:07:00 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:08 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-04 13:07:08 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:16 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:07:16 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:21 - test_mtu.py - [line:54] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:07:21 - test_mtu.py - [line:56] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_PI_Networking_MTU_set_CVL_13_05_21
2022-03-04 13:07:24 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:07:24 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:29 - test_mtu.py - [line:58] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:07:29 - test_mtu.py - [line:59] - root - INFO - this is Test_Nics teardown
2022-03-04 13:07:29 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_MTU_set_CVL case ============================
                                  [ 28%]
npxtester/Tests/testNics/test_nics.py 2022-03-04 13:07:29 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-03-04 13:07:29 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:07:29 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:07:30 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:07:30 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:07:33 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:07:33 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:07:41 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:07:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:53 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:07:58 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:08:06 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:08:06 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:08:17 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Mar  4 13:15:25 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.122.2
[root@WW25ICX2 ~]# 
2022-03-04 13:08:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.
64 bytes from 192.168.122.1: icmp_seq=1 ttl=64 time=0.030 ms
2022-03-04 13:08:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=2 ttl=64 time=0.049 ms
2022-03-04 13:08:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=3 ttl=64 time=0.049 ms
2022-03-04 13:08:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=4 ttl=64 time=0.049 ms
2022-03-04 13:08:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=5 ttl=64 time=0.050 ms

--- 192.168.122.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.030/0.045/0.050/0.009 ms
[root@WW25ICX2 ~]# 
2022-03-04 13:08:37 - sshInstance.py - [line:94] - root - INFO - ifconfig vnet1 down
vnet1: ERROR while getting interface flags: No such device
[root@WW25ICX2 ~]# 
F2022-03-04 13:08:43 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:08:43 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:08:51 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:08:51 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:08:59 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:08:59 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:09:04 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:09:04 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:09:04 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:09:04 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:09:07 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:09:08 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:09:16 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:09:16 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:09:24 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:09:24 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:09:29 - test_nics.py - [line:68] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:09:29 - test_nics.py - [line:70] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_silver_Networking_ConnectivityEnableDisable_13_07_29
2022-03-04 13:09:32 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:09:32 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:09:37 - test_nics.py - [line:72] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:09:37 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-04 13:09:37 - test_nics.py - [line:74] - root - INFO - this is Test_Nics teardown
2022-03-04 13:09:37 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-03-04 13:09:37 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-03-04 13:09:37 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:09:37 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:09:37 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:09:37 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:09:40 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:09:40 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:09:48 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:09:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:10:00 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:10:05 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:10:13 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:10:14 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:10:19 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:10:19 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:10:19 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:10:25 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Mar  4 13:18:14 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.122.2
[root@WW25ICX2 ~]# 
2022-03-04 13:10:32 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.
64 bytes from 192.168.122.1: icmp_seq=1 ttl=64 time=0.040 ms
2022-03-04 13:10:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=2 ttl=64 time=0.034 ms
2022-03-04 13:10:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=3 ttl=64 time=0.050 ms
2022-03-04 13:10:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=4 ttl=64 time=0.051 ms
2022-03-04 13:10:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=5 ttl=64 time=0.027 ms

--- 192.168.122.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4106ms
rtt min/avg/max/mdev = 0.027/0.040/0.051/0.010 ms
[root@WW25ICX2 ~]# 
2022-03-04 13:10:43 - sshInstance.py - [line:71] - root - INFO - ping6 -c 5 -I vnet1 fe80::fc10:23ff:fe91:1512
ping: unknown iface vnet1
[root@WW25ICX2 ~]# 
F2022-03-04 13:10:49 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:10:49 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:10:57 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:10:57 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:11:05 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:11:05 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:11:10 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:11:10 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:11:10 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:11:10 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:11:13 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:11:13 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:11:21 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:11:21 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:11:29 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:11:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:11:34 - test_nics.py - [line:68] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:11:34 - test_nics.py - [line:70] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_silver_ConnectivityReboot_13_09_37
2022-03-04 13:11:37 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:11:37 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:11:42 - test_nics.py - [line:72] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:11:42 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-04 13:11:42 - test_nics.py - [line:74] - root - INFO - this is Test_Nics teardown
2022-03-04 13:11:42 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_silver_ConnectivityReboot case ============================
2022-03-04 13:11:42 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-04 13:11:42 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:11:42 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:11:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:11:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:11:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:11:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:11:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:11:43 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:11:46 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:11:46 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:11:54 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:11:58 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:12:06 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:12:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:12:19 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:12:19 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:12:27 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:12:27 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

F2022-03-04 13:12:35 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:12:35 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:12:43 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:12:43 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:12:51 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:12:51 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:12:56 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:12:57 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:12:57 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:12:57 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:13:00 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:13:00 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:13:08 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:13:08 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:13:16 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:13:16 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:13:21 - test_nics.py - [line:68] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:13:21 - test_nics.py - [line:70] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_gold_PI_Networking_SRIOV_CheckDevice_13_11_42
2022-03-04 13:13:24 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:13:24 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:13:29 - test_nics.py - [line:72] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:13:29 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-04 13:13:29 - test_nics.py - [line:74] - root - INFO - this is Test_Nics teardown
2022-03-04 13:13:29 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-04 13:13:29 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_InternetProtocolv4v6_CVL case ============================
2022-03-04 13:13:29 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:13:29 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:13:29 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:13:29 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:13:32 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:13:32 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:13:40 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:13:44 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:13:52 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:13:57 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:14:05 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:14:06 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:14:14 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 192.168.10.10
2022-03-04 13:14:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:14:22 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 192.168.10.11
2022-03-04 13:14:22 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:14:30 - sshInstance.py - [line:46] - root - INFO - ping -w 5 192.168.10.11
2022-03-04 13:14:35 - sshInstance.py - [line:50] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.322 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.300 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.294 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.263 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.243 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.243/0.284/0.322/0.031 ms

2022-03-04 13:14:43 - sshInstance.py - [line:46] - root - INFO - ping6 -c 5 -I ens2f0 fe80::fc10:23ff:fe91:1512
2022-03-04 13:14:49 - sshInstance.py - [line:50] - root - INFO - ping6: Warning: source address might be selected on device other than ens2f0.
PING fe80::fc10:23ff:fe91:1512(fe80::fc10:23ff:fe91:1512) from :: ens2f0: 56 data bytes
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=1 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=2 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=3 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=4 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=5 Destination unreachable: Address unreachable

--- fe80::fc10:23ff:fe91:1512 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4121ms
pipe 3

F2022-03-04 13:14:57 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:14:57 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:15:05 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:15:05 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:15:13 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:15:13 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:15:18 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:15:18 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:15:18 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:15:18 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:15:21 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:15:21 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:15:30 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:15:30 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:15:38 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:15:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:15:43 - test_nics.py - [line:68] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:15:43 - test_nics.py - [line:70] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_PI_Networking_InternetProtocolv4v6_CVL_13_13_29
2022-03-04 13:15:46 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:15:46 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:15:51 - test_nics.py - [line:72] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:15:51 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-04 13:15:51 - test_nics.py - [line:74] - root - INFO - this is Test_Nics teardown
2022-03-04 13:15:51 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_InternetProtocolv4v6_CVL case ============================
2022-03-04 13:15:51 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_Link_State_Check_CVL case ============================
2022-03-04 13:15:51 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:15:51 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:15:51 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:15:51 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:15:51 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:15:51 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:15:51 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:15:51 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:15:54 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:15:54 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:16:02 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:16:06 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:16:14 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:16:19 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:16:27 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:16:27 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-04 13:16:35 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-04 13:16:36 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-04 13:16:44 - sshInstance.py - [line:46] - root - INFO - lspci -vvs 00:4b:00.0 | grep LnkCap:
2022-03-04 13:16:44 - sshInstance.py - [line:50] - root - INFO - 		LnkCap:	Port #0, Speed 16GT/s, Width x16, ASPM not supported

2022-03-04 13:16:52 - sshInstance.py - [line:46] - root - INFO - lspci -vvs 00:4b:00.0 | grep LnkSta:
2022-03-04 13:16:52 - sshInstance.py - [line:50] - root - INFO - 		LnkSta:	Speed 16GT/s (ok), Width x16 (ok)

2022-03-04 13:16:57 - test_nics.py - [line:230] - root - INFO - speed and width value is current
.2022-03-04 13:17:00 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:17:00 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:17:08 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:17:08 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:17:16 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:17:16 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:17:21 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:17:22 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:17:22 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:17:22 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:17:25 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:17:25 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

2022-03-04 13:17:33 - sshInstance.py - [line:46] - root - INFO - ifconfig vnet1 0
2022-03-04 13:17:33 - sshInstance.py - [line:50] - root - INFO - SIOCSIFADDR: No such device
vnet1: ERROR while getting interface flags: No such device

2022-03-04 13:17:41 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-04 13:17:41 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:17:46 - test_nics.py - [line:68] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-04 13:17:46 - test_nics.py - [line:70] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-04/test_PI_Networking_Link_State_Check_CVL_13_15_51
2022-03-04 13:17:49 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-04 13:17:49 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:17:54 - test_nics.py - [line:72] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-04 13:17:54 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-04 13:17:54 - test_nics.py - [line:74] - root - INFO - this is Test_Nics teardown
2022-03-04 13:17:54 - NicTestFixture.py - [line:32] - root - INFO - ============================ end of run test_PI_Networking_Link_State_Check_CVL case ============================
                              [100%]

=================================== FAILURES ===================================
__________ Test_Nics.test_silver_Networking_ConnectivityEnableDisable __________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7feec82ab240>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicSimple
    def test_silver_Networking_ConnectivityEnableDisable(self):
        cmd_list = [
            "ping -c 5 {}\n".format(self.dhcp["ipv4"]),
            "ifconfig {} down\n".format(self.sut_conf["connect_switch_sut_pf"]),
            "ifconfig {} up\n".format(self.sut_conf["connect_switch_sut_pf"]),
        ]
    
        pf_ip = "192.168.{}.{}".format(self.dhcp["ipv4"].split(".")[2],
                                               str(int(self.dhcp["ipv4"].split(".")[3]) + 1))
        cmd = "ifconfig {} {}\n".format(self.sut_conf["pf1"], pf_ip)
        self.cn_test_sut.run_ssh_cmd(self.session, cmd)
        output, stderr = self.cn_test_sut.run_ssh_cmd(self.session, cmd_list[0], self.check_str)
        assert 200 == self.cn_test_sut.commond_rs_check(output, "received, 0% packet loss", True)
        for i in range(5):
            output, stderr = self.cn_test_sut.run_ssh_cmd(self.session, cmd_list[1])
>           assert 200 == self.cn_test_sut.commond_rs_check(output, "No such device", False)
E           AssertionError: assert 200 == 400
E            +  where 400 = <bound method sshInstance.commond_rs_check of <libs.commons.sshInstance.sshInstance object at 0x7feec8376c88>>('ifconfig vnet1 down\r\nvnet1: ERROR while getting interface flags: No such device\r\n[root@WW25ICX2 ~]# ', 'No such device', False)
E            +    where <bound method sshInstance.commond_rs_check of <libs.commons.sshInstance.sshInstance object at 0x7feec8376c88>> = <libs.commons.sshInstance.sshInstance object at 0x7feec8376c88>.commond_rs_check
E            +      where <libs.commons.sshInstance.sshInstance object at 0x7feec8376c88> = <Tests.testNics.test_nics.Test_Nics object at 0x7feec82ab240>.cn_test_sut

npxtester/Tests/testNics/test_nics.py:94: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-04 13:07:29 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_Networking_ConnectivityEnableDisable case ============================
2022-03-04 13:07:29 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:07:29 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:07:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:07:30 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:07:30 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:07:33 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:07:33 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:07:41 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:07:45 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:07:53 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:07:58 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:08:06 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:08:06 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

----------------------------- Captured stdout call -----------------------------
2022-03-04 13:08:17 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Mar  4 13:15:25 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.122.2
[root@WW25ICX2 ~]# 
2022-03-04 13:08:24 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.
64 bytes from 192.168.122.1: icmp_seq=1 ttl=64 time=0.030 ms
2022-03-04 13:08:25 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=2 ttl=64 time=0.049 ms
2022-03-04 13:08:26 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=3 ttl=64 time=0.049 ms
2022-03-04 13:08:27 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=4 ttl=64 time=0.049 ms
2022-03-04 13:08:28 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=5 ttl=64 time=0.050 ms

--- 192.168.122.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.030/0.045/0.050/0.009 ms
[root@WW25ICX2 ~]# 
2022-03-04 13:08:37 - sshInstance.py - [line:94] - root - INFO - ifconfig vnet1 down
vnet1: ERROR while getting interface flags: No such device
[root@WW25ICX2 ~]# 
------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Mar  4 13:15:25 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.122.2
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.
64 bytes from 192.168.122.1: icmp_seq=1 ttl=64 time=0.030 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=2 ttl=64 time=0.049 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=3 ttl=64 time=0.049 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=4 ttl=64 time=0.049 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=5 ttl=64 time=0.050 ms

--- 192.168.122.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4096ms
rtt min/avg/max/mdev = 0.030/0.045/0.050/0.009 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ifconfig vnet1 down
vnet1: ERROR while getting interface flags: No such device
[root@WW25ICX2 ~]#
___________________ Test_Nics.test_silver_ConnectivityReboot ___________________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7feec83446d8>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicSimple
    def test_silver_ConnectivityReboot(self):
        logs = Logger()
        rs = 0
        cmdip = "ping -c 5 {}\n".format(self.dhcp["ipv4"])
        cmdipv6 = "ping6 -c 5 -I {} {}\n".format(self.sut_conf["connect_switch_sut_pf"],self.dhcp["ipv6"])
        for num in range(5):
            cn_test_sut = sshInstance()
            client, session = cn_test_sut.get_ssh_instance(self.sut_conf["host"], self.sut_conf["user"],
                                                           self.sut_conf["password"], self.sut_conf["port"])
            pf_ip = "192.168.{}.{}".format(self.dhcp["ipv4"].split(".")[2],
                                               str(int(self.dhcp["ipv4"].split(".")[3]) + 1))
            cmd = "ifconfig {} {}\n".format(self.sut_conf["pf1"], pf_ip)
            self.cn_test_sut.run_ssh_cmd(session, cmd)
            output, stderr = cn_test_sut.run_ssh_cmd(session, cmdip, self.check_str)
            assert 200 == cn_test_sut.commond_rs_check(output, "received, 0% packet loss", True)
            output, stderr = cn_test_sut.run_ssh_cmd(session, cmdipv6, self.check_str)
>           assert 200 == cn_test_sut.commond_rs_check(output, "received, 0% packet loss", True)
E           AssertionError: assert 200 == 400
E            +  where 400 = <bound method sshInstance.commond_rs_check of <libs.commons.sshInstance.sshInstance object at 0x7feec838f748>>('ping6 -c 5 -I vnet1 fe80::fc10:23ff:fe91:1512\r\nping: unknown iface vnet1\r\n[root@WW25ICX2 ~]# ', 'received, 0% packet loss', True)
E            +    where <bound method sshInstance.commond_rs_check of <libs.commons.sshInstance.sshInstance object at 0x7feec838f748>> = <libs.commons.sshInstance.sshInstance object at 0x7feec838f748>.commond_rs_check

npxtester/Tests/testNics/test_nics.py:119: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-04 13:09:37 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_silver_ConnectivityReboot case ============================
2022-03-04 13:09:37 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:09:37 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:09:37 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:09:37 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:09:37 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:09:40 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:09:40 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:09:48 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:09:52 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:10:00 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:10:05 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:10:13 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:10:14 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

----------------------------- Captured stdout call -----------------------------
2022-03-04 13:10:19 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:10:19 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:10:19 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:10:25 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Mar  4 13:18:14 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.122.2
[root@WW25ICX2 ~]# 
2022-03-04 13:10:32 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.
64 bytes from 192.168.122.1: icmp_seq=1 ttl=64 time=0.040 ms
2022-03-04 13:10:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=2 ttl=64 time=0.034 ms
2022-03-04 13:10:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=3 ttl=64 time=0.050 ms
2022-03-04 13:10:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=4 ttl=64 time=0.051 ms
2022-03-04 13:10:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.1: icmp_seq=5 ttl=64 time=0.027 ms

--- 192.168.122.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4106ms
rtt min/avg/max/mdev = 0.027/0.040/0.051/0.010 ms
[root@WW25ICX2 ~]# 
2022-03-04 13:10:43 - sshInstance.py - [line:71] - root - INFO - ping6 -c 5 -I vnet1 fe80::fc10:23ff:fe91:1512
ping: unknown iface vnet1
[root@WW25ICX2 ~]# 
------------------------------ Captured log call -------------------------------
INFO     paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_8.0)
INFO     paramiko.transport:transport.py:1819 Authentication (password) successful!
INFO     root:sshInstance.py:28 SSH on SUT: 10.112.97.62
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Fri Mar  4 13:18:14 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.122.2
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.1
PING 192.168.122.1 (192.168.122.1) 56(84) bytes of data.
64 bytes from 192.168.122.1: icmp_seq=1 ttl=64 time=0.040 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=2 ttl=64 time=0.034 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=3 ttl=64 time=0.050 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=4 ttl=64 time=0.051 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.1: icmp_seq=5 ttl=64 time=0.027 ms

--- 192.168.122.1 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4106ms
rtt min/avg/max/mdev = 0.027/0.040/0.051/0.010 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping6 -c 5 -I vnet1 fe80::fc10:23ff:fe91:1512
ping: unknown iface vnet1
[root@WW25ICX2 ~]#
_____________ Test_Nics.test_gold_PI_Networking_SRIOV_CheckDevice ______________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7feec8510128>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicSimple
    def test_gold_PI_Networking_SRIOV_CheckDevice(self):
        cmd = "echo 4 > /sys/class/net/{}/device/sriov_numvfs".format(self.sut_conf["connect_switch_sut_pf"])
        stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, cmd)
        if stdout or stderr:
>           assert 200 == 400
E           assert 200 == 400

npxtester/Tests/testNics/test_nics.py:129: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-04 13:11:42 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_gold_PI_Networking_SRIOV_CheckDevice case ============================
2022-03-04 13:11:42 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:11:42 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:11:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:11:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:11:43 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:11:43 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:11:43 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:11:43 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:11:46 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:11:46 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:11:54 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:11:58 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:12:06 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:12:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:12:19 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:12:19 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

----------------------------- Captured stdout call -----------------------------
2022-03-04 13:12:27 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/vnet1/device/sriov_numvfs
2022-03-04 13:12:27 - sshInstance.py - [line:50] - root - INFO - bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory

------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/vnet1/device/sriov_numvfs
INFO     root:sshInstance.py:50 bash: /sys/class/net/vnet1/device/sriov_numvfs: No such file or directory
____________ Test_Nics.test_PI_Networking_InternetProtocolv4v6_CVL _____________

self = <Tests.testNics.test_nics.Test_Nics object at 0x7feec8512198>

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicSimple
    def test_PI_Networking_InternetProtocolv4v6_CVL(self):
        sut1_ip = "192.168.10.10"
        sut2_ip = "192.168.10.11"
        cmd1 = "ifconfig {} {}".format(self.sut_conf["pf1"], sut1_ip)
        cmd2 = "ifconfig {} {}".format(self.sut2_conf["pf1"], sut2_ip)
    
        stdout1, stderr1 = self.cn_test_sut.ssh_exec_cmd(self.client, cmd1)
        stdout2, stderr2 = self.cn_test_sut.ssh_exec_cmd(self.client2, cmd2)
        if stdout1 or stderr1:
            assert 200==400,"assegin sut1 ip error"
        if stdout2 or stderr2:
            assert  200==400, "assegin sut2 ip error"
        ping_cmd = "ping -w 5 {}".format(sut2_ip)
        stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, ping_cmd)
        if stdout.find("100% packet loss") > -1:
            assert 200==400, "ping ipv4 sut2 from sut has error"
    
        ping6_cmd = "ping6 -c 5 -I {} {}".format(self.sut_conf["pf1"], self.dhcp["ipv6"])
        stdout, stderr = self.cn_test_sut.ssh_exec_cmd(self.client, ping6_cmd)
        if stdout.find("100% packet loss") > -1:
>           assert 200 == 400, "ping ipv6 sut2 from sut has error"
E           AssertionError: ping ipv6 sut2 from sut has error
E           assert 200 == 400

npxtester/Tests/testNics/test_nics.py:209: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-04 13:13:29 - NicTestFixture.py - [line:28] - root - INFO - ============================ Starting to run test_PI_Networking_InternetProtocolv4v6_CVL case ============================
2022-03-04 13:13:29 - test_nics.py - [line:18] - root - INFO - this is Test_Nics setup.
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:13:29 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-04 13:13:29 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-04 13:13:29 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-04 13:13:29 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-04 13:13:32 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-04 13:13:32 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-04 13:13:40 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-04 13:13:44 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:13:52 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-04 13:13:57 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:14:05 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-04 13:14:06 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

----------------------------- Captured stdout call -----------------------------
2022-03-04 13:14:14 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 192.168.10.10
2022-03-04 13:14:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:14:22 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 192.168.10.11
2022-03-04 13:14:22 - sshInstance.py - [line:50] - root - INFO - 
2022-03-04 13:14:30 - sshInstance.py - [line:46] - root - INFO - ping -w 5 192.168.10.11
2022-03-04 13:14:35 - sshInstance.py - [line:50] - root - INFO - PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.322 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.300 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.294 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.263 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.243 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.243/0.284/0.322/0.031 ms

2022-03-04 13:14:43 - sshInstance.py - [line:46] - root - INFO - ping6 -c 5 -I ens2f0 fe80::fc10:23ff:fe91:1512
2022-03-04 13:14:49 - sshInstance.py - [line:50] - root - INFO - ping6: Warning: source address might be selected on device other than ens2f0.
PING fe80::fc10:23ff:fe91:1512(fe80::fc10:23ff:fe91:1512) from :: ens2f0: 56 data bytes
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=1 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=2 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=3 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=4 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=5 Destination unreachable: Address unreachable

--- fe80::fc10:23ff:fe91:1512 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4121ms
pipe 3

------------------------------ Captured log call -------------------------------
INFO     root:sshInstance.py:46 ifconfig ens2f0 192.168.10.10
INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 ifconfig ens2f1 192.168.10.11
INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 ping -w 5 192.168.10.11
INFO     root:sshInstance.py:50 PING 192.168.10.11 (192.168.10.11) 56(84) bytes of data.
64 bytes from 192.168.10.11: icmp_seq=1 ttl=64 time=0.322 ms
64 bytes from 192.168.10.11: icmp_seq=2 ttl=64 time=0.300 ms
64 bytes from 192.168.10.11: icmp_seq=3 ttl=64 time=0.294 ms
64 bytes from 192.168.10.11: icmp_seq=4 ttl=64 time=0.263 ms
64 bytes from 192.168.10.11: icmp_seq=5 ttl=64 time=0.243 ms

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4133ms
rtt min/avg/max/mdev = 0.243/0.284/0.322/0.031 ms

INFO     root:sshInstance.py:46 ping6 -c 5 -I ens2f0 fe80::fc10:23ff:fe91:1512
INFO     root:sshInstance.py:50 ping6: Warning: source address might be selected on device other than ens2f0.
PING fe80::fc10:23ff:fe91:1512(fe80::fc10:23ff:fe91:1512) from :: ens2f0: 56 data bytes
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=1 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=2 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=3 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=4 Destination unreachable: Address unreachable
From fe80::b696:91ff:fe9c:f7a4%ens2f0: icmp_seq=5 Destination unreachable: Address unreachable

--- fe80::fc10:23ff:fe91:1512 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4121ms
pipe 3
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:62
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:62: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:101
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_iperf_client_4hour.py:101: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:71
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:71: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:381
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:381: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:498
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:498: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:797
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_network_sriov_stress.py:797: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:78
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:78: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:102
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:102: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:124
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:124: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:188
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:188: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:212
  /root/.jenkins/workspace/test-test-nic-simple/npxtester/Tests/testNics/test_nics.py:212: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_simple_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_silver_Networking_ConnectivityEnableDisable
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_silver_ConnectivityReboot
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_gold_PI_Networking_SRIOV_CheckDevice
FAILED npxtester/Tests/testNics/test_nics.py::Test_Nics::test_PI_Networking_InternetProtocolv4v6_CVL
====== 4 failed, 3 passed, 9 deselected, 12 warnings in 880.07s (0:14:40) ======
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4AfI3SthhIf/wHKBxkZZVuznCBOLGICd+mTaK5J1XhvpAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMHmfoKzrT+3fkMfZ274AAAA=[0m[Pipeline] }
[8mha:////4O1G14z5oV6C9jl1Q5yIn+pZFQRmsElhyj6JiXyHA8ixAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiBB2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7BpKm1V++AAAA[0m[Pipeline] // stage
[8mha:////4KtBCOpIKS64HlRGbxVDHBnhT4546C6ceKSEgLxKWO63AAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUauVY2WZoPEGEGAOZXUwWofJEXs07yMiMlb/67zXv9cYyRRw5OtVYaj2lyqsu9G56auDYXgMPquGLqpgSB6tKO5Rc29OMJYvFvCzHQmNlqQqcPDnBWjfmYYpgyBVniZM7aOS+vuOJTE9lMVG+MEZsbn2dmH6dvwGMXSfIt3tBtvsA/gVtV70AAAA=[0m[Pipeline] }
[8mha:////4PVa+eOfGCB5ryE2GyokIfyPZOVvh3emQVgJTOuHuCGAAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IMJC7GybVh8Qsq1Fpo3sP2IUx+kb/mP0gkcfJO95zlvN5Yp4gjR6daS52nVHvVh8HNT40cu2vgUbV8UTVT4mBVZceKG3tasGKxWJblWGlsLNWBkycn2OrWPEwRDLniLHF2B43cN3c8kem5LCbKF6aI3W1oEtOv8zeAqe8FebkXZOUHjeqpjr0AAAA=[0m[Pipeline] // node
[8mha:////4OyM7hMK6utvbTfbnNkjhtaoCHWCq3+ZbQ+BNe9AvJHZAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRoKBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Lu9INt+AKvzzsS9AAAA[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
