Started by user [8mha:////4C8zTO/v0UlG+vQ5Fjm5jTf9kR93yL5yxTMP2X04T9v8AAAAlh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgYu/dLi1CL9ovz8EgDKVWzSvwAAAA==[0mroot
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4DOlrZhma2TKYqx8mtRBwGXVE8Xt4z3OJyo/zi+ICDdzAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4B4K7nOhvaaLmbeE3w0NEhE1GAALwLDjakw9plXgkY6XAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Running on [8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-j in /root/.jenkins/workspace/test-test-nic-sriov-5times
[8mha:////4NUxBMzN6CtFAbQ4pdo7pH8ZuwVHigLf0SdP3FcjQTwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4OCB1+Up79PmV3LnMeomKr9r+JFCKkFjAfTpr2UorbLOAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4N6KQN35K8CT/Pcr9a+R4oOEu4uEh3phvpB1t67zd2hmAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (rm project dir)
[8mha:////4EWjgIQS1R18e39T6LdOu3ZpSMSXMburmKwxJHd8e163AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gwExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jcChmMxwAAAAA==[0m[Pipeline] script
[8mha:////4NOJ/YVWDlnnBpjDdLKlLZkF5LrR387vblsx7fWhZkPlAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0BAkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfpX/cvwAAAAA==[0m[Pipeline] {
[8mha:////4MAm0moKTc8Eo2PcB0LgkHNHI7Xtf5Poej2Mf/l8xh/lAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaoyVLaHxBMgiwpL/WWDdrTyRV/MOEjexcpJJ5k3zXm9Y5wQnSpZ7g73DrB2PYbR18YlSfws0cU9XrgkzBcOlmSR15rygpGJgCWtgJWBjUAfKDm2BrfDqodqg0LaXkup3FNC4boAnMFHNRaXyhTnB7j52mfDn+SuAORZg+9pD/AAeoCAqvAAAAA==[0m[Pipeline] sh
+ ls /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
1.0.0.0001.version
conf
installation
libs
log_analyzer
README.md
testconf
testLibs
Tests
[8mha:////4F3BY6hez6Yn9lSF4dYULOlz4RwK0Fdsp1OYWtj0vxDtAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKBDglR0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYO0G2F+S7bfcBITL9lL0AAAA=[0m[Pipeline] echo
dir is exists and rm dir
[8mha:////4KL1cTFlC/t8/0LRf71hJwxXIUFLIMviWtcIHXR2W8epAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6KEzcQ4uTYsfkGFWgvNe9g+hMkv8tf8B4kkTt7pnrOc1xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9YJsL8jLsv8AYAPmjb0AAAA=[0m[Pipeline] sh
+ rm -rf /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester
[8mha:////4GzJynz9IX3CLl34e/1JpYOeLz7FDsqMtIihCtFGqNpZAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRVEiIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsTZPsPzjQzob0AAAA=[0m[Pipeline] }
[8mha:////4MvApYhNLg1xEFG2iXyHCog7Z9h4MbdAsNSDoK4wJnDgAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRoqBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AO8A7Ay9AAAA[0m[Pipeline] // script
[8mha:////4P1g47DHQeYIMdAQPrqVFJW5XTEYSJkMqP0k+p1upCWxAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIREqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5NudINt/AGnsy8m9AAAA[0m[Pipeline] }
[8mha:////4Lc6WrLYEiiAC7rTWY8q4RQPGu1FD+hrgClvEqpzcg2sAAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiKMBZVjZZuh8QQRYgxkdjFZhMoTeTXvICMzVv7qv9e81xvrFHHk6FRrqfOUaq/6MLj5qZFjdw08qpYvqmZKHKyq7FhxY08LViwWy7IcK42NpTpw8uQEW92ahymCIVecJc7uoJH75o4nMj2XxUT5whSxuw1NYvp1/gYw9b0g35eCrPwAY5Sibb0AAAA=[0m[Pipeline] // stage
[8mha:////4LPzYIRsJlP9vBl87WR2FbvV5590n9jZkqHCRBijPEs5AAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJESDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8A6sHc4fBAAAA[0m[Pipeline] stage
[8mha:////4P0yjWfQiEwQxZO7i9obwDXrYwQclNR3i//1CTGbFwBFAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohULDAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD1+IXOLCAAAA[0m[Pipeline] { (git clone)
[8mha:////4I3tKNYAz7At397ZkNOs6SFwEn2bzn3ZBhsoegW1dhRwAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKpAQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHNxXfVKy+AAAA[0m[Pipeline] sh
+ git clone -b develop https://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@github.com/Jiz1028/applications.validation.network-platform.npxtester.git npxtester
Cloning into 'npxtester'...
[8mha:////4CRWXV91kUhqh2bTVXI+2n5U32cQ89nJ7yub5blKQ29bAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiKoQQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrt/lO7N9Jjga++AAAA[0m[Pipeline] }
[8mha:////4I4ZVrOFMvh2sVfxnfT9s6+paGHoH9OzkxEwdR4h+nRDAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICFDQoFa3lhheYxBgn1l2wHZyKF/E1/oBFJCq2WO1sM683LIOHmr3BTlNvKTQWBzeavDCx76+OE3Z8wYYpsNModZLc6tOMkqOGOUUJCwErTY3jYMlEWItOPVTlFJnqHH3+jgJK297hCYXI5qh8/MLkYXMb28D08/wVwDQMEcr9Ntfu8AERGGHOvgAAAA==[0m[Pipeline] // stage
[8mha:////4J4BpfnRrLE6odVrNZGgZ11wIRy0HYHBalvcHAcD12j/AAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjEB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INji2eq8EAAAA=[0m[Pipeline] stage
[8mha:////4AgPhGmio4pMNzq5gItmuDxswb3P5dwyIofUIBdMXBTmAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycohUdEVMrFEXThCaEJJG/7dJSjpxIq7GHWipxIQHy7ZkvdcbyhjgRMFwp7GzGFvLez+aOfFMobt5ytzRlbeEkbzmjc4NKX1ea0NJw6qCwUbAVmPrKVo0CXbCyYesvERTXVKYt6MAZtUATyjETE4ypG+ZAuzvo4qEP85fAEx9AlYfFquXZ/kBAsTc3cIAAAA=[0m[Pipeline] { (pre-exec-set-args)
[8mha:////4G9dxluK5ut2lxdfo2JVi6OIov1ZH/881VUFzuPzanonAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyE0vHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzD5B3baf2vs3w5BRkb4AAAA=[0m[Pipeline] sh
+ python /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/conf/change_args.py '{"drive_info":{"drive_version":"1.6.4"},"dpdk_dir":"/opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/","vm_image_conf":{"image1":"uvm1.img","image2":"uvm2.img","image3":"rhel84rt.img","image4":"rhel84rt2.img","image_dir":"/home/image"},"sut_conf":{"host":"10.112.97.62","pf1":"ens2f0","os":"RHEL"},"pkg_generator":{"host":"10.112.97.60","pf1":"ens2f1"}}'
[8mha:////4FhUQONKPXFSeOjFO92QKbtxv93cUzSuhB7hx3xoWX6KAAAApB+LCAAAAAAAAP9tjbEOwiAURV9rHFwd/QiaNG7GyZWw+AXYIkLJexSodPKL/DX/QbSJk3e4uecu5/mCdQxwpKCZVTgYjJ1h3k26LJYpDFdHmVm6sI4wklNMqCyoV6cFBSUFS6oaVhw2CjtH0aBOsOVW3mXjJOrmnEL5Dhxq04/wgIoXc5IhfWEOsLtNfST8ef4KYPY+Qd3uP9W+Ad3NsHm+AAAA[0m[Pipeline] }
[8mha:////4EpM1Tihe33kOTBucrClpdwMCq1FF6wGwTU/AEOZmYaNAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikKgQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGMIGcrd/lPbN8JP5Su+AAAA[0m[Pipeline] // stage
[8mha:////4JJk4NQMkVX21N+ktknOqKLQw+FD2VU/fvD8dhBPuambAAAApx+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjIUSDqGgtN7zAxMY4se6CfSGpeBFf4w8EIlGx1c5Kq3m+oMwJDpS8bBy2AXMdZBd7PzU5UGovkQbZ0FnWhJmik9oNmqw7zqiJHcwRBSwULB3WkXJAz7BSjbmbKhr01YnTtO0VFMHe4AFCTWY2ib8wJlhfe5sJf56/Ahg7BrFlKDa7z7F8AzYdm7bBAAAA[0m[Pipeline] stage
[8mha:////4GToWcz1lEtttcc1F67+obVKf97ChyGWoNBgdNb8ln6iAAAAqB+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUYoABMXWNsnCC0ISQNvq//KS0EyfiatyBlkpMeLBsS9Z7vaGIDCdiJxqLrcdYe9GF3k1JDMTtNdAgGrqImjBSsELZQZGx1VIVJQuLshxWEtYW60DRo0uwkY1+6DJodOU58bQdJeTe3OEJmZzISXP6lpFhe+tNJPxx/gJg7BLku/1sh/lZfAAyQCqkwgAAAA==[0m[Pipeline] { (run nic case)
[8mha:////4M/BBJOrvLliK1a64sS7A0hf4H4seiclg8D1IX9OqKAVAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0YCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDhnK7+9Q+vAGvZp0gvgAAAA==[0m[Pipeline] sh
+ pytest /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics -s -m nicSriov5times --capture=tee-sys --html=/root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html --self-contained-html
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics, configfile: pytest.ini
plugins: metadata-1.11.0, html-3.1.1
collected 17 items / 16 deselected / 1 selected

npxtester/Tests/testNics/test_network_sriov_stress.py 2022-03-14 15:24:13 - NicTestFixture.py - [line:37] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-03-14 15:24:13 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 15:24:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-14 15:24:13 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 15:24:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-14 15:24:16 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-14 15:24:16 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-14 15:24:25 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-14 15:24:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:24:37 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-14 15:24:42 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:24:50 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-14 15:24:50 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:24:58 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-14 15:24:58 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-14 15:25:06 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-14 15:25:06 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 342 (342.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 19  bytes 3138 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 15:25:14 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-14 15:25:14 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 6097575899  bytes 9229273135753 (8.3 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 211278822  bytes 16112300351 (15.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 15:25:19 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-14 15:25:22 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 15:25:23 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 15:25:28 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 15:25:28 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 15:25:28 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 15:25:34 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 14 15:31:58 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 15:25:37 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 15:25:40 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:25:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:25:45 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 15:25:48 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 15:25:48 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 15:25:53 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 15:25:56 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 15:25:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:26:04 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 15:26:05 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:26:10 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:26:13 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 15:26:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:26:19 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:26:19 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:26:22 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:26:22 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 15:26:27 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 15:26:30 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 15:26:30 - sshInstance.py - [line:50] - root - INFO - no

2022-03-14 15:26:35 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? no

2022-03-14 15:26:35 - test_network_sriov_stress.py - [line:207] - root - INFO - virsh net-start default
2022-03-14 15:26:38 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-14 15:26:38 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-14 15:26:43 - test_network_sriov_stress.py - [line:211] - root - INFO - Successfully started network default.
2022-03-14 15:26:47 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 15:26:48 - sshInstance.py - [line:71] - root - INFO - 
** (process:12973): [1;33mWARNING[0m **: [34m15:35:12.796[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:26:50 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:26:53 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 15:26:57 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13022): [1;33mWARNING[0m **: [34m15:35:22.531[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-14 15:26:58 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:27:00 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:27:03 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 15:27:06 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:27:06 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:27:11 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 15:28:14 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:28:14 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 15:28:19 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 15:28:22 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:28:23 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 15:28:28 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 15:28:28 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 15:28:28 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 15:28:32 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.335 ms
2022-03-14 15:28:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.466 ms
2022-03-14 15:28:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.280 ms
2022-03-14 15:28:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.470 ms
2022-03-14 15:28:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4116ms
rtt min/avg/max/mdev = 0.280/0.403/0.470/0.082 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:28:45 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
The authenticity of host '192.168.122.72 (192.168.122.72)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-14 15:28:54 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.72' (ECDSA) to the list of known hosts.
root@192.168.122.72's password: 
2022-03-14 15:29:04 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:37:25 AM EDT
  System load:  0.04               Processes:             141
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Sun Mar 13 22:44:25 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:29:13 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:29:19 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:29:25 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:29:30 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:29:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 15:29:39 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:29:45 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:29:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 15:30:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:30:13 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:30:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:30:31 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:30:38 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.284 ms
2022-03-14 15:30:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.471 ms
2022-03-14 15:30:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.326 ms
2022-03-14 15:30:41 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.276 ms
2022-03-14 15:30:42 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.273 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.273/0.326/0.471/0.074 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:30:51 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
The authenticity of host '192.168.122.208 (192.168.122.208)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-14 15:31:00 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.208' (ECDSA) to the list of known hosts.
root@192.168.122.208's password: 
2022-03-14 15:31:09 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:39:30 AM EDT
  System load:  0.0                Processes:             137
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Sun Mar 13 22:46:21 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:31:18 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:31:24 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:31:30 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:31:35 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:31:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 15:31:44 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:31:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:32:00 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 15:32:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:32:18 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:32:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:32:36 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:32:39 - test_network_sriov_stress.py - [line:468] - root - INFO - Ping two vms IP from SUT:
2022-03-14 15:32:43 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.769 ms
2022-03-14 15:32:44 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.253 ms
2022-03-14 15:32:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.189 ms
2022-03-14 15:32:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.179 ms
2022-03-14 15:32:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.111 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.111/0.300/0.769/0.238 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:32:54 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.411 ms
2022-03-14 15:32:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.208 ms
2022-03-14 15:32:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.204 ms
2022-03-14 15:32:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.174 ms
2022-03-14 15:32:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.201 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4090ms
rtt min/avg/max/mdev = 0.174/0.239/0.411/0.088 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:33:01 - test_network_sriov_stress.py - [line:476] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 15:33:05 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.274 ms
2022-03-14 15:33:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.463 ms
2022-03-14 15:33:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.471 ms
2022-03-14 15:33:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.461 ms
2022-03-14 15:33:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.177 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.177/0.369/0.471/0.121 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:33:18 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 15:33:27 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:41:49 AM EDT
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:37:25 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:33:34 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.279 ms
2022-03-14 15:33:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.331 ms
2022-03-14 15:33:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.208 ms
2022-03-14 15:33:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.241 ms
2022-03-14 15:33:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.276 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.208/0.267/0.331/0.041 ms
root@localhost:~# 
2022-03-14 15:34:18 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:34:21 - test_network_sriov_stress.py - [line:484] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 15:34:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 15:34:28 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 15:34:31 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4123ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 15:34:37 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:34:39 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:34:44 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 15:34:47 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 15:34:47 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 15:34:52 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 15:34:55 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 15:34:55 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 15:35:00 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 15:35:03 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 15:35:04 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 15:35:09 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 15:35:12 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 15:35:12 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 15:35:17 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 15:35:17 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-03-14 15:35:20 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 15:35:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 15:35:25 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 15:35:25 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 15:35:25 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 15:35:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 15:35:34 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 15:35:37 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:35:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:35:43 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 15:35:46 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 15:35:46 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 15:35:51 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 15:35:54 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 15:35:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:36:02 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 15:36:03 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:36:08 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:36:11 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 15:36:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:36:17 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:36:17 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:36:20 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:36:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 15:36:25 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 15:36:28 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 15:36:28 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 15:36:33 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 15:36:37 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14132): [1;33mWARNING[0m **: [34m15:45:01.942[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
2022-03-14 15:36:38 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 15:36:41 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14132): [1;33mWARNING[0m **: [34m15:45:01.942[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 15:36:41 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 15:36:45 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14138): [1;33mWARNING[0m **: [34m15:45:09.952[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:36:48 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:36:51 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 15:36:55 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14182): [1;33mWARNING[0m **: [34m15:45:19.943[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
2022-03-14 15:36:56 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 15:36:59 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14182): [1;33mWARNING[0m **: [34m15:45:19.943[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 15:36:59 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 15:37:03 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14189): [1;33mWARNING[0m **: [34m15:45:27.876[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:37:05 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:37:08 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 15:37:11 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:37:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:37:16 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 15:38:19 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:38:19 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 15:38:24 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 15:38:27 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:38:27 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 15:38:32 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 15:38:32 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 15:38:32 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 15:38:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.339 ms
2022-03-14 15:38:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.465 ms
2022-03-14 15:38:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.316 ms
2022-03-14 15:38:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.469 ms
2022-03-14 15:38:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.473 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4082ms
rtt min/avg/max/mdev = 0.316/0.412/0.473/0.072 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:38:49 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 15:38:58 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:47:20 AM EDT
  System load:  0.0                Processes:             135
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:41:49 2022 from 192.168.122.1
root@localhost:~# Resuming build at Mon Mar 14 07:34:24 GMT 2022 after Jenkins restart
Waiting to resume part of test-test-nic-sriov-5times #56: Finished waiting
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Waiting to resume part of test-test-nic-sriov-5times #56: Waiting for next available executor on â€˜[8mha:////4EheNQ7D4c27QswDGPiDpGtf9rfQF1HauEmyd+/REsZ/AAAAoh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyeEgZx/eT83ILSktQiICOvpCg/Jye1SDdLHwCRPP8lzAAAAA==[0mcontroller-jâ€™
Ready to run at Mon Mar 14 07:38:38 GMT 2022

2022-03-14 15:39:07 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:39:13 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:39:19 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:39:24 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:39:30 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 15:39:33 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:39:39 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:39:49 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 15:39:58 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:40:07 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:40:16 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:40:25 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:40:32 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.331 ms
2022-03-14 15:40:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.461 ms
2022-03-14 15:40:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.468 ms
2022-03-14 15:40:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.394 ms
2022-03-14 15:40:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.197 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4110ms
rtt min/avg/max/mdev = 0.197/0.370/0.468/0.100 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:40:45 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 15:40:54 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:49:16 AM EDT
  System load:  0.0                Processes:             139
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:39:30 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:41:03 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
root@localhost:~# 
2022-03-14 15:41:09 - test_network_sriov_stress.py - [line:357] - root - INFO - Faile to get vf pci id of vm1.
2022-03-14 15:41:15 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
F2022-03-14 15:41:21 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 15:41:22 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 15:41:27 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 15:41:30 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 15:41:30 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 15:41:35 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 15:41:38 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 15:41:38 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 15:41:43 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 15:41:46 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 15:41:46 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 15:41:51 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 15:41:54 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:41:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:42:04 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 0
2022-03-14 15:42:04 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:42:12 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1 0
2022-03-14 15:42:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:42:20 - sshInstance.py - [line:46] - root - INFO - dmesg > /tmp/dmesg.log
2022-03-14 15:42:20 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:42:25 - test_network_sriov_stress.py - [line:82] - root - INFO - generate dmesg.log file on sut /tmp/dmesg.log
2022-03-14 15:42:25 - test_network_sriov_stress.py - [line:84] - root - INFO - copy dmesg.log from sut1 /tmp dir to controller dir /root/testconfig/testlogs/2022-03-14/test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]_15_24_13
2022-03-14 15:42:28 - sshInstance.py - [line:46] - root - INFO - rm -f /tmp/dmesg.log
2022-03-14 15:42:28 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:42:33 - test_network_sriov_stress.py - [line:86] - root - INFO - rm dmesg.log on sut1 /tmp dir
2022-03-14 15:42:33 - sshInstance.py - [line:39] - root - INFO - closing ssh client on SUT
2022-03-14 15:42:33 - NicTestFixture.py - [line:41] - root - INFO - ============================ end of run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
                  [100%]

=================================== FAILURES ===================================
_ Test_Network_SRIOV_Stress.test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] _

self = <Tests.testNics.test_network_sriov_stress.Test_Network_SRIOV_Stress object at 0x7f5cd8bc71d0>
vm1_image = 'uvm2.img', vm2_image = 'uvm1.img'

    @pytest.mark.usefixtures("fbefore")
    @pytest.mark.nicAll
    @pytest.mark.nicGold
    @pytest.mark.nicSriovStress
    @pytest.mark.nicSriov5times
    @pytest.mark.parametrize('vm1_image, vm2_image', vm_image)
    def test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest(self, vm1_image, vm2_image):
        for j in range(1, 6):
            logging.info(
                "\n\n********************************************************Stress Disable and Enable for {} time when VF is Assigned VM guest.*************************************************************\n\n".format(
                    j))
            # get pf id: 0000:xx:xx.x
            pf_id, status = self.get_pf_id(self.pf_name)
            # transfer pf_id to 0000\:00\:00.0 format
            if not pf_id:
                assert 200 == status
            else:
                pf_id_format = pf_id.replace(":", "\\:", 2)
                logging.info("format_pf_id is {}".format(pf_id_format))
                # get the number key of pf_id
                pf_id_key = pf_id.split(":")[1]
                logging.info("pf_id_key: {}".format(pf_id_key))
                # assign IP to PF in SUT and sut2
                pf_ip = "192.168.10.10"
                sut2_ip = "192.168.10.11"
                assert 200 == self.assign_ip_ehternet(self.session, pf_ip, self.pf_name)
                # virtulize the pf to vfs
                assert 200 == self.virtualize_pf_to_vfs(self.pf_name)
                # get vf ids
                vf_id_list, status = self.get_vf_ids(pf_id_key)
                vf_id_list = [i.strip() for i in vf_id_list]
                if status == 200:
                    # modprobe vfio-pci
                    assert 200 == self.modprobe("vfio-pci")
                    # bind vf with vfio-pci
                    host_dev_id_list, status = self.bind_vf_to_vfio_pci(vf_id_list)
                    assert 200 == status
                else:
                    assert 200 == status
                # get vF device ida
                # tmp code
                cmd = "lspci -Dnn | grep %s" % (vf_id_list[1])
                logging.info(cmd)
                vf_device_id = ""
                vf_device_id_rs, error = self.ssh_sut.ssh_exec_cmd(self.client, cmd)
                if vf_device_id_rs:
                    st = False
                    vf_device_id = None
                    for one in vf_device_id_rs.split(" "):
                        one = " " + one + " "
                        if one.find(" [") > -1 and one.find("] ") > -1 and one.find(":") > -1:
                            vf_device_id = one.replace("[", "").replace("]", "").strip()
                    if not vf_device_id: assert 200 == 400, "vf_device_id is not found"
                    logging.info("Successfully get vf device id: {}".format(vf_device_id))
                    assert 200 == 200
                else:
                    logging.error("Fail to get vf device id.")
                    assert 200 == 400
    
                # set network
                status = self.default_network_isActive(self.defult_network)
                if status == "no":
                    assert 200 == self.start_default_network(self.defult_network)
    
                # start VMs
                assert 200 == self.create_vm(vm1_image, host_dev_id_list[0], self.vm1_name, "5900")
                assert 200 == self.create_vm(vm2_image, host_dev_id_list[1], self.vm2_name, "5901")
                # get VM ssh IP
                vm1_ip, status1 = self.get_vm_ip(self.vm1_name)
                vm2_ip, status2 = self.get_vm_ip(self.vm2_name)
                logging.info("ip of VM1: {}".format(vm1_ip))
                logging.info("ip of VM1: {}".format(vm2_ip))
    
                # ssh VM1 to set VF
                vm1_vf_ip = "192.168.10.12"
                vm2_vf_ip = "192.168.10.13"
                assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                                  vm1_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
                vm1_vf_name, vm1_ipv6, status = self.ssh_vm_set_VF(vm1_ip, vf_device_id, vm1_vf_ip, "1234567890ac")
                self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
    
                assert 200 == status, "vm1 vf related settings failed"
                assert 200 == self.on_session_ssh(self.ssh_sut, self.session,
                                                  vm2_ip), "ssh vm failed,the reason may be is password is error,vm ip isimpassability"
                vm2_vf_name, vm2_ipv6, status = self.ssh_vm_set_VF(vm2_ip, vf_device_id, vm2_vf_ip, "1234567890ab")
                self.ssh_sut.run_ssh_cmd(self.session, "exit\n")
>               assert 200 == status, "vm2 vf related settings failed"
E               AssertionError: vm2 vf related settings failed
E               assert 200 == 400

npxtester/Tests/testNics/test_network_sriov_stress.py:465: AssertionError
---------------------------- Captured stdout setup -----------------------------
2022-03-14 15:24:13 - NicTestFixture.py - [line:37] - root - INFO - ============================ Starting to run test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img] case ============================
2022-03-14 15:24:13 - test_network_sriov_stress.py - [line:28] - root - INFO - SSH SUT and setup configurations in the setup function.
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 15:24:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.62
2022-03-14 15:24:13 - sftp.py - [line:158] - paramiko.transport.sftp - INFO - [chan 1] Opened sftp connection (server version 3)
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.0)
2022-03-14 15:24:13 - transport.py - [line:1819] - paramiko.transport - INFO - Authentication (password) successful!
2022-03-14 15:24:13 - sshInstance.py - [line:28] - root - INFO - SSH on SUT: 10.112.97.60
2022-03-14 15:24:16 - sshInstance.py - [line:46] - root - INFO - modinfo ice | grep ^version:
2022-03-14 15:24:16 - sshInstance.py - [line:50] - root - INFO - version:        1.6.4

2022-03-14 15:24:25 - sshInstance.py - [line:46] - root - INFO - rmmod ice
2022-03-14 15:24:29 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:24:37 - sshInstance.py - [line:46] - root - INFO - modprobe ice
2022-03-14 15:24:42 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:24:50 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0 up
2022-03-14 15:24:50 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:24:58 - sshInstance.py - [line:46] - root - INFO - modinfo ice
2022-03-14 15:24:58 - sshInstance.py - [line:50] - root - INFO - filename:       /lib/modules/4.18.0-305.el8.x86_64/updates/drivers/net/ethernet/intel/ice/ice.ko
firmware:       intel/ice/ddp/ice.pkg
version:        1.6.4
license:        GPL v2
description:    Intel(R) Ethernet Connection E800 Series Linux Driver
author:         Intel Corporation, <linux.nics@intel.com>
rhelversion:    8.4
srcversion:     C8EA21B2A34EA565E9AC844
alias:          pci:v00008086d0000151Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Fsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000124Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000189Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001899sv*sd*bc*sc*i*
alias:          pci:v00008086d00001898sv*sd*bc*sc*i*
alias:          pci:v00008086d00001897sv*sd*bc*sc*i*
alias:          pci:v00008086d00001894sv*sd*bc*sc*i*
alias:          pci:v00008086d00001893sv*sd*bc*sc*i*
alias:          pci:v00008086d00001892sv*sd*bc*sc*i*
alias:          pci:v00008086d00001891sv*sd*bc*sc*i*
alias:          pci:v00008086d00001890sv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Esv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Dsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Csv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000188Asv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000159Asv*sd*bc*sc*i*
alias:          pci:v00008086d00001599sv*sd*bc*sc*i*
alias:          pci:v00008086d00001593sv*sd*bc*sc*i*
alias:          pci:v00008086d00001592sv*sd*bc*sc*i*
alias:          pci:v00008086d00001591sv*sd*bc*sc*i*
depends:        
name:           ice
vermagic:       4.18.0-305.el8.x86_64 SMP mod_unload modversions 
parm:           debug:netif level (0=none,...,16=all) (int)
parm:           fwlog_level:FW event level to log. All levels <= to the specified value are enabled. Values: 0=none, 1=error, 2=warning, 3=normal, 4=verbose. Invalid values: >=5
 (ushort)
parm:           fwlog_events:FW events to log (32-bit mask)
 (ulong)

2022-03-14 15:25:06 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f0
2022-03-14 15:25:06 - sshInstance.py - [line:50] - root - INFO - ens2f0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fe9c:f7a4  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:9c:f7:a4  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 342 (342.0 B)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 19  bytes 3138 (3.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


2022-03-14 15:25:14 - sshInstance.py - [line:46] - root - INFO - ifconfig ens2f1
2022-03-14 15:25:14 - sshInstance.py - [line:50] - root - INFO - ens2f1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::b696:91ff:fea5:9b45  prefixlen 64  scopeid 0x20<link>
        ether b4:96:91:a5:9b:45  txqueuelen 1000  (Ethernet)
        RX packets 6097575899  bytes 9229273135753 (8.3 TiB)
        RX errors 0  dropped 85  overruns 0  frame 0
        TX packets 211278822  bytes 16112300351 (15.0 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


----------------------------- Captured stdout call -----------------------------
2022-03-14 15:25:19 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


2022-03-14 15:25:22 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 15:25:23 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 15:25:28 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 15:25:28 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 15:25:28 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 15:25:34 - sshInstance.py - [line:94] - root - INFO - Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 14 15:31:58 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 15:25:37 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 15:25:40 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:25:40 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:25:45 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 15:25:48 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 15:25:48 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 15:25:53 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 15:25:56 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 15:25:56 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:26:04 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 15:26:05 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:26:10 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:26:13 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 15:26:14 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:26:19 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:26:19 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:26:22 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:26:22 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 15:26:27 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 15:26:30 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 15:26:30 - sshInstance.py - [line:50] - root - INFO - no

2022-03-14 15:26:35 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? no

2022-03-14 15:26:35 - test_network_sriov_stress.py - [line:207] - root - INFO - virsh net-start default
2022-03-14 15:26:38 - sshInstance.py - [line:46] - root - INFO - virsh net-start default
2022-03-14 15:26:38 - sshInstance.py - [line:50] - root - INFO - Network default started


2022-03-14 15:26:43 - test_network_sriov_stress.py - [line:211] - root - INFO - Successfully started network default.
2022-03-14 15:26:47 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
2022-03-14 15:26:48 - sshInstance.py - [line:71] - root - INFO - 
** (process:12973): [1;33mWARNING[0m **: [34m15:35:12.796[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:26:50 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:26:53 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 15:26:57 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13022): [1;33mWARNING[0m **: [34m15:35:22.531[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
2022-03-14 15:26:58 - sshInstance.py - [line:71] - root - INFO - WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:27:00 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:27:03 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 15:27:06 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:27:06 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:27:11 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 15:28:14 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:28:14 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 15:28:19 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 15:28:22 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:28:23 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 15:28:28 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 15:28:28 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 15:28:28 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 15:28:32 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.335 ms
2022-03-14 15:28:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.466 ms
2022-03-14 15:28:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.280 ms
2022-03-14 15:28:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.470 ms
2022-03-14 15:28:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4116ms
rtt min/avg/max/mdev = 0.280/0.403/0.470/0.082 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:28:45 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
The authenticity of host '192.168.122.72 (192.168.122.72)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-14 15:28:54 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.72' (ECDSA) to the list of known hosts.
root@192.168.122.72's password: 
2022-03-14 15:29:04 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:37:25 AM EDT
  System load:  0.04               Processes:             141
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Sun Mar 13 22:44:25 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:29:13 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:29:19 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:29:25 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:29:30 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:29:36 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 15:29:39 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:29:45 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:29:55 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 15:30:04 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:30:13 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:30:22 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:30:31 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:30:38 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.284 ms
2022-03-14 15:30:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.471 ms
2022-03-14 15:30:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.326 ms
2022-03-14 15:30:41 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.276 ms
2022-03-14 15:30:42 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.273 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.273/0.326/0.471/0.074 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:30:51 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
The authenticity of host '192.168.122.208 (192.168.122.208)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
2022-03-14 15:31:00 - sshInstance.py - [line:94] - root - INFO - yes
Warning: Permanently added '192.168.122.208' (ECDSA) to the list of known hosts.
root@192.168.122.208's password: 
2022-03-14 15:31:09 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:39:30 AM EDT
  System load:  0.0                Processes:             137
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Sun Mar 13 22:46:21 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:31:18 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:31:24 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:31:30 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:31:35 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:31:41 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.13
root@localhost:~# 
2022-03-14 15:31:44 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:31:50 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:32:00 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
2022-03-14 15:32:09 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:32:18 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:32:27 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:32:36 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:32:39 - test_network_sriov_stress.py - [line:468] - root - INFO - Ping two vms IP from SUT:
2022-03-14 15:32:43 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.769 ms
2022-03-14 15:32:44 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.253 ms
2022-03-14 15:32:45 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.189 ms
2022-03-14 15:32:46 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.179 ms
2022-03-14 15:32:47 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.111 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.111/0.300/0.769/0.238 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:32:54 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.411 ms
2022-03-14 15:32:55 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.208 ms
2022-03-14 15:32:56 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.204 ms
2022-03-14 15:32:57 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.174 ms
2022-03-14 15:32:58 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.201 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4090ms
rtt min/avg/max/mdev = 0.174/0.239/0.411/0.088 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:33:01 - test_network_sriov_stress.py - [line:476] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 15:33:05 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.274 ms
2022-03-14 15:33:06 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.463 ms
2022-03-14 15:33:07 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.471 ms
2022-03-14 15:33:08 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.461 ms
2022-03-14 15:33:09 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.177 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.177/0.369/0.471/0.121 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:33:18 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 15:33:27 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:41:49 AM EDT
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:37:25 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:33:34 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.279 ms
2022-03-14 15:33:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.331 ms
2022-03-14 15:33:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.208 ms
2022-03-14 15:33:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.241 ms
2022-03-14 15:33:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.276 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.208/0.267/0.331/0.041 ms
root@localhost:~# 
2022-03-14 15:34:18 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:34:21 - test_network_sriov_stress.py - [line:484] - root - INFO - ping VMtest2 IP from VMtest1
2022-03-14 15:34:25 - sshInstance.py - [line:71] - root - INFO - ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
2022-03-14 15:34:28 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
2022-03-14 15:34:31 - sshInstance.py - [line:71] - root - INFO - From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4123ms
pipe 4
[root@WW25ICX2 ~]# 
2022-03-14 15:34:37 - sshInstance.py - [line:46] - root - INFO - echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:34:39 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:34:44 - test_network_sriov_stress.py - [line:264] - root - INFO - Successfully removed VFs from PF.
2022-03-14 15:34:47 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest1
2022-03-14 15:34:47 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 destroyed


2022-03-14 15:34:52 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest1
2022-03-14 15:34:55 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest1
2022-03-14 15:34:55 - sshInstance.py - [line:50] - root - INFO - Domain VMtest1 has been undefined


2022-03-14 15:35:00 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest1
2022-03-14 15:35:03 - sshInstance.py - [line:46] - root - INFO - virsh destroy VMtest2
2022-03-14 15:35:04 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 destroyed


2022-03-14 15:35:09 - test_network_sriov_stress.py - [line:277] - root - INFO - Successfully shut down the VM: VMtest2
2022-03-14 15:35:12 - sshInstance.py - [line:46] - root - INFO - virsh undefine VMtest2
2022-03-14 15:35:12 - sshInstance.py - [line:50] - root - INFO - Domain VMtest2 has been undefined


2022-03-14 15:35:17 - test_network_sriov_stress.py - [line:287] - root - INFO - Successfully removed the VM: VMtest2
2022-03-14 15:35:17 - test_network_sriov_stress.py - [line:389] - root - INFO - 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


2022-03-14 15:35:20 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
2022-03-14 15:35:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:00.0

2022-03-14 15:35:25 - test_network_sriov_stress.py - [line:111] - root - INFO - pf_id was found: 0000:4b:00.0

2022-03-14 15:35:25 - test_network_sriov_stress.py - [line:397] - root - INFO - format_pf_id is 0000\:4b\:00.0

2022-03-14 15:35:25 - test_network_sriov_stress.py - [line:400] - root - INFO - pf_id_key: 4b
2022-03-14 15:35:31 - sshInstance.py - [line:94] - root - INFO - ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
2022-03-14 15:35:34 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens2f0
2022-03-14 15:35:37 - sshInstance.py - [line:46] - root - INFO - echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
2022-03-14 15:35:38 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:35:43 - test_network_sriov_stress.py - [line:125] - root - INFO - Successfully Virtualized PF to VFs.
2022-03-14 15:35:46 - sshInstance.py - [line:46] - root - INFO -  lspci | grep "Virtual" | awk '{print $1;}'list
2022-03-14 15:35:46 - sshInstance.py - [line:50] - root - INFO - 4b:01.0
4b:01.1
4b:01.2
4b:01.3

2022-03-14 15:35:51 - test_network_sriov_stress.py - [line:139] - root - INFO - Succssfully Gotten vf_id list:

2022-03-14 15:35:54 - sshInstance.py - [line:46] - root - INFO - modprobe vfio-pci

2022-03-14 15:35:54 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:36:02 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
2022-03-14 15:36:03 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:36:08 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:36:11 - sshInstance.py - [line:46] - root - INFO - /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
2022-03-14 15:36:12 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:36:17 - test_network_sriov_stress.py - [line:172] - root - INFO - Successfuly bound VF to vfio-pci
2022-03-14 15:36:17 - test_network_sriov_stress.py - [line:421] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:36:20 - sshInstance.py - [line:46] - root - INFO - lspci -Dnn | grep 4b:01.1
2022-03-14 15:36:20 - sshInstance.py - [line:50] - root - INFO - 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

2022-03-14 15:36:25 - test_network_sriov_stress.py - [line:432] - root - INFO - Successfully get vf device id: 8086:1889
2022-03-14 15:36:28 - sshInstance.py - [line:46] - root - INFO - virsh net-info default | grep "Active" | awk '{print $2;}'
2022-03-14 15:36:28 - sshInstance.py - [line:50] - root - INFO - yes

2022-03-14 15:36:33 - test_network_sriov_stress.py - [line:198] - root - INFO - Default network is active? yes

2022-03-14 15:36:37 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14132): [1;33mWARNING[0m **: [34m15:45:01.942[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
2022-03-14 15:36:38 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 15:36:41 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14132): [1;33mWARNING[0m **: [34m15:45:01.942[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 15:36:41 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 15:36:45 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14138): [1;33mWARNING[0m **: [34m15:45:09.952[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:36:48 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:36:51 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest1
2022-03-14 15:36:55 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14182): [1;33mWARNING[0m **: [34m15:45:19.943[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
2022-03-14 15:36:56 - sshInstance.py - [line:71] - root - INFO - [root@WW25ICX2 ~]# 
2022-03-14 15:36:59 - test_network_sriov_stress.py - [line:230] - root - ERROR - Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14182): [1;33mWARNING[0m **: [34m15:45:19.943[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
2022-03-14 15:36:59 - test_network_sriov_stress.py - [line:231] - root - ERROR - Failed to create a VM: 
2022-03-14 15:37:03 - sshInstance.py - [line:71] - root - INFO - virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14189): [1;33mWARNING[0m **: [34m15:45:27.876[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
2022-03-14 15:37:05 - sshInstance.py - [line:71] - root - INFO - Domain creation completed.
[root@WW25ICX2 ~]# 
2022-03-14 15:37:08 - test_network_sriov_stress.py - [line:233] - root - INFO - Successfully created a VM: VMtest2
2022-03-14 15:37:11 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:37:11 - sshInstance.py - [line:50] - root - INFO - 
2022-03-14 15:37:16 - test_network_sriov_stress.py - [line:250] - root - ERROR - not found IP of VMtest1
2022-03-14 15:38:19 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:38:19 - sshInstance.py - [line:50] - root - INFO - 192.168.122.72/24

2022-03-14 15:38:24 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest1 IP: 192.168.122.72/24

2022-03-14 15:38:27 - sshInstance.py - [line:46] - root - INFO - virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
2022-03-14 15:38:27 - sshInstance.py - [line:50] - root - INFO - 192.168.122.208/24

2022-03-14 15:38:32 - test_network_sriov_stress.py - [line:245] - root - INFO - Successfully got VMtest2 IP: 192.168.122.208/24

2022-03-14 15:38:32 - test_network_sriov_stress.py - [line:449] - root - INFO - ip of VM1: 192.168.122.72
2022-03-14 15:38:32 - test_network_sriov_stress.py - [line:450] - root - INFO - ip of VM1: 192.168.122.208
2022-03-14 15:38:36 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.339 ms
2022-03-14 15:38:37 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.465 ms
2022-03-14 15:38:38 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.316 ms
2022-03-14 15:38:39 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.469 ms
2022-03-14 15:38:40 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.473 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4082ms
rtt min/avg/max/mdev = 0.316/0.412/0.473/0.072 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:38:49 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.72
root@192.168.122.72's password: 
2022-03-14 15:38:58 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:47:20 AM EDT
  System load:  0.0                Processes:             135
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:41:49 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:39:07 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
2022-03-14 15:39:13 - test_network_sriov_stress.py - [line:341] - root - INFO - successfully got vf pci id of vm1: 0000:00:05.0
2022-03-14 15:39:19 - sshInstance.py - [line:94] - root - INFO - ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
2022-03-14 15:39:24 - test_network_sriov_stress.py - [line:355] - root - INFO - Successfully got vf device name of vm1: ens5
2022-03-14 15:39:30 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 192.168.10.12
root@localhost:~# 
2022-03-14 15:39:33 - test_network_sriov_stress.py - [line:302] - root - INFO - Successfully assigned ip to ethernet: ens5
2022-03-14 15:39:39 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 down
root@localhost:~# 
2022-03-14 15:39:49 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
2022-03-14 15:39:58 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5 up
root@localhost:~# 
2022-03-14 15:40:07 - sshInstance.py - [line:94] - root - INFO - nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
2022-03-14 15:40:16 - sshInstance.py - [line:94] - root - INFO - ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
2022-03-14 15:40:25 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
2022-03-14 15:40:32 - sshInstance.py - [line:71] - root - INFO - ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.331 ms
2022-03-14 15:40:33 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.461 ms
2022-03-14 15:40:34 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.468 ms
2022-03-14 15:40:35 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.394 ms
2022-03-14 15:40:36 - sshInstance.py - [line:71] - root - INFO - 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.197 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4110ms
rtt min/avg/max/mdev = 0.197/0.370/0.468/0.100 ms
[root@WW25ICX2 ~]# 
2022-03-14 15:40:45 - sshInstance.py - [line:94] - root - INFO - ssh root@192.168.122.208
root@192.168.122.208's password: 
2022-03-14 15:40:54 - sshInstance.py - [line:94] - root - INFO - 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:49:16 AM EDT
  System load:  0.0                Processes:             139
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:39:30 2022 from 192.168.122.1
root@localhost:~# 
2022-03-14 15:41:03 - sshInstance.py - [line:94] - root - INFO - lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
root@localhost:~# 
2022-03-14 15:41:09 - test_network_sriov_stress.py - [line:357] - root - INFO - Faile to get vf pci id of vm1.
2022-03-14 15:41:15 - sshInstance.py - [line:94] - root - INFO - exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
------------------------------ Captured log call -------------------------------
INFO     root:test_network_sriov_stress.py:389 

********************************************************Stress Disable and Enable for 1 time when VF is Assigned VM guest.*************************************************************


INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
INFO     root:sshInstance.py:50 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:111 pf_id was found: 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:397 format_pf_id is 0000\:4b\:00.0

INFO     root:test_network_sriov_stress.py:400 pf_id_key: 4b
INFO     root:sshInstance.py:94 Activate the web console with: systemctl enable --now cockpit.socket
This system is not registered to Red Hat Insights. See https://cloud.redhat.com/
To register this system, run: insights-client --register
Last login: Mon Mar 14 15:31:58 2022 from 10.112.97.60
[root@WW25ICX2 ~]# ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:125 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:46  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:50 4b:01.0
4b:01.1
4b:01.2
4b:01.3

INFO     root:test_network_sriov_stress.py:139 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:46 modprobe vfio-pci

INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:421 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:46 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:50 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:432 Successfully get vf device id: 8086:1889
INFO     root:sshInstance.py:46 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 no

INFO     root:test_network_sriov_stress.py:198 Default network is active? no

INFO     root:test_network_sriov_stress.py:207 virsh net-start default
INFO     root:sshInstance.py:46 virsh net-start default
INFO     root:sshInstance.py:50 Network default started


INFO     root:test_network_sriov_stress.py:211 Successfully started network default.
INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole
INFO     root:sshInstance.py:71 
** (process:12973): [1;33mWARNING[0m **: [34m15:35:12.796[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest1
INFO     root:sshInstance.py:71 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:13022): [1;33mWARNING[0m **: [34m15:35:22.531[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
INFO     root:sshInstance.py:71 WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest1
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.72/24

INFO     root:test_network_sriov_stress.py:245 Successfully got VMtest1 IP: 192.168.122.72/24

INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.208/24

INFO     root:test_network_sriov_stress.py:245 Successfully got VMtest2 IP: 192.168.122.208/24

INFO     root:test_network_sriov_stress.py:449 ip of VM1: 192.168.122.72
INFO     root:test_network_sriov_stress.py:450 ip of VM1: 192.168.122.208
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.335 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.466 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.280 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.470 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.466 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4116ms
rtt min/avg/max/mdev = 0.280/0.403/0.470/0.082 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.72
The authenticity of host '192.168.122.72 (192.168.122.72)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
INFO     root:sshInstance.py:94 yes
Warning: Permanently added '192.168.122.72' (ECDSA) to the list of known hosts.
root@192.168.122.72's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:37:25 AM EDT
  System load:  0.04               Processes:             141
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Sun Mar 13 22:44:25 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:341 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.12
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 1  bytes 346 (346.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.284 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.471 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.326 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.276 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.273 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4118ms
rtt min/avg/max/mdev = 0.273/0.326/0.471/0.074 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.208
The authenticity of host '192.168.122.208 (192.168.122.208)' can't be established.
ECDSA key fingerprint is SHA256:uiL9MQ8j64kizIc2NkvuxVE93C2YBfGXw5p1QHW5dUA.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
INFO     root:sshInstance.py:94 yes
Warning: Permanently added '192.168.122.208' (ECDSA) to the list of known hosts.
root@192.168.122.208's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:39:30 AM EDT
  System load:  0.0                Processes:             137
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Sun Mar 13 22:46:21 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:341 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.13
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ab
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.13  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ab  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ab  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:468 Ping two vms IP from SUT:
INFO     root:sshInstance.py:71 ping -c 5 192.168.10.12
PING 192.168.10.12 (192.168.10.12) 56(84) bytes of data.
64 bytes from 192.168.10.12: icmp_seq=1 ttl=64 time=0.769 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.12: icmp_seq=2 ttl=64 time=0.253 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.12: icmp_seq=3 ttl=64 time=0.189 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.12: icmp_seq=4 ttl=64 time=0.179 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.12: icmp_seq=5 ttl=64 time=0.111 ms

--- 192.168.10.12 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4097ms
rtt min/avg/max/mdev = 0.111/0.300/0.769/0.238 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.411 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.208 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.204 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.174 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.201 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4090ms
rtt min/avg/max/mdev = 0.174/0.239/0.411/0.088 ms
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:476 ping VMtest2 IP from VMtest1
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.274 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.463 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.471 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.461 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.177 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4085ms
rtt min/avg/max/mdev = 0.177/0.369/0.471/0.121 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.72
root@192.168.122.72's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:41:49 AM EDT
  System load:  0.0                Processes:             130
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%                 IPv4 address for ens5: 192.168.10.12

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:37:25 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.10.13
PING 192.168.10.13 (192.168.10.13) 56(84) bytes of data.
64 bytes from 192.168.10.13: icmp_seq=1 ttl=64 time=0.279 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=2 ttl=64 time=0.331 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=3 ttl=64 time=0.208 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=4 ttl=64 time=0.241 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.10.13: icmp_seq=5 ttl=64 time=0.276 ms

--- 192.168.10.13 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4075ms
rtt min/avg/max/mdev = 0.208/0.267/0.331/0.041 ms
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:484 ping VMtest2 IP from VMtest1
INFO     root:sshInstance.py:71 ping -c 5 -I 192.168.10.10 192.168.10.11
PING 192.168.10.11 (192.168.10.11) from 192.168.10.10 : 56(84) bytes of data.
INFO     root:sshInstance.py:71 From 192.168.10.10 icmp_seq=1 Destination Host Unreachable
From 192.168.10.10 icmp_seq=2 Destination Host Unreachable
From 192.168.10.10 icmp_seq=3 Destination Host Unreachable
INFO     root:sshInstance.py:71 From 192.168.10.10 icmp_seq=4 Destination Host Unreachable
From 192.168.10.10 icmp_seq=5 Destination Host Unreachable

--- 192.168.10.11 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4123ms
pipe 4
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:46 echo 0 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:264 Successfully removed VFs from PF.
INFO     root:sshInstance.py:46 virsh destroy VMtest1
INFO     root:sshInstance.py:50 Domain VMtest1 destroyed


INFO     root:test_network_sriov_stress.py:277 Successfully shut down the VM: VMtest1
INFO     root:sshInstance.py:46 virsh undefine VMtest1
INFO     root:sshInstance.py:50 Domain VMtest1 has been undefined


INFO     root:test_network_sriov_stress.py:287 Successfully removed the VM: VMtest1
INFO     root:sshInstance.py:46 virsh destroy VMtest2
INFO     root:sshInstance.py:50 Domain VMtest2 destroyed


INFO     root:test_network_sriov_stress.py:277 Successfully shut down the VM: VMtest2
INFO     root:sshInstance.py:46 virsh undefine VMtest2
INFO     root:sshInstance.py:50 Domain VMtest2 has been undefined


INFO     root:test_network_sriov_stress.py:287 Successfully removed the VM: VMtest2
INFO     root:test_network_sriov_stress.py:389 

********************************************************Stress Disable and Enable for 2 time when VF is Assigned VM guest.*************************************************************


INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -s | grep ens2f0 | awk '{print $1;}'
INFO     root:sshInstance.py:50 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:111 pf_id was found: 0000:4b:00.0

INFO     root:test_network_sriov_stress.py:397 format_pf_id is 0000\:4b\:00.0

INFO     root:test_network_sriov_stress.py:400 pf_id_key: 4b
INFO     root:sshInstance.py:94 ifconfig ens2f0 192.168.10.10
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens2f0
INFO     root:sshInstance.py:46 echo 4 > /sys/class/net/ens2f0/device/sriov_numvfs
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:125 Successfully Virtualized PF to VFs.
INFO     root:sshInstance.py:46  lspci | grep "Virtual" | awk '{print $1;}'list
INFO     root:sshInstance.py:50 4b:01.0
4b:01.1
4b:01.2
4b:01.3

INFO     root:test_network_sriov_stress.py:139 Succssfully Gotten vf_id list:

INFO     root:sshInstance.py:46 modprobe vfio-pci

INFO     root:sshInstance.py:50 
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.0
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:sshInstance.py:46 /opt/APP/utility/DPDK_install/dpdk-stable-20.11.1/usertools/dpdk-devbind.py -b vfio-pci 4b:01.1
INFO     root:sshInstance.py:50 
INFO     root:test_network_sriov_stress.py:172 Successfuly bound VF to vfio-pci
INFO     root:test_network_sriov_stress.py:421 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:46 lspci -Dnn | grep 4b:01.1
INFO     root:sshInstance.py:50 0000:4b:01.1 Ethernet controller [0200]: Intel Corporation Ethernet Adaptive Virtual Function [8086:1889] (rev 02)

INFO     root:test_network_sriov_stress.py:432 Successfully get vf device id: 8086:1889
INFO     root:sshInstance.py:46 virsh net-info default | grep "Active" | awk '{print $2;}'
INFO     root:sshInstance.py:50 yes

INFO     root:test_network_sriov_stress.py:198 Default network is active? yes

INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14132): [1;33mWARNING[0m **: [34m15:45:01.942[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
INFO     root:sshInstance.py:71 [root@WW25ICX2 ~]# 
ERROR    root:test_network_sriov_stress.py:230 Failed to create a VM: virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14132): [1;33mWARNING[0m **: [34m15:45:01.942[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.0 is in use by driver QEMU, domain VMtest1
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest1
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
ERROR    root:test_network_sriov_stress.py:231 Failed to create a VM: 
INFO     root:sshInstance.py:71 virt-install --name VMtest1 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_0 --boot hd --disk path=/home/iimage/uvm2.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5900 --noaautoconsole

** (process:14138): [1;33mWARNING[0m **: [34m15:45:09.952[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest1
INFO     root:sshInstance.py:71 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14182): [1;33mWARNING[0m **: [34m15:45:19.943[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
INFO     root:sshInstance.py:71 [root@WW25ICX2 ~]# 
ERROR    root:test_network_sriov_stress.py:230 Failed to create a VM: virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14182): [1;33mWARNING[0m **: [34m15:45:19.943[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
ERROR    Requested operation is not valid: PCI device 0000:4b:01.1 is in use by driver QEMU, domain VMtest2
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VMtest2
otherwise, please restart your installation.
[root@WW25ICX2 ~]# 
ERROR    root:test_network_sriov_stress.py:231 Failed to create a VM: 
INFO     root:sshInstance.py:71 virt-install --name VMtest2 --ram 4096 --cpu host --vcpus=5 ---network network=default --hostdev pci_0000_4b_01_1 --boot hd --disk path=/home/iimage/uvm1.img,size=50,format=qcow2 --graphics vnc,listen=0.0.0.0,port=5901 --noaautoconsole

** (process:14189): [1;33mWARNING[0m **: [34m15:45:27.876[0m: Entity http://pcisig.com/pci/1B36/0100 referenced but not defined
WARNING  No operating system detected, VM performance may suffer. Specify an OS with --os-variant for optimal results.

Starting install...
INFO     root:sshInstance.py:71 Domain creation completed.
[root@WW25ICX2 ~]# 
INFO     root:test_network_sriov_stress.py:233 Successfully created a VM: VMtest2
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 
ERROR    root:test_network_sriov_stress.py:250 not found IP of VMtest1
INFO     root:sshInstance.py:46 virsh domifaddr VMtest1 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.72/24

INFO     root:test_network_sriov_stress.py:245 Successfully got VMtest1 IP: 192.168.122.72/24

INFO     root:sshInstance.py:46 virsh domifaddr VMtest2 | grep '192.168' | awk '{print $4;}'
INFO     root:sshInstance.py:50 192.168.122.208/24

INFO     root:test_network_sriov_stress.py:245 Successfully got VMtest2 IP: 192.168.122.208/24

INFO     root:test_network_sriov_stress.py:449 ip of VM1: 192.168.122.72
INFO     root:test_network_sriov_stress.py:450 ip of VM1: 192.168.122.208
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.72
PING 192.168.122.72 (192.168.122.72) 56(84) bytes of data.
64 bytes from 192.168.122.72: icmp_seq=1 ttl=64 time=0.339 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=2 ttl=64 time=0.465 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=3 ttl=64 time=0.316 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=4 ttl=64 time=0.469 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.72: icmp_seq=5 ttl=64 time=0.473 ms

--- 192.168.122.72 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4082ms
rtt min/avg/max/mdev = 0.316/0.412/0.473/0.072 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.72
root@192.168.122.72's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:47:20 AM EDT
  System load:  0.0                Processes:             135
  Usage of /:   40.2% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.72
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:41:49 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
0000:00:05.0
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:341 successfully got vf pci id of vm1: 0000:00:05.0
INFO     root:sshInstance.py:94 ls /sys/bus/pci/devices/0000\:00\:05.0/net/ --color=never
ens5
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:355 Successfully got vf device name of vm1: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 192.168.10.12
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:302 Successfully assigned ip to ethernet: ens5
INFO     root:sshInstance.py:94 ifconfig ens5 down
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 hw ether 1234567890ac
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5 up
root@localhost:~# 
INFO     root:sshInstance.py:94 nmcli device connect ens5
Command 'nmcli' not found, but can be installed with:
apt install network-manager
root@localhost:~# 
INFO     root:sshInstance.py:94 ifconfig ens5
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.12  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::1034:56ff:fe78:90ac  prefixlen 64  scopeid 0x20<link>
        ether 12:34:56:78:90:ac  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 766 (766.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@localhost:~# 
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.72 closed.
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:71 ping -c 5 192.168.122.208
PING 192.168.122.208 (192.168.122.208) 56(84) bytes of data.
64 bytes from 192.168.122.208: icmp_seq=1 ttl=64 time=0.331 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=2 ttl=64 time=0.461 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=3 ttl=64 time=0.468 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=4 ttl=64 time=0.394 ms
INFO     root:sshInstance.py:71 64 bytes from 192.168.122.208: icmp_seq=5 ttl=64 time=0.197 ms

--- 192.168.122.208 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4110ms
rtt min/avg/max/mdev = 0.197/0.370/0.468/0.100 ms
[root@WW25ICX2 ~]# 
INFO     root:sshInstance.py:94 ssh root@192.168.122.208
root@192.168.122.208's password: 
INFO     root:sshInstance.py:94 
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
  System information as of Mon 14 Mar 2022 03:49:16 AM EDT
  System load:  0.0                Processes:             139
  Usage of /:   40.9% of 19.07GB   Users logged in:       0
  Memory usage: 4%                 IPv4 address for ens3: 192.168.122.208
  Swap usage:   0%

380 updates can be installed immediately.
252 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Last login: Mon Mar 14 03:39:30 2022 from 192.168.122.1
root@localhost:~# 
INFO     root:sshInstance.py:94 lspci -Dnn | grep "8086:1889" --color=never| awk '{print $1;}' [A        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [C        [K            '
root@localhost:~# 
INFO     root:test_network_sriov_stress.py:357 Faile to get vf pci id of vm1.
INFO     root:sshInstance.py:94 exit
logout
Connection to 192.168.122.208 closed.
[root@WW25ICX2 ~]#
=============================== warnings summary ===============================
npxtester/Tests/testNics/test_iperf_client_4hour.py:70
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_tcp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_tcp

npxtester/Tests/testNics/test_iperf_client_4hour.py:108
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_iperf_client_4hour.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.iperf_udp - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.iperf_udp

npxtester/Tests/testNics/test_mtu.py:69
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:70
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:70: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_mtu.py:109
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:109: PytestUnknownMarkWarning: Unknown pytest.mark.two_sut_CVL - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.two_sut_CVL

npxtester/Tests/testNics/test_mtu.py:110
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_mtu.py:110: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_network_sriov_stress.py:383
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:383: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov5times - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov5times

npxtester/Tests/testNics/test_network_sriov_stress.py:500
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:500: PytestUnknownMarkWarning: Unknown pytest.mark.nicSriov2hours - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSriov2hours

npxtester/Tests/testNics/test_network_sriov_stress.py:799
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_network_sriov_stress.py:799: PytestUnknownMarkWarning: Unknown pytest.mark.SriovVfIperf - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.SriovVfIperf

npxtester/Tests/testNics/test_nics.py:92
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:92: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:117
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:117: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:141
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:141: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:173
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:173: PytestUnknownMarkWarning: Unknown pytest.mark.driveInstall - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.driveInstall

npxtester/Tests/testNics/test_nics.py:213
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:213: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

npxtester/Tests/testNics/test_nics.py:239
  /root/.jenkins/workspace/test-test-nic-sriov-5times/npxtester/Tests/testNics/test_nics.py:239: PytestUnknownMarkWarning: Unknown pytest.mark.nicSimple - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.nicSimple

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated html file: file:///root/testconfig/testlogs/HtmlReport/nic_sriov5times_case_report.html -
=========================== short test summary info ============================
FAILED npxtester/Tests/testNics/test_network_sriov_stress.py::Test_Network_SRIOV_Stress::test_PI_Networking_SRIOV_StressDisableEnableFor5TimesWhenVFIsAssigned_VM_Guest[uvm2.img-uvm1.img]
========== 1 failed, 16 deselected, 15 warnings in 1100.34s (0:18:20) ==========
[8mha:////4LeiMYyvaTAszhIQ10pdIeDepJ20hGjpoNTSDQ54vTlOAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIi0SCEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQGMKkS1vgAAAA==[0m[Pipeline] }
[8mha:////4I/tRoD/KV6lJ76TTEJ8vusLD5mbZiDJ1z7tZBIwhHThAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOKCQKJBqWgtN7zAJMY4se6C7eBUvIiv8QcsIlGxxWpnm3m9YRk81OwNdpp6S6GxOLjR5IWJfX91nLDjCzZMgZ1GqZPkVp9mlBw1zClKWAhYaWocB0smwlp06qEqp8hU5+jzdxRQ2vYOTyhENkfl4xcmD5vb2Aamn+evAKZhiFDut7l2hw9mQDtDvgAAAA==[0m[Pipeline] // stage
[8mha:////4CAP7WQdC2FMpNczqgZSKdPjM+Zu6Lz59I8VEE3/AlUOAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjBB2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INOibpDcEAAAA=[0m[Pipeline] stage
[8mha:////4Db8sOlSRxZnVxb7xJBDSAteoF0PgC9lkQldzKIJFwYiAAAAph+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUwIiYukZZOEFoQkgb/V9+UtqJE3E17kBLJSY8WLYl673eUESGE7ETjcXWY6y96ELvpiQG4vYaaBANXURNGClYoeygyNhqqYqShUVZDisJa4t1oOjRJdjIRj90GTS68px42o4Scm/u8IRMTuSkOX3LyLC99SYS/jh/ATB2CfLDbrb9/Cw+2YMO4MIAAAA=[0m[Pipeline] { (collect logs)
Stage "collect logs" skipped due to earlier failure(s)
[8mha:////4AfI3SthhIf/wHKBxkZZVuznCBOLGICd+mTaK5J1XhvpAAAAox+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIikRJR0VppeIFJjLFj3Tm2g1PxIr7GHwhEomKL1c4283zBOgY4ctBoFfWGYmvQu1HPCzOH/uo4o+ULtkyRncJG5YY7dVqw4aRgSVHCSsBGUes4GtIJtsLKu6ycJF2dU5i/g4DSdAM8oBCzOcmQvjAF2N3GLjL9PH8FMHmfoKzrT+3fkMfZ274AAAA=[0m[Pipeline] }
[8mha:////4O1G14z5oV6C9jl1Q5yIn+pZFQRmsElhyj6JiXyHA8ixAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiBB2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7BpKm1V++AAAA[0m[Pipeline] // stage
[8mha:////4KtBCOpIKS64HlRGbxVDHBnhT4546C6ceKSEgLxKWO63AAAAox+LCAAAAAAAAP9tjTESgjAQRT84FraWHiIUauVY2WZoPEGEGAOZXUwWofJEXs07yMiMlb/67zXv9cYyRRw5OtVYaj2lyqsu9G56auDYXgMPquGLqpgSB6tKO5Rc29OMJYvFvCzHQmNlqQqcPDnBWjfmYYpgyBVniZM7aOS+vuOJTE9lMVG+MEZsbn2dmH6dvwGMXSfIt3tBtvsA/gVtV70AAAA=[0m[Pipeline] }
[8mha:////4PVa+eOfGCB5ryE2GyokIfyPZOVvh3emQVgJTOuHuCGAAAAAox+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IMJC7GybVh8Qsq1Fpo3sP2IUx+kb/mP0gkcfJO95zlvN5Yp4gjR6daS52nVHvVh8HNT40cu2vgUbV8UTVT4mBVZceKG3tasGKxWJblWGlsLNWBkycn2OrWPEwRDLniLHF2B43cN3c8kem5LCbKF6aI3W1oEtOv8zeAqe8FebkXZOUHjeqpjr0AAAA=[0m[Pipeline] // node
[8mha:////4OyM7hMK6utvbTfbnNkjhtaoCHWCq3+ZbQ+BNe9AvJHZAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMKRoKBAVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Lu9INt+AKvzzsS9AAAA[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
